### ISSUE TITLE
4.1.1 - Design of portal (interface) (Community portal)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#104]
User friendly design of portal, wireframes

**Comment by fwelter** [comment]
Avoid various frames inside other frames. Hold the portal as simple as possible.

**Comment by JiriFrank** [comment]
The new template will be instaled today between 2:30 - 3:30 pm. 

We are also working on new concept of the portal design. 
This concept is also close related with implementation developed features in modules on the portal.

**Comment by JiriFrank** [comment]
Draft design for whole portal is done. The integration phase is related according to portal features developing proces.

**Comment by JiriFrank** [comment]
4.1.1 - Design of portal (interface) (Community portal)

COR number: 4.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Portal design

Description:

User friendly design of portal, wireframes

Any comments regarding the overall portal design are welcome.

Several parts of portal are still under developing and will be changed in some details.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
4.1.1 - Design of portal (interface) (Community portal)

COR number: 4.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Portal design

Description:

User friendly design of portal, wireframes

Any comments regarding the overall portal design are welcome.

Several parts of portal are still under developing and will be changed in some details.

@AntonioGVH
@fwelter
@LarissaS

**Comment by HenningScholz** [comment]
No comment now, but I see a significant different difference between IE9 and Firefox 9.0.1. Advanced search is not useable in Firefox, very strange.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 15:26
An: Scholz, Henning
Betreff: Re: [bhle] 4.1.1 - Design of portal (interface) (Community portal) (#104)

4.1.1 - Design of portal (interface) (Community portal)

COR number: 4.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Portal design

Description:

User friendly design of portal, wireframes

Any comments regarding the overall portal design are welcome.

Several parts of portal are still under developing and will be changed in some details.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by RalfH** [comment]
Generally, I like the design. Compared to BHL portal much more inviting, userfriendly and decently coloured. Some remarks:

(1) Search results (text right hand to icon): The titles are cut in the 3rd line as are authors etc. in the 2nd. Well, there is a mouse over functionality but the cutting is a bit ugly. I would prefer full lines whatever their number may be.

(2) The mixture of German and English (Save query, zurücksetzen ...) obviously will be changed?

(3) expand search tick box: it took my some time in the beginning to understand what that means. You find an explanation in the tutorial. And there is another one at the bottom of the page. But if you are in the advanced search modus you need to scroll to find it. A mouse over short explanation could help to make that userfriendlier.

(4) tick box for exact word / phrase: Seems a bit displaced in one line with expand search and simple search. Expand search and exact word/phrase placed a bit lower?

(5) Login /create account: What is it for? An internal thing? What does it mean for the common user? Does a registration make sense for the occasional visitor?

(6) Advanced search: Why are there OR and NOT buttons but no AND or + button? Well, after some testing you may realize that you can type a + but this is not selfexplanatory.

(7) It took me some time to find the BHL-E newsletter. A more prominent presentation would be useful. Not all users (even the non-elderly) are obsessed with facebook and twitter ...

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:26
An: Hand, Ralf
Betreff: Re: [bhle] 4.1.1 - Design of portal (interface) (Community portal) (#104)

4.1.1 - Design of portal (interface) (Community portal)

COR number: 4.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Portal design

Description:

User friendly design of portal, wireframes

Any comments regarding the overall portal design are welcome.

Several parts of portal are still under developing and will be changed in some details.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by fwelter** [comment]
I have Mozilla Firefox 5/0 on my notebook. The portal does not show the
search box properly. Several components of the website seem to be
distorted. The search box seems to be covered by the the moving pictures
of the books. If I try to insert someting in the search box I click on a
link to a page saying "Seite nicht gefunden" (page not found).

I will try with another computer.

Francisco

> 4.1.1 - Design of portal (interface) (Community portal)
> 
> COR number: 4.1.1
> Testing platform: http://bhl-test.nhm.ac.uk/portal/
> Function: Portal design
> 
> Description:
> 
> User friendly design of portal, wireframes
> 
> Any comments regarding the overall portal design are welcome.
> 
> Several parts of portal are still under developing and will be changed in
> some details.
> 
> @AntonioGVH
> @fwelter
> @LarissaS
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bhle/bhle/issues/104#issuecomment-3561026

Francisco Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536
http://www.animalbase.org

**Comment by grahamhrbge1670** [comment]
Overall design very good.  

Particularly like the colour palette used.  The simple search box is well positioned and uncluttered, and the browse and tutorial radio buttons are obvious.  

Positioning of tutorial buttons good throughout the various levels of search.

**Comment by fwelter** [comment]
In Mozilla Firefox Version 3.0.19 (institute computer from 2008) I can see
the portal website in a form as it should probably be.

In Mozilla Firefox version 2.0.0.16 (from 2006) not. This is my notebook,
so I am not able to test the portal at weekends. I can only test during
the week.

Test from institute computer.

I am only looking at design questions here for this question. But maybe
some observations noted here need to be pasted to somewhere else.

The portal search page contains moving images. I have the problem that
moving images on a computer screen make me a headache, so I cannot work
long time. When I work at a computer I need a silent screen. When the
website has moving and blinking images I try to avoid these by scrolling
them away. If this is not possible I try to leave the website as soon as
possible.

The moving images also distort from working.

The headline shows a mixture of German and Engish, this looks unprofessional:

```
* Home
* Über uns
* Contact Us
* Login/Create Account
```

If I select the Portuguese version the link "Über uns" (about us) does not
show up. Same with French and Spanish versions.

Switching between language versions takes 6 seconds for the screen to
re-appear.

In the headline the search options title, author, year and "advanced
search" appear in local languages (German, French, Spanish etc.), "search
in" and "Scientific Name" in English. Language mixup.

"Browse" button: In Italian version I can only read "Navigazion", probably
the word is too long (which means it is formatted too large). Portuguese,
German and Dutch versions show the English term "Browse", the others the
local language term.

"Tutorial" button: if I open this link in a new window (with right mouse)
I come to exactly the same search page, but always in German,
independently from which language I click on this link.
If I click on the link (with left mouse) a popup opens which shows an
English text (two headlines, Simple search and My account), invariably
from which language version I click on this link.

The popup needs 6 seconds to load in. The mouse moves slowly when the
popup is open. When I close the popup (X in right upper corner) it takes 6
seconds until it is closed. Then the mouse is fast again as usual.

Clicking on the moving book images leads to a page "page not found".

sorry, my mailer has probably cut the rest of the text. Or maybe you get
two messages.

Francisco

**Comment by fwelter** [comment]
I have switched between language versions and advanced search pages, the
language information is always lost when I come to a new page. I always
land at a German page.

The lower part of the letters in the search field of the advanced search
page is cut off and not shown.

I tried to type in "remarques" an "Remarques" in simple and advanced
search and obtained a page "your search yielded no results".
If I type in "Remarques" and press return then "OR" is added to the term.

I have the feeling that the portal is not ready for being presented to the
public. It takes probably a long time until the user will find out how to
skip all the bugs to find something.

Francisco

**Comment by AntonioGVH** [comment]
I like very much the portal, but I am not very objective.

The portal detects that I am Spanish and give many entries in Spanish but some other are simultaneously in English.

Do you need more help translating to Spanish?

Screen shot included

Quoting JiriFrank:

**Comment by LarissaS** [comment]
- I like the start page, but content highlights do not work yet I suppose? 
- In browse page the font is too big, may be if we make it smaller than we can see all browsing features on the screen without replacing it?
- Search page - still a lot of bugs, 
- Book View page - fine
- Bibliographic page - fine, with some small bugs
- Login/create account - works, but window was VERY small! 

General impression is good, hopefully after this testing it will be even better and will work perfectly!

Success
Larissa

-----Original Message-----

**Comment by fwelter** [comment]
Firefox 8.0 from a home computer.

main search page seems to be displayed correctly.
when I searched for "remarques" and pressed return the website gave no
response.
when I searched for "remarques" and pressed two times return, the search
query was understood and the action started.

I suspect a bug. Should understand the return at the first time.

I tried the same with clicking on the search button. when I clicked one
time on the search button, nothing happened. when I clicked two times on
it, the search function was understood and the query started.

I suspect a bug. Should start search at first click.

the number of results found was 0. so the search did not work because
there is a title with the word "remarques" in the books we should search
for.

I obtained a new screen (I call it "adavnced search page")

in the search box I saw a text displayed "tvpe what do vou want to search"
(the lower parts of y and p are not shown).

this was basically the same bug as at the other computer I had reported
before, but here a little more of the letters was shown. at the other
computer the cut of the letters was slightly more above.

I suspect a browser<->portal interaction bug.

in the advanced search mode I typed "remarques" and pressed return. this
had the effect that the word "OR" was inserted in the search box, nothing
more. when I pressed return 5 times I obtained "remarques OR OR OR OR OR",
the query was not started.

I suspect a bug. The word "OR" should not be inserted at return. The query
should be submitted at return.

pressing the "Reset" button had no effect, neither in the English nor in
the German version.

I suspect a bug. "Reset" should empty the search box.

I typed in "remarques" and pressed on the search button.

this query did not yield a result.

I suspect a bug. A title containing the word "remarques" is contained.

I used the "Browse" function and saw alphabetical letters displyed at
which I could click. I clicked "H". I obtained 5 titles, none of the
titles and authors begant with "H". One of the books had the word
"Beschrijving" in the title.

I went back to the search page and inserted a search term "beschrijving".

I obtained the "advanced search page" with this one title "Onze flora,
Beschrijving..." correctly listed in a square.

I went back to the main portal entry search page and inserted again
"remarques".
No results were obtained again, but in the search box of the advanced
search page which appeared to tell me that nothing was found, the word
"beschrijving" was inserted.

I suspect a bug. The program has forgotten that I had been looking for
"remarques".

I used the Browse function and selected the letter "I". A title with the
word "Remarques" appeared as the third hit. So this book is known to the
program and was not found in the simple search by title.

Maybe Jiri you can copy this observation or other observations to an other
github where it belongs. I fear that if I open a new mail page then the
information on this one can be lost (this has happened last time). The
university mail program I am using here is not so good.

Design of the presentation of the results:

The displayed title I have searched with the word "beschrijving" was (I
write the hard returns here as I saw it on the screen):
Onze flora:
Beschrijving van de
(in the next line I saw one word familiän or so, I could not see it, it
was formatted in fading colours and showed only the upper 1/3 section of
the letters, the lower parts of the letters were cut off)
Oudemans,
Antonie Cornelis (these words were displayed in fading colour and the
lowest parts of the letters were cut)
1900
W.J. Thieme
View record   Read book

I think that too few title words are shown.
I went with the mouse on the first letters of the title (Onze flora...)
and suddenly the screen showed the whole title.
When I wanted to read the other titles I had to go with the mouse to every
single title and was always only able to read one title at a time, which
disappeared immediately after I went somewhere else with the mouse. I
could not compare longer title texts.
I was not able to copy the title in this mode.

I used the Browse function (by title) and searched for "E". 13 titles were
found. Only 12 were displayed on the first screen.

when I clicked on [page] "2", or on "last page" (to see hit no. 10-13), I
obtained a page saying "your search yielded no results".

I tried the same with "Browse by title" "S": 14 results, only 12 were
displeyed, when I clicked "2", "next page" or "last page" to see results
13-14 I obtained always a page saying "your search yielded no results".

I suspect a bug.

On that page I clicked on an arrow "step back", then I was redirected to
the previous page with the exception that all the information at the
left-side frame was not shown any more (it was replaced by a white space).

I suspect a bug.

I clicked once again on "last page" (same with "next page") and obtained
once again a page saying "your search yielded no results", but this time
the screen looked differently, the left frame was not shown (and no "step
back" arrow"), and the 3-lines text below occupied the whole width of the
screen.

So the left-frame information was lost at both occasions.

Browse function "Search by author": I searched for "H" and obtained 7
results, only one author began with H.
Similar results with E and other letters. It was not intelligible why
these results were displayed and what they had to do with the query.

Browse function "Search by journal title": whatever I searched here, I
always obtained a "page not found" error message (not a message "your
query did not yield results").

I clicked on the "Read book" function of a title. The book viewer opened
and showed the book.

Book reader

The first page shown was the cover of the book ("Uber die Okologie und
Verbreitung..." - in this title the German umlauts were not correctly
displayed). The basic functions seemed to work.
There was no page-level scrollbox, as in BHL, Gallica, SUB Goettingen and
other well-known online library services.
On the headline was displayed one line with the title. Clicking on this
line returned me to the first page of the book (which was the cover) (I
would have expected to be directed to the record page at this occasion).
On the right corner there was a function icon "Play" - this gave no
reaction when I clicked on it. I have no idea for what it should be good.
The page display was incorrect. I wanted to go to p. 266 and came to p.
262/263 (other pages likewise). It was not always possible to insert a
number in the page selection box and click return to start the job.
Sometimes the program did not understand that I have clicked "return". I
suspect bugs.
The navigation bars covered the upper and lower parts of the book, so that
it was not possible to read the correct page number without hiding the
navigation bar.
In the OCR the German umlauts were not displayed (ä = a, ü = ii, ö = 6/),
the OCR was of an extremely low quality. Searching for correctly OCR'd
words worked.

Internet Explorer 6.0 from 2004 from the same computer:

Portal page was not displayed correctly, all buttons, boxes and other
elements were totally distorted. it was not possible to change languages.
it was possible to insert words in the search box.

searching for "beschrijving" returned a page "your query did not yield
results".

the same query had yielded a result in the Firefox search, but obviously
not in the IE search.

this page was an equivalent of the "advanced search page", but boxes and
written elements were so much distorted that it was not possible to insert
a query in a search box.
I clicked on the "Browse" function. A very distorted page appeared, it was
not possible to click anything on it or to scroll down. After 14 seconds
it suddenly displayed a slightly less distorted page, displaying the
letters.

I clicked on letter "H" (title search) and obtained 5 results. The page
loaded in after 4 seconds, but it took another 13 seconds until it was
possible to click somewhere or scroll down. The page was much more
distorted than in Firefox, and the colours looked differently, the BHL-E
logo was on brown background and many white fields were brown as well.
It was possible to click at the results. It was not possible to see longer
title texts with the mouse.

I clicked on "View record" and obtained the correct record page.

I clicked on "Read book", the reader was opened, but contained no book.

The portal cannot be used with this browser, many key functions do not
work at all.

General comment on the portal design: too little information shown on the
search and result set pages, too much space wasted. Too much white space.
Portal cannot be used with moderately old browsers, a serious shortcoming.

I tried 4 browsers, all less than 10 years old, at 2 it was impossible to
work, at two others I was able to work but observed bugs which were
probably related to imcompatibility problems browser<->portal.

Francisco

> 4.1.1 - Design of portal (interface) (Community portal)
> COR number: 4.1.1
> Testing platform: http://bhl-test.nhm.ac.uk/portal/
> Function: Portal design
> Description:
> User friendly design of portal, wireframes
> Any comments regarding the overall portal design are welcome.
> Several parts of portal are still under developing and will be changed
> in
> some details.
> @AntonioGVH
> @fwelter
> 
> ## @LarissaS
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bhle/bhle/issues/104#issuecomment-3561026

Francisco Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536
http://www.animalbase.org

**Comment by fwelter** [comment]
Design of portal in Internet Explorer 5.0 (1999)

The page opened, but all elements were distorted and the BHL-E logo 
on grey background. The moving images were fixed. It was possible to 
use the search function. I inserted "Beschrijving" and clicked 
return, which was immediately understood. A new page appeared 
(also this one with much distorted image, box and text elements) and 
said that the query yielded no results. In this new page ("advanced 
search page") it was not possible to use the search function.

It is not possible to work with the portal in this browser.

Francisco

University of Goettingen, Germany
www.animalbase.org

**Comment by fwelter** [comment]
Tried some other computers in the institute: 

Mozilla Firefox 2.0 (2006). 

This was more or less the same version as that of my notebook, but 
with a very different (bigger) screen. The design of the portal was 
basically the same, all elements of boxes, texts and images were 
totally distorted, and it was not possible to insert text in the 
search box (because the moving books were "flying" above the search 
box).

Internet Explorer 6.0 (2004)

Elements were distorted also here, BHL-E logo on grey background 
(not brown this time). It was possible to insert text in the search 
box. I searched for "Beschrijving" and obtained one result (the 
correct result). In the "advanced search page" that appeared it was 
not possible to insert text in the seach box because the 
image, text and box elements were so distorted that they covered the 
search box.

Internet Explorer 8.0 (2009)

Elements were not distorted, the presentation was probably correct, 
as far as I could see.

I types "beschrijving" and obtained one result, the correct one. 
In the advanced search page that appeared I typed in "remarques" and 
pressed return one time - this was understood by the program and the 
query started. This was a difference to Mozilla Firefox where 
pressing "return" had the effect that "OK" was added to the search 
term.
I obtained no result. Instead of a text "your query did not yield 
results" only white space appeared. Another difference to Mozilla 
Firefox where such a text was displayed.
Then I clicked on the "Reset" button. This had the effect that the 
page was reloaded and suddenly the text "your query did not yield 
results" appeared.

I typed in "herzen" and pressed return. Same situation as with 
"remarques": a white space with a beautiful grey fossil fish.
Then " clicked on the Reset button and the page was reloaded - and 
suddenly one result was shown ("Im Herzen von Afrika: ..."). 

This means that the query is not understood when return is pressed.

The language information was kept between main page and 
advanced search page (French site -> French site), but it was 
lost when I switched to the view record page (French -> German).

So it was possible to work with the portal at this IE 8 browser, but 
it seemed that the bugs differed slightly from the Mozilla Firefox 
browser.

So I have tested basic functions at 8 browsers and 5 different 
computers and screens, most were institute computers which are 
currently in usage. In 5 of the 8 browsers the portal could not be 
used because the design elements were totally distorted and the most 
basic functions did not work. At the other 3 browsers the portal 
worked, with some minor bugs.

This is a scientific institute at a public university in Germany. The 
institute does not have the money to buy new computers every two 
years. Updates for browsers cannot be installed easily because only 
administrators are allowed to do this, and due to lack of personal 
resources this is rarely done. Also, updates usually require more 
memory space, which immediately runs into the funding problem. The 
institute is financially very badly equipped.

The BHL-US portal and the GRIB portal work perfectly at 7 of the 8 
browsers, or in other words, at every browser from 2003 onwards.

University of Goettingen, Germany
www.animalbase.org
