### ISSUE TITLE
4.2.2 - Save search results

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#125]
Save and display search history (only registered user)

**Comment by janahoffmann** [comment]
Ready for testing with addtional info for testers on how to do it.
First press 'save query' after performing a search and then check 'saved queries'

works fine and is a very helpful tool. 
This is a function only for registered users.

**Comment by JiriFrank** [comment]
Testing of feature 4.2.2 - Save search results

Feature description from the Catalogue of user requirements:

Save and display search history (only registered user)

Testers:
@AntonioGVH
@fwelter
@heimor
@janahoffmann
@JFTester
@JiriFrank
@LarissaS

**Comment by JiriFrank** [comment]
Testing of feature 4.2.2 - Save search results

Feature description from the Catalogue of user requirements:

Save and display search history (only registered user)

Testers:
@fwelter

**Comment by AntonioGVH** [comment]
This option seems to work properly

A

Quoting JiriFrank:

**Comment by fwelter** [comment]
4.2.2     save search results

I tried to test something by clicking on the link "Manage saved
queries" 

The following was displayed: 

flora   delete
dc_date__facet:[1910 TO 1930]   delete
african crabs   delete
a\*  delete
book    delete
- clicking on "delete" next to "flora" had the effect that the page
  was reloaded and the flora line was removed.
- clicking on "african crabs" (I opened the link in a new Tab) gave
  the following result:
  1. NCB Naturalis (172)
  2. Oberösterreichisches Landesmuseum (15)
  3. Royal Museum for Central Africa (4)
- the sorting was the last one that I had in my immediately preceding
  research (Title arrow down)
- when I inserted another query with a different search term, changed
  the sorting there (Creator arrow up) and then clicked on the same
  "african crabs" saved query link, then I got the same african crab
  results 
  1. NCB Naturalis (172)
  2. Oberösterreichisches Landesmuseum (15)
  3. Royal Museum for Central Africa (4)
- but now they were sorted (Creator arrow up)
- this means that the program had not saved the sorting of the results
  list in the query

mantides
- gave 3 results
- I clicked on the button "Save query"
- the button turned grey "query saved"
- reloading the "Manage saved queries" page had the effect that
  "mantides     delete" was displayed there, sorted below the others
- clicking on the "mantides" link (I opened it in a new Tab) listed
  the correct 3 results

musee
- results:
  1. NCB Naturalis (25)
  2. Royal Museum for Central Africa (20)
  3. Oberösterreichisches Landesmuseum (7)
- browser headline showed this:
  http://bhl-portal-dev.nhm.ac.uk/?q=advanced_search_view/{!lucene}musee
- I clicked on the button "Save query"
- the button turned grey "query saved"
- reloading the "Manage saved queries" page had the effect that "musee
  delete" was displayed there, sorted below the others
- clicking on the "musee" link with right mouse function "save link"
  produced this link:
  http://bhl-portal-dev.nhm.ac.uk/?q=advanced_search_view/{!lucene}musee
- clicking on the "musee" link (I opened it in a new Tab) listed the
  correct results

saving search results worked fine. the sorting parameters were not
saved. a link with the search query text is saved and provided with a
stable URL link to the saved query. It practically means that the
query is repeated. 

we could not test this but the method as I understood it would produce
a new query and if the content or the search function will have
changed since the last time, the search will be performed under the
new conditions and not produce the same results.

---
- when there were many results the page took long time to load in and
  blocked the mouse of my computer. this was because all the thumbnails
  needed to load in. it seems that also those thumbnails needed to load
  in that were not displayed on the screen. if I had installed to
  display 25 results in the hitlist and there were 1500 results the
  thumnails for all 1500 results loaded in. after that the computer was
  largely blocked and very slow, I tried to close the window as soon as
  possible and I also tried not to select search terms that produced so
  many results.
- nowhere was displayed how many titles were found in total, usually I
  listed the numbers given for data providers. only maximum 5 data
  providers were shown, I discovered this bug only very late in the
  testing process.
- it is also possible that Date, Language and the other facet lists
  had also restrictions for 5 lines to be shown only. I realised this
  only after 2 weeks testing.
- the big problem was that too many results were shown, mainly for two
  reasons:

1 - the result lists generally displayed titles where none of the
words were contained in the title, author or year, but in the text of
the abstract and notes of the item page. 

2 - single journal volumes were displayed for serial runs, they
blocked all intelligent search attempts and spammed the results list
with over and over the same journal title. 
- it was generally very difficult (better say, practically impossible)
  to test for completeness of results. restricting search for (1) only
  in title, author and date and (2) exclude journal metadata of single
  journal volume item pages (and instead create one single journal title
  hit) would probably solve the problems.

Francisco

---

F. Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536, Fax +49 551 395579
http://www.gwdg.de/~fwelter
http://www.animalbase.org

**Comment by JiriFrank** [comment]
This function is implemented and working properly.

**Comment by chris-sleep** [comment]
Save search is not currently active/enabled in the current portal.  The function hook needs to be identified and linked to the current save search button.

**Comment by akohlbecker** [comment]
the "ait" implementation of save search is found in https://github.com/bhle/bhle/blob/master/portal/drupal/www/sites/all/modules/ait/advanced_search/advanced_search.module#L1124 at this line you will find the function:

```
 function advanced_search_panel_save_query($form, &$form_state) {

    $saved_queries = metadata_variable_get_user('advanced_search_saved_queries');
    $saved_queries[] = $form_state['values']['query_string'];
    metadata_variable_set_user('advanced_search_saved_queries',$saved_queries);

    $form_state['storage']['query_saved'] = true;
    $form_state['rebuild'] = TRUE;
  }
```

**Comment by lobajuluwa** [comment]
Dependent on getting tagging options in line.

**Comment by akohlbecker** [comment]
@JiriFrank @chris-sleep what should happen when clicking the save search button?

For example: The user enters new search terms and clicks "Save Query", will the query be executed or will it only be saved?

**Comment by akohlbecker** [comment]
@JiriFrank @chris-sleep  fixed
