### ISSUE TITLE
4.2.3 - Save results to favourites (URL’s)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#126]
Provide link for saving search results in favorites (of browser), shorter url's?

**Comment by janahoffmann** [comment]
I think this requires an up and running archival system and is not implemented yet. We don't have bhl-europe urls yet. 

However, another way is to save the query and add the query link to favourites in the browser, which work well if logged in.
That's a very good tool and needs to be integrated in the help/tutorial for the BHl Europe portal. This function will only be available for logged in users, right?

Copy/ paste of the url of the found item (in metadata view) works fine. 
So, I think this is sufficient the way it works. The only thing missing is the actual URL of the object, which refers to my first comment above.

**Comment by JiriFrank** [comment]
Open for testing.

**Comment by JiriFrank** [comment]
Testing of feature 4.2.3 - Save results to favourites (URL’s)

Feature description from the Catalogue of user requirements:

Provide link for saving search results in favorites (of browser), shorter url's?

Testers:
@AntonioGVH
@fwelter
@heimor
@janahoffmann
@JFTester
@JiriFrank
@LarissaS

**Comment by JiriFrank** [comment]
Testing of feature 4.2.3 - Save results to favourites (URL’s)

Feature description from the Catalogue of user requirements:

Provide link for saving search results in favorites (of browser), shorter url's?

Testers:
@fwelter

**Comment by AntonioGVH** [comment]
Do not know how to do this.

However, it seems that the system does not go back at the beggining after saving a list. I asked for 'Ramos' after saving some records and got the screen included (even after clicking 'inicio').

A

Quoting JiriFrank:

**Comment by fwelter** [comment]
4.2.3     stable URLs

simple search  mantides
- 3 results

http://bhl-portal-dev.nhm.ac.uk/?q=node/13071
http://bhl-portal-dev.nhm.ac.uk/?q=node/18685
http://bhl-portal-dev.nhm.ac.uk/?q=node/13543
- each node has an obviously individual ID number

Advanced search 2

dc_contributor:n\* AND europeana_dataProvider__facet:"Consejo Superior
de Investigaciones Científicas"
- gave 5 results, all from Consejo Superior de Investigaciones
  Científicas

http://bhl-portal-dev.nhm.ac.uk/?q=node/12917
http://bhl-portal-dev.nhm.ac.uk/?q=node/12918
http://bhl-portal-dev.nhm.ac.uk/?q=node/12919
http://bhl-portal-dev.nhm.ac.uk/?q=node/12922
http://bhl-portal-dev.nhm.ac.uk/?q=node/12923
- it is almost obvious that the ID number was donated in the order of
  the date of acquisition/upload. All Consejo Superior de
  Investigaciones Científicas data were presumably uploaded at the same
  time.
- I opened this page in a new window:
  http://bhl-portal-dev.nhm.ac.uk/?q=node/12919
- this dispayed the item page (in BHL terms) with metadata information
  and a link to a digitised copy that was not active.
- I found this information displayed:

intern bhle id for metadata files: 
CSIC/8400070100OC
- in the metadata was shown the following information:;

Identification  

84-00-07010-0 (O.C.)
84-00-07011-9 (V.0)
CSIC000151989
e4817cc1-580f-478b-b745-bb958fc64733
- this means that the internal ID number (the node number shown in the
  browser URL headline) was not displayed on the metadata page, and that
  the numer given at "intern bhle id for metadata files"
  (CSIC/8400070100OC) was not this number (this number should have been
  12919)

the system with the node numbers looks good and is acceptable. The ID
number is at the end of the URL, this is easy to recognise, and
something that can be compared with the stable URLs BHL is providing,
for example http://www.biodiversitylibrary.org/item/107353

the ID number in the URL is not unnecessarily long. looks good. of
course, we cannot test if the page will be stable in 20 years, but the
conditions seem to be good

---
- when there were many results the page took long time to load in and
  blocked the mouse of my computer. this was because all the thumbnails
  needed to load in. it seems that also those thumbnails needed to load
  in that were not displayed on the screen. if I had installed to
  display 25 results in the hitlist and there were 1500 results the
  thumnails for all 1500 results loaded in. after that the computer was
  largely blocked and very slow, I tried to close the window as soon as
  possible and I also tried not to select search terms that produced so
  many results.
- nowhere was displayed how many titles were found in total, usually I
  listed the numbers given for data providers. only maximum 5 data
  providers were shown, I discovered this bug only very late in the
  testing process.
- it is also possible that Date, Language and the other facet lists
  had also restrictions for 5 lines to be shown only. I realised this
  only after 2 weeks testing.
- the big problem was that too many results were shown, mainly for two
  reasons:

1 - the result lists generally displayed titles where none of the
words were contained in the title, author or year, but in the text of
the abstract and notes of the item page. 

2 - single journal volumes were displayed for serial runs, they
blocked all intelligent search attempts and spammed the results list
with over and over the same journal title. 
- it was generally very difficult (better say, practically impossible)
  to test for completeness of results. restricting search for (1) only
  in title, author and date and (2) exclude journal metadata of single
  journal volume item pages (and instead create one single journal title
  hit) would probably solve the problems.

Francisco

---

F. Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536, Fax +49 551 395579
http://www.gwdg.de/~fwelter
http://www.animalbase.org

**Comment by lobajuluwa** [comment]
Update from Portal Review Workshop - nothing ingested in the archive therefore may not be done – ready for November sub release? assigned to Chris Sleep.
