### ISSUE TITLE
File Submission Guidelines

### ISSUE THREAD

**Issue by lobajuluwa** [gbhl/bhl-europe#145]
Tasks to be completed:-
- Provide recommendation : Article level content: how to provide pages that do not belong to articles but to the volume?
- Documentation for OLEF

**Comment by melitabirthaelmer** [comment]
<i>Issue:</i>
"However, there are some questions regarding our content. This addresses the "completeness" of the volumes. As you may remember the granularity level we used is the articles themselves. That means that a volume will not be "complete" (in terms of pages) because of the missing blank pages, title pages, front cover etc. "

<i>Questions:</i>
- Where should these pages be uploaded (e.g. which directory is preferred), so you can work with them and process them at best automatically?
- How will the pre-ingest/portal/archive deal with the content on article level? 
- Will the portal display the several articles individually or merge articles together to one volume?

<i>Example:</i>
HNHM provides content on article level in the way we agreed for the file submission guidelines. You can have for e.g. a look at this directory: http://bhl-celsus.nhm.ac.uk/uploads/HNHM/Fragm_min_pal/Fragm_min_pal_1996_Vol_18/

This directory contains the articles for  “Fragmenta mineralogical et paleontological Vol. 18” in subfolders for each article. Each subfolder contains the article and the metadata for the article.

<i>Summing up:</i>
- Where should they upload for e.g. the front page or the table of contents, all these pages which do not belong to the articles?
- What is the best way for you to manage these pages during the ingest?

<b>Recommendation is needed as soon as possible in order to be able to advice our content providers concerned and secure that they can move on uploading content to the NHM server.</b>

**Comment by sprogerb** [comment]
Best practice guidance was requested from BHL-US by Melita (WP2-Lead).

**Comment by lobajuluwa** [comment]
Hi Bernd,

I think you should keep this issue open. If it was requested by Melita then all you need to do is reassign the issue.

Thanks.

**Comment by lobajuluwa** [comment]
Melita's comments:
Documentation for OLEF is needed:-

We have something like that until now – Technical documentation : http://www.bhl-europe.eu/bhl-schema/v0.3/
But need something more user friendly like the Europeana document:
http://version1.europeana.eu/c/document_library/get_file?uuid=77376831-67cf-4cff-a7a2-7718388eec1d&groupId=10128
During one of the PMG calls we agreed to do it and start the work during the Helsinki meeting. Wolfgang needs an official decision from WP3 to do this work.
Update from tech call (9th Jan): during Helsinki meeting we will need to have a separate meeting to discuss how to produce a 2nd doc similar to ESE version. (GH)
@melitabirthaelmer 
@wkollernhm 
@heimor

**Comment by wkollernhm** [comment]
@lobajuluwa I think we can close this issue and open a new one for creating the OLEF documentation as a task for the end of the project.
