### ISSUE TITLE
Clean issue tracker labels

### ISSUE THREAD

**Issue by sprogerb** [gbhl/bhl-europe#161]
Issue tracker must only contain the following issue types:
- bug
- feature request (enhancment)

Bugs shall be classified according to severity level and priority. 

Severity levels:
- minor defect
- major defect
- blocking (critical) defect

Priority levels:
- low
- high

**Comment by lobajuluwa** [comment]
Hi Bernd,

The GitHub Issue tracker can be used as a generalized tool for tracking different kinds of activities and hence you can classify issues into many different types i.e Bug, Enhancement, Feature, tasks, Patch etc.
We agreed along with the Testing Manager that it would be best to use one platform – GitHub as the Issue Tracker and for the Testing process and therefore Lee & I originally thought it would be best to keep the labelling system “Simple” for the various types of issues.  Hence the following labels have been agreed as: - 

1))  Types of Issues that developers will be dealing with:-

Issues: Bug, Feature, Feature Request, Project Tasks

2) The Priority to be determined by the level of Importance:- 

Priority: Critical, Normal, Minor.

3) Furthermore, Graham has assigned additional labels in order to provide further classification and clarity for developers which includes:- Web Services, GRIB.

4)Finally, even though we have a filter for milestones it was also decided to include labels for specific dates i.e. Aug 2011, Nov 2011, March 2012 etc – for the regular releases that we have planned.

Other miscellaneous labels include: - Documentation & Unresolved.

Please let me know what your thoughts & comments are regarding above i.e do you think the main Issues will become obscured by the various labels we presently have?

Kind Regards,

Lola

**Comment by lobajuluwa** [comment]
Guidelines for using Issue Tracker is available on the Wiki:
https://bhl.wikispaces.com/GitHub+Issue+Tracker
