### ISSUE TITLE
1.1.8 - Search in all or specific main search categories (Simple Search)

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#168]
This functionality needs also to be implemented as Simple Search functionality, not only Advanced Search. In simple search it needs to be restricted to the identified main search categories (metadata fields): title, author, year and maybe journal title.
It should have the look and feel (simpler) of advanced search but has to be restricted to the main search categories, see above. 

@janahoffmann
feature #40

**Comment by JiriFrank** [comment]
I will provide the developers with the graphic draft, where and how to implement this function on the front page.

Link to the first draft on Wiki
https://bhl.wikispaces.com/file/view/Simple_search_criteria.png

**Comment by JiriFrank** [comment]
In this option the advance search 1 will be not needed. Delete the Advance Search 1.

**Comment by JiriFrank** [comment]
Bug - 1.1.8 - Search in all or specific main search categories (Simple Search)

COR number: it is bug related to feature 1.1.8
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search

Bug description:

This functionality needs also to be implemented as Simple Search functionality, not only Advanced Search. In simple search it needs to be restricted to the identified main search categories (metadata fields): title, author, year and maybe journal title.

It should have the look and feel (simpler) of advanced search but has to be restricted to the main search categories, see above.

These bugs are results from 1st testing phase. Please read the description and made a comment if this bug is solve according to status of portal or not.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
Bug - 1.1.8 - Search in all or specific main search categories (Simple Search)

COR number: it is bug related to feature 1.1.8
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search

Bug description:

This functionality needs also to be implemented as Simple Search functionality, not only Advanced Search. In simple search it needs to be restricted to the identified main search categories (metadata fields): title, author, year and maybe journal title.

It should have the look and feel (simpler) of advanced search but has to be restricted to the main search categories, see above.

These bugs are results from 1st testing phase. Please read the description and made a comment if this bug is solve according to status of portal or not.

@AntonioGVH
@fwelter
@LarissaS

**Comment by LarissaS** [comment]
It looks ok, but by default all fields are switched except scientific name, is it by purpose?

-----Original Message-----

**Comment by LarissaS** [comment]
Just saw that scientific name is not always switched out, then I just start from start page all fields are switched on, but if I go back from the results page via the button simple search - the scientific name is out. Small bug?

-----Original Message-----

**Comment by RalfH** [comment]
No problem as regards that.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 16:05
An: Hand, Ralf
Betreff: Re: [bhle] 1.1.8 - Search in all or specific main search categories (Simple Search) (#168)

Bug - 1.1.8 - Search in all or specific main search categories (Simple Search)

COR number: it is bug related to feature 1.1.8
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search

Bug description:

This functionality needs also to be implemented as Simple Search functionality, not only Advanced Search. In simple search it needs to be restricted to the identified main search categories (metadata fields): title, author, year and maybe journal title.

It should have the look and feel (simpler) of advanced search but has to be restricted to the main search categories, see above.

These bugs are results from 1st testing phase. Please read the description and made a comment if this bug is solve according to status of portal or not.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment]
Have done simple searches for 1. author only 2. title word only 3. year only 4. scientific name only (example used Betula pendula) seems to work fine in all cases.

**Comment by HenningScholz** [comment]
This bug seems to be gone.

---

Dr. Henning Scholz 
Museum für Naturkunde | Leibniz Institute for Research on Evolution and Biodiversity at the Humboldt University Berlin
Invalidenstraße 43 | D-10115 Berlin | Germany 
Tel.: +49-30-2093-8864 | Fax: +49-30-2093-8868 
Email: henning.scholz@mfn-berlin.de
http://www.naturkundemuseum-berlin.de/ / http://www.bivalve.de 
http://www.bhl-europe.eu / http://www.biodiversitylibrary.org/
BHL-Europe in Europeana:  bit.ly/BHLE-Europeana

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 16:05
An: Scholz, Henning
Betreff: Re: [bhle] 1.1.8 - Search in all or specific main search categories (Simple Search) (#168)

Bug - 1.1.8 - Search in all or specific main search categories (Simple Search)

COR number: it is bug related to feature 1.1.8
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search

Bug description:

This functionality needs also to be implemented as Simple Search functionality, not only Advanced Search. In simple search it needs to be restricted to the identified main search categories (metadata fields): title, author, year and maybe journal title.

It should have the look and feel (simpler) of advanced search but has to be restricted to the main search categories, see above.

These bugs are results from 1st testing phase. Please read the description and made a comment if this bug is solve according to status of portal or not.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AntonioGVH** [comment]
Title and author seems to work properly from simple search.

Quoting JiriFrank:

**Comment by JiriFrank** [comment]
Bug is fixed.

@LarissaS 
The Scientific name is not check as default, because is using different web-services which are not common as the first three main search metadata fields. The user can choose if he want to use it or not.
