### ISSUE TITLE
1.2.5 - Combined search in different metadata fields 

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#171]
Jiri
The date search only gives you results from LANDOE because the books have the year in the title.
If the date search is in the first field you will always get the results from dates (from LANDOE).
Other categories combinations are working independent on order.

Jana
Search for dates doesn't work correctly in advanced search (2).
Search for dates is only performed on LANDOE collection because the year is included automatically in the title (which is not supposed to be the case!, check metadata). In advanced search no other collection than Landoe can be found by searching for dates.
In simple search, search for dates works (because search is performed on all metadata fields).

Feature #48

**Comment by janahoffmann** [comment]
@Melitabirthaelmer
Could you please check the respective metadata of LANDOE collection.

**Comment by melitabirthaelmer** [comment]
This is the current situation using an example:

BHL-Europe portal: http://bhl-portal-dev.nhm.ac.uk/?q=node/13019 
Used metadata for this content: http://81.10.192.123:8082/oai/oai2.php?verb=GetRecord&identifier=oai:biologiezentrum.at:125&metadataPrefix=ese

<b>Please note: this is metadata that was used for the Europeana ingest in April 2011 as we had no portal & no ingest tool. Therefore LANDOE prepared their metadata using the ESE schema as requested by AIT</b>
LANDOE is currently working on preparing their metadata using the OLEF schema over OAI-PMH and this should be used for the BHL-Europe portal.

As far as I understand this is the current problem: 
Title: Linzer biologische Beiträge (LBB) 30_1 (1998)

The date in brackets (1998) derives from the date field.
This can be left out within the title.
LANDOE does not include the date in brackets within their title field within their own data base. 

Background why the date is at the end of the title field for Europeana: 
This was necessary for the first ingest to Europeana before April 2010. As far as I understood the title from some different issues are exactly the same and in order to identify the issue the field date has been added to the title in brackets.

Suggestion: LANDOE leaves the date at the end of the title field out and after the ingest to the portal we can have a look if the individual issues with the same title cause a problem. Then we decide what to to with the individual issues and it might be that those need to be re-ingested.

<b>What is the preferred solution from your side? </b>

**Comment by janahoffmann** [comment]
Sounds like a good solution!!!

Museum für Naturkunde
Leibniz Institute for Research on Evolution and Biodiversity at the Humboldt University Berlin

Jana Hoffmann 
BHL-Europe - project assistant  

http://www.bhl-europe.eu/
Invalidenstraße 43 
10115 Berlin 
Germany 

phone: +49 (0)30 2093-8650
fax: +49 (0)30 2093-8565 
email: jana.hoffmann@mfn-berlin.de 
website: http://www.naturkundemuseum-berlin.de 

-----Ursprüngliche Nachricht-----
Von: melitabirthaelmer [mailto:reply@reply.github.com] 
Gesendet: Mittwoch, 17. August 2011 15:47
An: Hoffmann, Jana
Betreff: Re: [bhle] 1.2.5 - Combined search in different categories (#171)

This is the current situation using an example:

BHL-Europe portal: http://bhl-portal-dev.nhm.ac.uk/?q=node/13019 
Used metadata for this content: http://81.10.192.123:8082/oai/oai2.php?verb=GetRecord&identifier=oai:biologiezentrum.at:125&metadataPrefix=ese

<b>Please note: this is metadata that was used for the Europeana ingest in April 2011 as we had no portal & no ingest tool. Therefore LANDOE prepared their metadata using the ESE schema as requested by AIT</b>
LANDOE is currently working on preparing their metadata using the OLEF schema over OAI-PMH and this should be used for the BHL-Europe portal.

As far as I understand this is the current problem: 
Title: Linzer biologische Beiträge (LBB) 30_1 (1998)

The date in brackets (1998) derives from the date field.
This can be left out within the title.
LANDOE does not include the date in brackets within their title field within their own data base. 

Background why the date is at the end of the title field for Europeana: 
This was necessary for the first ingest to Europeana before April 2010. As far as I understood the title from some different issues are exactly the same and in order to identify the issue the field date has been added to the title in brackets.

Suggestion: LANDOE leaves the date at the end of the title field out and after the ingest to the portal we can have a look if the individual issues with the same title cause a problem. Then we decide what to to with the individual issues and it might be that those need to be re-ingested.

<b>What is the preferred solution from your side? </b>

##

**Comment by JiriFrank** [comment]
Ready for testing.

**Comment by JiriFrank** [comment]
1.2.5 - Combined search in different metadata fields (Advanced Search)

COR number: 1.2.5
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Simple search

Description:

Select/ combine different metadata fields for search; e.g. search for author and year, or search for taxon name in a certain time interval.

For more search fields in advanced search use the add field option.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
1.2.5 - Combined search in different metadata fields (Advanced Search)

COR number: 1.2.5
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Simple search

Description:

Select/ combine different metadata fields for search; e.g. search for author and year, or search for taxon name in a certain time interval.

For more search fields in advanced search use the add field option.

---

@GregKenicer
@GeoffHarper
@KasiaGoral
@MartinaMetzger
@DanielFisher
@NeilWoodcock
@SaraPerzley
@SaraCarlton
@HannaKoivula
@PaiviLipsanen

**Comment by JiriFrank** [comment]
1.2.5 - Combined search in different metadata fields (Advanced Search)

COR number: 1.2.5
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Simple search

Description:

Select/ combine different metadata fields for search; e.g. search for author and year, or search for taxon name in a certain time interval.

For more search fields in advanced search use the add field option.

---

@PaiviJaakkola
@SiniKarki
@TiinaOnttonen

**Comment by LarissaS** [comment]
Works fine

-----Original Message-----

**Comment by HenningScholz** [comment]
Seems to work fine.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Do 12.04.2012 19:13
An: Scholz, Henning
Betreff: Re: [bhle] 1.2.5 - Combined search in different metadata fields (#171)

1.2.5 - Combined search in different metadata fields (Advanced Search)

COR number: 1.2.5
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Simple search

Description:

Select/ combine different metadata fields for search; e.g. search for author and year, or search for taxon name in a certain time interval.

For more search fields in advanced search use the add field option.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamtestrbge** [comment]
Works when using author + year; title word + author; language + author.  Think that the use notes should have a text box that says that when doing a combination search the box in each search field needs to be ticked.   

Tried some searches using Author and part of Place, eg Aigret AND Namur, this did not retrieve any results.  But perhaps this is not how that function should be used.

**Comment by RalfH** [comment]
It works but as in the first testing phase I have problems as regards the ranges of years. None of the recommended methods work (1800-1900, 1800 TO 1900 ...).

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Donnerstag, 12. April 2012 19:14
An: Hand, Ralf
Betreff: Re: [bhle] 1.2.5 - Combined search in different metadata fields (#171)

1.2.5 - Combined search in different metadata fields (Advanced Search)

COR number: 1.2.5
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Simple search

Description:

Select/ combine different metadata fields for search; e.g. search for author and year, or search for taxon name in a certain time interval.

For more search fields in advanced search use the add field option.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by SiniKarki** [comment]
Seems to work.
How to use OR NOT box, option not quite clear. 
"Place" search does not seem to work.

Searching ' flore OR flora '  In title: 3 results, In scientific name: 0 results, In title and scientific name: 4 results including:

Květena českého cenomanu: BibTex : keywords="fossil flora",

**Comment by AntonioGVH** [comment]
Strange behavior of the portal.

I did a query as shown in screen shot First and get the error message shown in screen shot Second

-----Mensaje original-----
De: JiriFrank [mailto:reply@reply.github.com] 
Enviado el: jueves, 12 de abril de 2012 19:14
Para: AntonioGVH
Asunto: Re: [bhle] 1.2.5 - Combined search in different metadata fields (#171)

1.2.5 - Combined search in different metadata fields (Advanced Search)

COR number: 1.2.5
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Simple search

Description:

Select/ combine different metadata fields for search; e.g. search for author and year, or search for taxon name in a certain time interval.

For more search fields in advanced search use the add field option.

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
Is the place category valid? Are all categories in advanced search block active or functional?
Will be the combined categories from simple search hidden in Advanced search block?
@akohlbecker 
@chris-sleep
