### ISSUE TITLE
1.3.1 - Browse by Title

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#181]
Browse by “B” results starts with 8 items which doesn’t start by “B”.
Browse by “C” – 23 items.
Browse by “D” – 18 items.
…
Browse by “N” - more than 150 items. The Browse option is evidently looking for term starting by “N” in whole metadata and not just in the title. Is it metadata problem or bug in browse option?

Browse by “S” – more than 300 items. There is another problem with metadata in this case. 98 titles starts with square bracket, which is probably caused by defect in metadata and probably also in OCR. 

Feature #57

**Comment by janahoffmann** [comment]
@melitabirthaelmer
Do you have an idea what could cause the "S" or "N" problem?

**Comment by melitabirthaelmer** [comment]
It is difficult to test this, as reduction of the retrieved items to an individual "Data Provider" doesnt't work using the faceted navigation.

Here is an example I had a look at (I used one from our CPs who uploaded the metadata file and the scans to the NHM server in order to be able to compare the original metadata with the processed metadata displayed in the portal):
- Used search: Browse by "S" -> go to page 3
- This is what is displayed:
  http://bhl-portal-dev.nhm.ac.uk/?q=advanced_search_view/{!lucene%20%20q.op%3DOR}dc_title__facet%3AS*%20dc_title__facet%3As*&page=2
- Scroll down to "Memoranda Societatis pro fauna et flora Fennica" (the very long one) from Helsingin yliopisto
- Click on that and you get this: http://bhl-portal-dev.nhm.ac.uk/?q=node/21970
- The corresponding metadata file is this one on the NHM sever: http://bhl-celsus.nhm.ac.uk/uploads/UHViikki/FI-Hb/FI-Hb_301519_Memoranda_Societatis/301519_01_1924-1925/301519_01-1924-1925_articles_metadata.mrc    

This error might be caused because of the way the metadata is processed for the portal.

<b>Please note again: The displayed metadata in the current portal is following the ESE schema. Judgement on such errors doesn't make really sense if we do not display metadata using the OLEF schema.</b>

Explanation for the error might be:
The original metadata format is MARC and in this case it contains even information on article level.
All fields starting with 245 (= title field) are one after another added with a line break to the BHL-Europe portal title field. The title of the whole item is marked with <i>245  00$a</i> and the title of an article is marked with <i>245  10$a</i>. Additionally, for the articles there is a field <i>773</i> denoted which gives information on the host item and the exact location of the component part within the bibliographic item.
However in the BHL-Europe portal title field, only the first row should be the title of this item. The successive rows are the titles from the articles within the item and that way of processing the original fields might cause the problem.

Here is an extract from the metadata file.
<i><snip>
=LDR  00763cas a22003014a 4500
=001  1389093
=005  20081230105153.0
=007  tu
=008  950127c19279999fi\a||p||||||||||b0mul||
=022  0\$a0373-6873$z0375-7641$2a
=035  \$97504
=041  0\$amul
=080  \$a58
=080  \$a59
=245  00$aMemoranda Societatis pro fauna et flora Fennica.
=260  \$aHelsinki :$bSocietas pro fauna et flora Fennica.
=300  \$c25 cm.
=596  \$aViik$b1994-
=597  \$aHYjulki
=597  \$aSFFF$b1965-1995
=597  \$aMet
=597  \$aHYjulki$b1993-
=597  \$aHYjulki$b1998-
=710  2\$aSocietas pro fauna et flora Fennica.
=850  \$aFI-HYjulki
=850  \$aFI-Viik
=905  \$aa
=995  \$aBiot$aHYjulki$aHYjulki$aSFFF$aHYjulki$aViik
<i>
=LDR  00498cab a22001574ar4500
=001  138021
=005  20081217004434.0
=007  tu
=008  970128s1925\\fi|||||||||||||||0swe||
=035  \$a138021
=041  0\$aswe
=100  1\$aKrogerus, Rolf.
=245  10$aTvå för Finland nya skalbaggar från lk.
=773  0\$7nnas$w03736873$tMemoranda Societatis pro fauna et flora Fennica. -$dHelsinki : Societatis pro fauna et flora Fennica. -$x0373-6873. -$g1 (1924-1925), s. 6
=850  \$aFI-Viik
=995  \$aBiot$aViik
<i>
=LDR  00554cab a22001574ar4500
=001  138024
=005  20081217004434.0
=007  tu
=008  970128s1925\\fi|||||||||||||||0ger||
=035  \$a138024
=041  0\$ager
=100  1\$aLuther, Alex.
=245  10$aU¨ber das Vorkommen der Bryozoe Victorella pavida S. Kent im Finnischen Meerbusen bei Tvärminne.
=773  0\$7nnas$w03736873$tMemoranda Societatis pro fauna et flora Fennica. -$dHelsinki : Societatis pro fauna et flora Fennica. -$x0373-6873. -$g1 (1924-1925), s. 7-9
=850  \$aFI-Viik
=995  \$aBiot$aViik
<snip></i>

<b>Once again we need to see how this is handled within the OLEF schema to give any useful feedback either to our CPs for future uploads or to developers/ingest team how to handle this.</b>

**Comment by JiriFrank** [comment]
Same as #182

**Comment by akohlbecker** [comment]
@JiriFrank i think we can close this ticket now (#182 is also closed)
