### ISSUE TITLE
1.3.1 - Browse by Year

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#183]
The results are just from LANDOE content provider because the books have the year also in title and from UBER because of their specific date format. Related bug #171

For example by Browse by Year 1990 - Matches for: dc_date__facet:[1990 TO 2010] first items are from UBER and are sorted by wrong year (for example 1900) because of the different format of metadata.

Feature #57

**Comment by janahoffmann** [comment]
@melitabirthaelmer 
Could you please check the UBER date format and find out why they display it in this style 1900-01-01? This might confuse the users and interfer with the search functionalities.

**Comment by melitabirthaelmer** [comment]
For me it looks like it matches the UBER items because of this additional comment in the date field "20. Jahrhundert/Erste Dekade des 20. Jahrhunderts". 20 is marked yellow when I search an the search seams to retrieve everthing with 20XX.

This is the search 
(Matches for:dc_date_facet:[1990 TO 2010] AND europeana_dataProvider_facet:"UB der Humboldt-Universität, Zweigbibliothek Museum für Naturkunde"): 
http://bhl-portal-dev.nhm.ac.uk/?q=advanced_search_view/{!lucene++q.op%3DOR}dc_date__facet%3A[1990+TO+2010]+AND+europeana_dataProvider__facet%3A%22UB+der+Humboldt-Universit%C3%A4t%2C+Zweigbibliothek+Museum+f%C3%BCr+Naturkunde%22

However I have no idea how the additional comment can be in the protal date field and where it comes from.
Having a look at the original metadata for the first item (http://bhl-portal-dev.nhm.ac.uk/?q=node/21882), I cannot find the comment within the original metadata.
Here is the original metadata from UBER: 
http://edoc.hu-berlin.de/OAI-2.0?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:HUBerlin.de:26502

**Comment by akohlbecker** [comment]
@karlos007 @wkollernhm  searching for a range of years is working now see  87b3b3fbb71d6943c8090d55fa506fa712ae54e9
