### ISSUE TITLE
4.2.1 - Change individual search setting

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#184]
Table view is not working properly. The metadata extend from the frames, creating a mess.

The table need to by styled and redesigned also with the new template. There are several different table views and also tables in tables in several cases. It is more or less a design function.

For more details see comments in feature #124

**Comment by JiriFrank** [comment]
4.2.1 - Change individual search setting

COR number: it is bug related to feature 4.2.1 – the description in COR need to be change, because there is not necessary to be registered user for use this feature.

Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Bug description:

Table view is not working properly. The metadata extend from the frames, creating a mess.
The table need to by styled and redesigned also with the new template. There are several different table views and also tables in tables in several cases. It is more or less a design function.

This bug is a result from 1st testing phase. Please read the description and write a comment if this bug is solved according to status of portal or not.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
4.2.1 - Change individual search setting

COR number: it is bug related to feature 4.2.1 – the description in COR need to be change, because there is not necessary to be registered user for use this feature.

Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Bug description:

Table view is not working properly. The metadata extend from the frames, creating a mess.
The table need to by styled and redesigned also with the new template. There are several different table views and also tables in tables in several cases. It is more or less a design function.

This bug is a result from 1st testing phase. Please read the description and write a comment if this bug is solved according to status of portal or not.

@AntonioGVH
@fwelter
@LarissaS

**Comment by RalfH** [comment]
During 4 days of testing no irregularities seen. Apart from the cut lines mentioned earlier under another COR number.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 16:29
An: Hand, Ralf
Betreff: Re: [bhle] 4.2.1 - Change individual search setting (#184)

4.2.1 - Change individual search setting

COR number: it is bug related to feature 4.2.1 - the description in COR need to be change, because there is not necessary to be registered user for use this feature.

Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Bug description:

Table view is not working properly. The metadata extend from the frames, creating a mess.
The table need to by styled and redesigned also with the new template. There are several different table views and also tables in tables in several cases. It is more or less a design function.

This bug is a result from 1st testing phase. Please read the description and write a comment if this bug is solved according to status of portal or not.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment]
Table and List views both working as expected. No merging of results apparent.

**Comment by HenningScholz** [comment]
I think this bug is gone. However, maybe related, when I search for all books (search for *) I see in the result summary 27 results, but only see 12 items in the result list (items per page is set to all). Clicking to page 2 or 3 gives no results. In the facet list I see 27 books, but a variety of counts for author, year, language etc. - How is that all related, why can I not see the 27 books?

---

Dr. Henning Scholz 
Museum für Naturkunde | Leibniz Institute for Research on Evolution and Biodiversity at the Humboldt University Berlin
Invalidenstraße 43 | D-10115 Berlin | Germany 
Tel.: +49-30-2093-8864 | Fax: +49-30-2093-8868 
Email: henning.scholz@mfn-berlin.de
http://www.naturkundemuseum-berlin.de/ / http://www.bivalve.de 
http://www.bhl-europe.eu / http://www.biodiversitylibrary.org/
BHL-Europe in Europeana:  bit.ly/BHLE-Europeana

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 16:29
An: Scholz, Henning
Betreff: Re: [bhle] 4.2.1 - Change individual search setting (#184)

4.2.1 - Change individual search setting

COR number: it is bug related to feature 4.2.1 - the description in COR need to be change, because there is not necessary to be registered user for use this feature.

Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Result list

Bug description:

Table view is not working properly. The metadata extend from the frames, creating a mess.
The table need to by styled and redesigned also with the new template. There are several different table views and also tables in tables in several cases. It is more or less a design function.

This bug is a result from 1st testing phase. Please read the description and write a comment if this bug is solved according to status of portal or not.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AntonioGVH** [comment]
I asked for 'Flora' and the result list lokks very well formated and complete.

Quoting JiriFrank:

**Comment by JiriFrank** [comment]
This feature was completely rebuild.

@RalfH 
The table view is mainly for have more results on one page.

For see the full title there is mouse over option in table view or you can switch the result list in to list view. 
In table view there are always displayed always 3 lines of text because of the space and proper size of fonts. The fog on the third line is the same effect which is using MS Windows. We made some improvements on developing platform and the mouse over option is now for all fields in case that there is more authors or longer range of years. Active is always just the title of item leading to bibliographic page of that item.

@HenningScholz 
The pagination for result list is not implemented yet because several conflicts with search module, but we are working on that. This function will be tested anyway in sense of result list and facet list, ideally with more content.

This bug is fixed.
