### ISSUE TITLE
Access – Web service for generating different formats for derivatives generated in realtime for different page ranges: PDF

### ISSUE THREAD

**Issue by audreyhzhang** [gbhl/bhl-europe#19]
Download selected pages in PDF format, enter page number in field (1-25)
The user interface is #16

**Comment by leenamba** [comment]
To test you can go to this URL and input different ranges:

http://bhl-alexandria.nhm.ac.uk/fedora/objects/demo%3Adarwin/methods

use the demo:book2pdf field enter the range and hit run.

example: 1-10,20-22,53-46

Know bugs now are whitespaces and single numbers.

You can also directly put ranges in the URL of the method

example:  http://bhl-alexandria.nhm.ac.uk/fedora/objects/demo%3Adarwin/methods/demo%3Abook2pdf/pdf?ranges=40-42

**Comment by zhengl** [comment]
Bugs have been fixed
Entering whitespaces is considered as the whole range of a book
Single numbers such as 1,4,6 can be used as the parameter, even mixed with other ranges.
For each range, if the lower bound is greater than the upper bound, it will be rearranged in a ascendant order. (e.g. 10-1=> 1-10)
If one of them is out of range, it will be rewritten to be within the range (e.g. 1-10000 => 1-114)

Here are some example that everybody could try:
1-10, 3, 40-42
10-1, 50, 60
(several whitespaces)
100-1000000

**Comment by chrisfreeland** [comment]
Users are going to need to be able to request by the page number printed on the page, not the series number of the page as scanned from the front of the book to the back of the book.  They need "Pages 1-3" not images 1-3.  Plus they will want to get pages from all parts of the book (a title page, the pages of an article, the plate and map at the back of the book), which is why we have a GUI for the same process, as at http://www.biodiversitylibrary.org/pdfgen/69526

**Comment by leenamba** [comment]
Yes we will need a UI which is in a separate issue #16
@janahoffmann
@jirifrank
We're going to need some specifications here based on Chris' comments.  Please advise.

**Comment by janahoffmann** [comment]
This issue is related to CoR feature 3.2.1. I will add your comments to the new feature as soon as possible.

**Comment by janahoffmann** [comment]
now issue #99
