### ISSUE TITLE
1.2.2 – Search by year of publication – metadata problem

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#198]
Search by year of publication works just for the LANDOE, UBER and UCPH collections, because they have a field Date. Other collections are not possible search or browse by date. 

The function itself is ready and the problem is probably just in metadata. But without fixing this problem the function is useless.

Related bug is #183.
Related feature #45

**Comment by janahoffmann** [comment]
@jirifrank
I am not sure if we should report this a bug as we don't know enough about the pre-ingest process. I informed Melita about these problems but as long as we don't see the fully functional pre-ingest tool we don't know what causes this. However, Melita is exploring the metadata of partners to check whether this is the orginal format, seems to be true for Landoe (year in title) and UBER/ UCPH (strange date format 1900-01-01). 
@Melitabirthaelmer
Any idea why the date is not displayed for the other content provider? compare :
RBGE: http://bhl-portal-dev.nhm.ac.uk/?q=node/19964
NAT: http://bhl-portal-dev.nhm.ac.uk/?q=node/19950
but
LANDOE
http://bhl-portal-dev.nhm.ac.uk/?q=node/16435
It seems to me that the metadata is displayed in very different ways... What causes this?

Maybe we should think about reducing the number of characters allowed in the date field to 4.

**Comment by melitabirthaelmer** [comment]
I guess this problem occurs because two different field names are used within the portal for displaying the publication date.

For LANDOE the publication date is in the field "Date" within the portal.
For RBGE and NAT the publication date is in the field "Publication" within the portal.

Having a look at the metadata on the NHM server for RBGE the publication date is available within the field 
<i>=260  \$aEdinburgh :$bHMSO $c1925</i>

Here is the corresponding metadata file for the RBGE item mentioned above:
http://bhl-celsus.nhm.ac.uk/uploads/RBGE/NRBGEv1-23/Volume14/NRBGEindex1-14.mrc 

FYI: this is the same item in Europeana for the RBGE example with a correct date field
http://www.europeana.eu/portal/record/08705/D3FA215D3B3C4BAF93EC9947787BDA27247F2444.html?start=2&pageId=brd&query=Notes+from+the+Royal+Botanic+Garden+Edinburgh+index&view=table&startPage=1

<b>This issue seems to be again related to how the metadata is processed for the portal. We can only judge sufficiently this issue after the metadata has been mapped to OLEF and displayed in the portal. </b>

**Comment by lobajuluwa** [comment]
Update from Portal Review workshop_The Hague: Search by year of publication  – reassign to Chris  for November sub release. (data issue).

**Comment by JiriFrank** [comment]
Under process of testing.

**Comment by JiriFrank** [comment]
related to Issue #45 which is functional and closed.
