### ISSUE TITLE
1.2.10b - Search for publishing language (Advanced search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#237]
Description:
Search in metadata field 'language', e.g. search for books published in German or Spanish.
Use unified language identifiers/ abbreviations

Precondition:
Provision of language information by CP in metadata.
or use language recognition tools

Connected issue #53  (previously summarised under 1.2.10 Search for publishing country/ language) 

Related bug: #180

**Comment by chris-sleep** [comment]
implemented

**Comment by JiriFrank** [comment]
1.2.10b - Search for publishing language (Advanced search)

COR number: 1.2.10b 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search in metadata field 'language', e.g. search for books published in German or Spanish.
Use unified language identifiers/ abbreviations

The three-letter word language code iso639-2b is required.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
1.2.10b - Search for publishing language (Advanced search)

COR number: 1.2.10b 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search in metadata field 'language', e.g. search for books published in German or Spanish.
Use unified language identifiers/ abbreviations

The three-letter word language code iso639-2b is required.

@AntonioGVH
@fwelter
@LarissaS

**Comment by LarissaS** [comment]
Works good

-----Original Message-----

**Comment by RalfH** [comment]
There seem to be problems. Searching for German publications the search result list is presenting 4 titles but there are at least 8 in the testing list.
French also gives one English title.

But who knows the code? To list it completely in the tutorial or elsewhere would inflate it. A link / drop down menu? Or preferably accepting the full (English) name of a language?

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 16:44
An: Hand, Ralf
Betreff: Re: [bhle] 1.2.10b - Search for publishing language (Advanced search) (#237)

1.2.10b - Search for publishing language (Advanced search)

COR number: 1.2.10b 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search in metadata field 'language', e.g. search for books published in German or Spanish.
Use unified language identifiers/ abbreviations

The three-letter word language code iso639-2b is required.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment]
Tried this for French.  Initially followed instruction and typed fre into search box in Advanced Search set to Language, result no search hits.

Then typed French into search box in Advanced Search set to Language, result 8 hits.  In the MODS data for each  of these books the field Language of the text contains the term "French" in full

**Comment by HenningScholz** [comment]
This works, although not always using the 3-letter code. French works with French not fre. German works with ger. I assume this is due to the manual ingest process.

---

Dr. Henning Scholz 
Museum für Naturkunde | Leibniz Institute for Research on Evolution and Biodiversity at the Humboldt University Berlin
Invalidenstraße 43 | D-10115 Berlin | Germany 
Tel.: +49-30-2093-8864 | Fax: +49-30-2093-8868 
Email: henning.scholz@mfn-berlin.de
http://www.naturkundemuseum-berlin.de/ / http://www.bivalve.de 
http://www.bhl-europe.eu / http://www.biodiversitylibrary.org/
BHL-Europe in Europeana:  bit.ly/BHLE-Europeana

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 16:44
An: Scholz, Henning
Betreff: Re: [bhle] 1.2.10b - Search for publishing language (Advanced search) (#237)

1.2.10b - Search for publishing language (Advanced search)

COR number: 1.2.10b 
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search in metadata field 'language', e.g. search for books published in German or Spanish.
Use unified language identifiers/ abbreviations

The three-letter word language code iso639-2b is required.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AntonioGVH** [comment]
This function seems to work properly.

Quoting JiriFrank:

**Comment by JiriFrank** [comment]
@HenningScholz 
Exaclty, the PI will use the three-letter word language code iso639-2b and will unify the result.

Will be tested again with more content.
On developing instance is it fixed already and using the facet list with language filtering works properly. 

@RalfH

**Comment by JiriFrank** [comment]
related issue is Issue #180
