### ISSUE TITLE
1.1.4 - Search with words including diacritic characters (Simple Search) - bug

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#288]
Bug reported from 2nd testing phase

For Aerzte

From simple search you will get: 

“Medicinisch-pharmaceutische botanik zugleich als handbuch der systematischen botanik fur botaniker, arzte und apotheker”

But when you edit the search and check “exact phrase” you will get again just only one book, but different one:

“Deutsche Flora. Pharmaceutisch-medicinische Botanik. Ein Grundriss der systematischen Botanik zum Selbststudium für Aerzte, Apotheker und Botaniker”

Why not both at the beginning?

For Plantulæra:

From simple search or advanced search you will get 0 results.

But checking the “exact phrase” you will get the right result:

Plantulæra : vió myndum

Related to Issue #36

**Comment by akohlbecker** [comment]
Another example from #74 (a bit extended) :
- search for 'Plantae' in olef_scientific_name returns zero entries
- search for 'Plantea*'  in olef_scientific_name returns four entires

The problem is the following line in https://github.com/bhle/bhle/blob/master/data-management/solr/core/conf/schema.xml :

```
<filter class="solr.PatternReplaceFilterFactory" pattern="([aAoOuU])e" replacement="$1" replace="all"/>
```

This solr.PatternReplaceFilter has been introduced to allow find 'Äpfel' also with the search terms 'Apfel' & 'Aepfel' but is only configured for the query processing, not for the indexing. The following happens in the analyzers during the indexing of 'Äpfel' and with 'Plantae':
- solr.ICUFoldingFilter: 'Äpfel' => **'apfel'** ; 'Plantae' => **'plantae'**

During the query processing the analyzers transform the terms 'Äpfel';  'Aepfel';  'Plantae' like:
- solr.ICUFoldingFilter: 'Äpfel' => 'apfel'; 'Aepfel' => 'aepfel'; 'Plantae' => 'plantae'
- solr.PatternReplaceFilter:  'apfel' => **'apfel'**; 'aepfel' => **'apfel'**; 'plantae' => _'planta'_

So 'Plantae' cannot be found, only when adding a wildcard character solr will skip all analyzers and the term  'Plantae' is found.

A feasible **Solution** of this problem would be to also add the

```
<filter class="solr.PatternReplaceFilterFactory" pattern="([aAoOuU])e" replacement="$1" replace="all"/>
```

to the indexing analyzers. In this case all Umlauts ä, ü, ö and ae, ue, oe combinations will always be indexed as a, u, o.

@wkollernhm

**Comment by JiriFrank** [comment]
Ready for testing.

**Comment by JiriFrank** [comment]
Ready to be closed.
