### ISSUE TITLE
implement fuzzy search

### ISSUE THREAD

**Issue by akohlbecker** [gbhl/bhl-europe#3]
The portal should  allow getting search result even if the search term not 100% identical to the token in the index (phonetic variant, typo, diacritics, ...) 

Fuzzy search can be realized by using  Solr Filters, see the following links for further reference:
- http://wiki.apache.org/solr/AnalyzersTokenizersTokenFilters#solr.PhoneticFilterFactory 
- http://lucene.apache.org/solr/api/org/apache/solr/analysis/PhoneticFilterFactory.html

**Comment by fwelter** [comment]
I would rank this at second priority (if we work with 3).
In any case such a function should only be optional, never among the default functions, which is one of the expressed results of the user survey.
http://www.planetposter.de/bhl/wien2010.htm

See Question 6 there, which covered this option:
"Google-like search was not preferred, even less by frequent users. Google returns too many insignificant results and is not able to search for an exact sequence of letters, incorrect spellings are automatically corrected (it is not possible to search for an uncommon spelling of a name), these are shortcomings in the Google search function and annoying for professional BHL users. BHL users seem to know exactly what they are looking for."

**Comment by janahoffmann** [comment]
This issue is related to CoR feature 1.1.10. I add Andreas comments and description to the new feature as soon as possible. 
Francisco, please keep in mind that we have to focus more on the public and a fuzzy search might be more interesting for the public user. I think it might be a good way to separate default search otpion by user profiles, such as scientist, publich user, librarian. The user survey only represents the opinion of scientists and can here not be weigthed the same. 
The fuzzy search is defined as a priority one feature.

**Comment by akohlbecker** [comment]
ticket replaced by #42
