### ISSUE TITLE
1.1.1 - Search with unordered keywords (Simple Search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#33]
Updated description (JH) CoRv1:

Search with unordered keywords, e.g. 'amphipod', '1967', 'Hedley'
Restrict result view to items only including all search terms. Sort/ filter by facet list 

General filtering done by facet list with active links to individual search terms. 
This is default setting for the advanced search. 

Preconditions: 
Simple search is restricted to main categories (author, title/ journal title, year, taxon)

@akohlbecker

Previous description:
e.g. ‘amphipod’  ‘1967’  ‘Hedley’ (no use of boolean operators)

Extension (Francsico): 
Give results including all 3 search terms in this format (facet list):
term a,b,c - x results
term a - x results
term b - x results
term c - x results

Related bugs: #172 (1); #173 (2); #174 (3); #175

**Comment by JiriFrank** [comment]
Thi is the simple search option (box under the Navigation blog).

**Comment by janahoffmann** [comment]
indication of search string very good: matches for...(very transparent)

basic functionality of this feature o.k. but results inaccessible

specific bugs:
- provide facet list for unordered search terms, e.g. results for "Hedley amphipod" shall be displayed as Hedley + amphipod (x items), hedley (x item), amphipod (x items)
- best matches shall be displayed first, e.g. Denisia Bartsch; the actual item that matches Denisia (title) and Bartsch (author) is listed at 5th place and less good hits with just one of the two keywords are listed before

general bug: 
- Abstract and Notes are displayed in the metadata view but contain identical content (duplication)
- search is performed in all metadata fields (also abstract) and thus results are also given for e.g. terms in abstract; difficult to handle and sort if not indicated where it was found, only separated in result in dates and text in facet list (left menu), this needs to be extended to main search categories, I recommend limiting search to specific metadata field in simple search (e.g. main search categories) and not all (this can be done in advanced search: search in all metadata field, already implemented) or the results need to be structured in a better way e.g. main categories: title (x items), author (x items), year (x items), (journal title); all in the main page and not in the left hand menu
- abstract are not always displayed in full length but cut off (all or nothing)
- left hand facet list in result view: sort by importance: date, language, collection (only acronym), type (what is the definition for text? ): journal/ series, monograph

**Comment by JiriFrank** [comment]
Test1a: Matches for: 'amphipod' '1967' 'Hedley'
about 200 items
order of:
amphipod – 1-5, 11, 12, 14, 15, 32 …
1967 - 6-10, 16-31 …
Hedley – on 13th place, just one record.

Test1b: Matches for: '1967' 'Hedley' 'amphipod'
same results

Test1c: Matches for: 'Hedley' 'amphipod' '1967'
same results

Test1d: Matches for: 'amphipod' 'Hedley' '1967'
same results

---

Test2a: ‘Sowerby’ ‘Cephalopoda’
16 items
order of:
Sowerby - 2, 4, 9, 10, 11, 13, 14
Cephalopoda – 1, 3, 5, 6, 7, 8, 12, 15, 16

Test2b: Simple search just Soweby
7 items
Test2c: Simple search just Cephalopoda
9 items

---

Test3: Matches for: Sowerby Mollusca
Sowerby – 1, 2, 3, 4, 5, 6, 7, 
Mollusca – 1, 2, 3, 4, 8 – app. 350  

---

Summary of test 1:
In this case was tested search with 3 terms, which are not included together in any book. The results are always the same independent on order of searched terms. The list of books (search result) is ordered chaotically and group of books with the same searching terms is spread out over the list.

Summary of test 2:
In this case was tested search with 2 terms, which are not included together in any book. The list of books (search result) is again ordered chaotically and group of books with the same searching terms is spread out over the list. Additional tests (2b-c) proved that the result of test 2a includes all books of searching terms.

Summary of test 3:
In this case was tested search with 2 terms, which are included together in several books. One term is represented just in 7 books and the second in many. The result list is ordered properly. All 7 books from the one term are on the begging of the list. Also all 4 books which include both of searching terms are at the beginning of the list. 

Conclusions:
Search with unordered keywords is working. The list of results is ordered properly if the searching terms are included together in the book. In the case when the searching terms are not included together in the book, the list of results is ordered chaotically. 

Bug: Search with unordered keywords with terms which are not included together in books. The list of books (search result) is ordered chaotically and group of books with the same searching terms is spread out over the list.

Proposal of requirement:
1.  Amount of searching items in the search result which Matches for: x y terms.
2.  Number the items in search result list.

**Comment by JiriFrank** [comment]
Testing of feature 1.1.1 - Search with unordered keywords

Feature description from the Catalogue of user requirements:

e.g. ‘amphipod’ ‘1967’ ‘Hedley’ (no use of boolean operators)

Extension (Francsico):
Give results including all 3 search terms in this format (facet list):
term a,b,c - x results
term a - x results
term b - x results
term c - x results

@AntonioGVH
@fwelter
@heimor
@janahoffmann
@JFTester
@JiriFrank
@LarissaS

**Comment by JiriFrank** [comment]
Testing of feature 1.1.1 - Search with unordered keywords

Feature description from the Catalogue of user requirements:

e.g. ‘amphipod’ ‘1967’ ‘Hedley’ (no use of boolean operators)

Extension (Francsico):
Give results including all 3 search terms in this format (facet list):
term a,b,c - x results
term a - x results
term b - x results
term c - x results

@fwelter

**Comment by LarissaS** [comment]
Dear Jiri,
Because I never did something like this I would like to know if I did it correct and if this is what you expect from the tester!
Here are my remarks for the first job!

Test 1: searching for “Sowerby Mollusca”
318 results, same for “Mollusca Sowerby”
Sowerby – 7
Mollusca - 315

In records of Oberösterreichisches Landesmuseum year of publication is shown, in other records – not. 

For collection of RMCA (records Von Martens “Mollusca. Varia I and II”) - records appear twice!
Only two languages appear; ger (4) and spa (1), where is the rest?

Sorting on date does not work in full selection, well inside a collection (NCB Naturalis or Oberösterreichisches Landesmuseum)

“Date” (column under search) disappear if I choose the Naturalis collection
It’s shown 277 records in Naturalis, but then I click on it I get only 7 records! And today (03/08/2011) collections of RMCA and Austria does not appear (I’ve got message “Your search yielded no results”)

Test 2: "poisson afrique" 46 records
afrique poisson – the same
poisson – 23
afrique - 24

17 records of RMCA, I click on it and see only 7! 

Test 3: "poisson boulenger 1899" – 136 records TEXT, 2 records BOOK and 2 records BOOKS, MONOGRAPHS. What is difference between them?! 
Poisons – 23
Boulenger – 39
1899 - 86
For collection of RMCA records are shown twice! For example searching for “boulenger” gives 10 records from RMCA, and they are all doubles! The same is for search “1899” two records from RMCA is actually one record of Balbiani. 

Sorting on date does not  work neither for RMCA nor for Naturalis, well for Oberösterreichisches Landesmuseum

I have searched for “poisons boulenger” and saw that clicking on DATE (left column) gives sometimes not correct results, for example for 1996 there are 3 records, I click on it and I see only two records.

General comments: 
The arrow showing direction of sorting appear not on good place, it should be closer to the sorting word! Otherwise it’s confusing.

It’s not clear how many matches I really have, may be above where it’s written 
“Matches for: 1899” we should give exact number of matches and in the left column we give details of the search (type, date, collection etc.)?

Why search term is only highlighted in the title and not in the record description? 

Would be useful to see somehow previous searching’s and to be able to go back in it!

-----Original Message-----

**Comment by AntonioGVH** [comment]
Hello Jiri! (I am sending this too to Jana, just to check with her if this is the kind of test that it is expected from me).

This is my first trial at testing and I would like to know if this is the kind of comment that can be useful.

The behaviour of the portal is somewhat idiosincratic (will explain below).

Concerning type of search 1.1.1

1) The result is stable (similar list of publications) using different order and uppercase and lowercase first letter: " Amphipod 1967 Hedley"; "amphipod 1967 Hedley"; "amphipod 1967 hedley"; "hedley 1967 Amphipod" etc.
2) Some records have nothing to do with "amphipod" or "Hedley" when searching for "amphipod 1967 Hedley". For example, record number 6, but there are others.
3) The ordering of records seems to be the same querying by "amphipod 1967 Hedley", " 1967 Amphipod Hedley" etc.
4) I do not find very useful to do single queries by "amphipod" "1967" or "Hedley"
5) The statistics at the right of the screen are inexplicable. I counted a total of 160 records with a query of "amphipod 1967 Hedley", however the set of statistics gave figures that do not have a clear relation with 160 (but may have...) I include herewith an screen shot (partial screen of amphipode 1967 Hedley.jpg)

Some idiosyncrasies of the portal:
- Entering by http://bhl-portal-dev.nhm.ac.uk/  takes you to screenshot_1. But if we enter "amphipod 1967 Hedley" the output screen says we are in 'advances searching'. See screenshot_1bis
- If we click on "buscar" (search in English), we get screenshot_2, where some options for browse appear.
- Clicking in a record, takes you to the next screen (see screenshot_3). It is suppose that the code in this page are in Spanish too, but "type" is written "tipo" in Spanish, "Digital object" is "Objeto digital" and "Lugar de archivación" is not a proper Spanish wording. It is much better to say "Depósito". I apologize if I gave those translations before.

I would greatly appreciate some feedback before continuing the testing

Best wishes

Antonio

Quoting JiriFrank:

**Comment by fwelter** [comment]
Hi Jiri, I hope this is the correct form to report.

simple search
- page takes very long to load in. this is because of the thumbnails. replace thumbnails by standard icons. would be easier for the testing.
- headline should list the number of results. would also be easier for the testing.
- it is very difficult to test if the program found what I have searched because it apparently also searches in abstracts and other metadata, not only in the title, author and journal title. this makes it practically impossible to confirm "the search function has worked correctly".
- default simple search function should be different from what is currently working there as simple search, as outlined in many mails before. 
- I would have appreciated more detailed instructions about the pruposes/objectives of these tests, to know what exactly we have to look for and what we could ignore and so. many things are not working when I start searching with unordered keywords - it is not always clear to me what kind of things I have to report. the instructions given above are very cryptic and not intelligible to me as non-insider who has not participated in elaborating these instructions in their present form, and who has not learned to understand this language.
- In any case the search function should be modified, we should test the search function and the result lists at the same time.
- It seems to me that some very basic parts of the application have not yet been programmed. Perhaps too early to start testing?

**Comment by fwelter** [comment]
1.1.1.   unordered keywords

mantides
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 2 + 1. 
- of these, search term found in title (and displayed yellow): 1

musee
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 25 + 20 + 7. 
- of these, search term found in title (and displayed yellow): 5
- in one title the word "Muse" was marked, so the search for musee
  incorrectly found muse

hepialidae
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 5 + 4. 
- of these, search term found in title (and displayed yellow): 3
- in title No. 3 the yellow mark did not correctly indicate the first
  word Hepialidae, but "pialidae ("

voyage iles
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 22 + 7 + 5. 
- of these, search term found in title (and displayed yellow): 7
- "Languages:" fre (7). this was incorrect, 15 titles were in french.
  english, dutch and german titles were not detected. 7 results were
  those from Royal Museum for Central Africa. NCB Naturalis and
  Oberösterreichisches Landesmuseum returned no results for language.
- clicking on "fre" gave 7 results with a display: Matches for: voyage
  iles AND dc_language__facet:"fre"
- I in Iles sometimes not marked in yellow (this error was independent
  from seach for i, î, I or Î)
- contained hits where only ile and not iles were contained
- at one occasion in a result hit "de l'Île de Formosa ..." the term
  "le d" was marked in yellow. 
- contained hits where only ile and not iles were contained
- clicking on the Data Provider links gave correct results (same
  numbers of papers shown as listed in the count) for the following data
  providers:

mantides musee AND europeana_dataProvider__facet:"Royal Museum for
Central Africa" mantides musee AND europeana_dataProvider__facet:"NCB
Naturalis" mantides musee AND
europeana_dataProvider__facet:"Oberösterreichisches Landesmuseum"

voyages iles
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 22 + 7 + 5. 
- same results as for voyage iles
- contained hits where only voyage and not voyages were contained

mantides musee
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 25 + 20 + 9. 
- of these, search term found in title (and displayed yellow): 5
- "Languages:" gave 20 results for "fre". These were the 20 hits which
  came from Royal Museum for Central Africa. NCB Naturalis and
  Oberösterreichisches Landesmuseum returned no results for language.
- in one hit "ée de " was marked in yellow.
- clicking on the Data Provider links gave correct results (same
  numbers of papers shown as listed in the count) for the following data
  providers:

25 hits:     mantides musee AND europeana_dataProvider__facet:"NCB
Naturalis" 20 hits:     mantides musee AND
europeana_dataProvider__facet:"Royal Museum for Central Africa"
 7 hits:     mantides musee AND
 europeana_dataProvider__facet:"Oberösterreichisches Landesmuseum"

mantides du musee
- the number of hits was not indicated, you have to count "Data
  Provider" (or "Rights"): 
  1. NCB Naturalis (94)
  2. Oberösterreichisches Landesmuseum (63)
  3. Royal Museum for Central Africa (38)
  4. Universitätsbibliothek Bielefeld (5)
- "Rights": returned 4 different rights, because they had different
  internet pages. It is likely that they were all based on the same
  Creative Commons 3.0 rights. clicking on the linked internet pages
  returned an error.
- clicking on the Data Provider links gave following results for the
  following data providers:

25 hits:     mantides du musee AND europeana_dataProvider__facet:"NCB
Naturalis" 20 hits:     mantides du musee AND
europeana_dataProvider__facet:"Royal Museum for Central Africa"
 7 hits:     mantides du musee AND
 europeana_dataProvider__facet:"Oberösterreichisches Landesmuseum"
- clicking on the Data Provider links gave zero results for the
  following data provider:

mantides du musee AND
europeana_dataProvider__facet:"Universitätsbibliothek Bielefeld"
- "Language:    1. fre (34)    2. eng (4)
- clicking on these languages gave correctly 34 results for fre, but 0
  results for eng

musees
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 25 + 20 + 9. 
- of these, search term found in title (and displayed yellow): 5
- returned also hits for muse, musée

muse
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 25 + 20 + 9. 
- same results as for musee and musees

musen
- no results

museen
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 56 + 15. 
- of these, search term found in title (and displayed yellow): 5

museum
- the number of hits was not indicated, you have to count "Data
  Provider" (or "Rights"):
  1. NCB Naturalis (699)
  2. Oberösterreichisches Landesmuseum (304)
  3. Royal Museum for Central Africa (102)
  4. UB der Humboldt-Universität, Zweigbibliothek Museum für
     Naturkunde (61) 5. University of Copenhagen (28)
- clicking on the Data Provider links gave correct results (same
  numbers of papers listed as announced in the count) for all.
- Royal Museum for Central Africa and UB der Humboldt-Universität,
  Zweigbibliothek Museum für Naturkunde hat this term in their names, so
  the search returned presumably all titles of this provider and marked
  Museum in yellow

genre et quelques
- the number of hits was not indicated, you have to count "Data
  Provider" 207 + 156 + 30 + 21 + 2
  1. NCB Naturalis (207)
  2. Oberösterreichisches Landesmuseum (156)
  3. Helsingin yliopisto (30)
  4. Royal Museum for Central Africa (21)
  5. UB der Humboldt-Universität, Zweigbibliothek Museum für
     Naturkunde (2)
- or "Rights": 209 + 156 + 30 + 21 + 1
- Only about 5-10 % of the results hat one of the words marked yellow
  in the title
- the yellow mark did not always hit the word exactly, but by 2-3
  letters inaccurate
- "Languages:"    1. ger (30)    2. fre (17)   3. swe (15)   4. fin
  (14)   5. eng (10)
- clicking on these languages gave 0 results in all cases, and a
  display in this form: Matches for: genre et quelques AND
  dc_language__facet:"fre"
- clicking on the Data Provider links gave the following results:

25 hits:     genre et quelques AND
europeana_dataProvider__facet:"Oberösterreichisches Landesmuseum" 20
hits:     genre et quelques AND europeana_dataProvider__facet:"NCB
Naturalis"
- clicking on the Data Provider links gave incorrectly zero results
  for the following data providers:

genre et quelques AND europeana_dataProvider__facet:"Helsingin
yliopisto" genre et quelques AND europeana_dataProvider__facet:"Royal
Museum for Central Africa" genre et quelques AND
europeana_dataProvider__facet:"UB der Humboldt-Universität,
Zweigbibliothek Museum für Naturkunde"

genre quelques
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 51 + 47 
  1. NCB Naturalis (51)
  2. Oberösterreichisches Landesmuseum (47)
- of these, search term found in title (and displayed yellow): 10
- clicking on the Data Provider links gave the folloing results:

20 hits:     genre quelques AND europeana_dataProvider__facet:"NCB
Naturalis" 25 hits:     genre quelques AND
europeana_dataProvider__facet:"Oberösterreichisches Landesmuseum" 

so the hits I actually got were different from those announced at the
main page.

apres
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 12 + 6 + 1
- of these, search term found in title (and displayed yellow): 6
- returned 4 results for Apr and 2 for après

vertebres
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 45 + 2
- of these, search term found in title (and displayed yellow): 20
- returned results for vertébrés, vertebrates, vertebral

zoologie
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 144 + 22 + 11 + 2
- of these, search term found in title (and displayed yellow): about
  80
- most of the returned results were single journal volumes of 3
  journals that had "zoologie" in its title: Joannea Zoologie,
  Mitteilungen der Abteilung für Zoologie am Landesmuseum Joanneum Graz,
  Mitteilungen der Abteilung für Zoologie und Botanik am Landesmuseum
  Joanneum Graz, over and over the same journals again

über placenta
- the number of hits was not indicated, you have to count "Data
  Provider" (or "Rights"):
  1. Oberösterreichisches Landesmuseum (1224)
  2. Universitätsbibliothek Bielefeld (188)
  3. NCB Naturalis (106)
  4. Royal Museum for Central Africa (6)
  5. UB der Humboldt-Universität, Zweigbibliothek Museum für
     Naturkunde (3)
- of these, search term found in title (and displayed yellow): about
  100
- clicking on the Data Provider links gave results for the following
  data provider:

2 hits:     über and placenta AND europeana_dataProvider__facet:"Royal
Museum for Central Africa"
- clicking on the Data Provider links gave zero results for the
  following data providers:

über placenta AND
europeana_dataProvider__facet:"Universitätsbibliothek Bielefeld" über
placenta AND europeana_dataProvider__facet:"NCB Naturalis" über
placenta AND europeana_dataProvider__facet:"UB der
Humboldt-Universität, Zweigbibliothek Museum für Naturkunde" über
placenta AND europeana_dataProvider__facet:"Oberösterreichisches
Landesmuseum"
- "Language:"
  1. ger (6)
  2. Latin (2)
  3. deutsch (1)
- clicking on these languages yielded 2 results for ger, 0 for Latin
  and 0 for deutsch

---
- when there were many results the page took long time to load in and
  blocked the mouse of my computer. this was because all the thumbnails
  needed to load in. it seems that also those thumbnails needed to load
  in that were not displayed on the screen. if I had installed to
  display 25 results in the hitlist and there were 1500 results the
  thumnails for all 1500 results loaded in. after that the computer was
  largely blocked and very slow, I tried to close the window as soon as
  possible and I also tried not to select search terms that produced so
  many results.
- nowhere was displayed how many titles were found in total, usually I
  listed the numbers given for data providers. only maximum 5 data
  providers were shown, I discovered this bug only very late in the
  testing process.
- it is also possible that Date, Language and the other facet lists
  had also restrictions for 5 lines to be shown only. I realised this
  only after 2 weeks testing.
- the big problem was that too many results were shown, mainly for two
  reasons:

1 - the result lists generally displayed titles where none of the
words were contained in the title, author or year, but in the text of
the abstract and notes of the item page. 

2 - single journal volumes were displayed for serial runs, they
blocked all intelligent search attempts and spammed the results list
with over and over the same journal title. 
- it was generally very difficult (better say, practically impossible)
  to test for completeness of results. restricting search for (1) only
  in title, author and date and (2) exclude journal metadata of single
  journal volume item pages (and instead create one single journal title
  hit) would probably solve the problems.

Francisco

---

F. Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536, Fax +49 551 395579
http://www.gwdg.de/~fwelter
http://www.animalbase.org

**Comment by akohlbecker** [comment]
This issue seems to be referring to faceted search and to simple search at the same time. Can someone (@JiriFrank, @lobajuluwa  ) review and update this ticket?

Simple search is done. So this ticket can considered being fixed if it's only on doing a simple search with unordered keywords.

**Comment by akohlbecker** [comment]
@JiriFrank wrote:

this has nothing to do with facet list. It means that the result from searching the unordered keywords in simple search will give you just results with documents including all these words together.

You can use the facet list for other sorting in the result list, but this is the function of facet list and has nothing to do with this ticket unordered keywords (the feature description is confusing).

If the searching of unordered keywords is functional in simple search, than could be this feature closed as Andreas mentioned.

**Comment by akohlbecker** [comment]
Use the extendeddismax (solr) parser for both simple and advance search and also add any combination of the fields author, year, scientific name and title to the field selection list of advanced search.
So it will be possible to also use the simple search specific behavior in advanced search. This will bring simple and advanced search in align and thus should solve the problems we are having with the faceted search.
