### ISSUE TITLE
1.1.2 - Search with Boolean operators (now: 1.2.14 Advanced Search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#34]
search with AND, OR, NOT, +, “search term”

e.g. mouse and Hedley
mouse or Hedley
mouse + Hedley
"mature mouse"

**Comment by janahoffmann** [comment]
previous comments: @fwelter
Boolean terms seach (and, or etc.) should NOT be included in the default search function. The default search function should be able to understand the word "and" as a word belonging to the title.

**Comment by JiriFrank** [comment]
Thi is the simple search option (box under the Navigation blog).

**Comment by janahoffmann** [comment]
tested following operator: "search term", AND, +, OR
all work fine in simple search

**Comment by JiriFrank** [comment]
Testing of feature 1.1.2 - Search with Boolean operators

Feature description from the Catalogue of user requirements:

search with AND, OR, +, “search term”

e.g. mouse and Hedley
mouse or Hedley
mouse + Hedley
"mature mouse"

Testers:
@AntonioGVH
@fwelter
@heimor
@janahoffmann
@JFTester
@JiriFrank
@LarissaS

**Comment by JiriFrank** [comment]
Testing of feature 1.1.2 - Search with Boolean operators

Feature description from the Catalogue of user requirements:

search with AND, OR, +, “search term”

e.g. mouse and Hedley
mouse or Hedley
mouse + Hedley
"mature mouse"

Testers:
@fwelter

**Comment by LarissaS** [comment]
Testing of feature 1.1.2 - Search with Boolean operators

Feature description from the Catalogue of user requirements:

search with AND, OR, +, "search term"

Test 1: searching for " waterhouse AND mammalia " - one record of RMCA (double! I don't know if I have to mention it always!)
"waterhouse OR mammalian" - 223 records
" waterhouse +  mammalia " - 223 records
"waterhouse" - one record
"mammalia" - 223 records
"natural selection" - 1 record

"boulenger AND poisons" - 10 records (5 doubles from RMCA)
"boulenger OR poisons" - 52 records (5 doubles from RMCA)
"boulenger" - 39 (5 doubles from RMCA)
"poissons" - 23 (5 doubles from RMCA)

"natural selection" - 1 record
"African fish" - no records, African fish - 230 records, African AND fish - 4 records
"African flora" - no records, African flora - 582, African AND flora - 2 records

As I already mentioned it's very difficult to estimate results of search without having highlighting in the detail description. For example, if I look for Boulenger in BHL-US, I get 28 results: these are books written by Boulenger, I can immediately see that there are two authors with name Boulenger, I also can see scientific names starting with bouleng... It is very practical. But BHL-US has no possibility to search with Boolean operators, at least I did not find.
In BHL-Eu searching for Boulenger give me 39 records, where only 10 from RMCA (5 doubles) are written by Boulenger, in other 29 records Boulenger is only mentioned in annotation or the scientific name starting with boulenger.... and you have to open every record to see what did you find! Not practical. So far as I see search with Boolean operators works good, but I would like to see in search results for example "boulenger OR poissons" how many records are matching "boulenger" and how many "poissons", to see in what records boulenger is an author and how many different authors with the  same name I have. 
May be I explained not clear, but I find the search results presented not clear!

---

 -----Original Message-----

**Comment by AntonioGVH** [comment]
Jiri, 
          I am using the words you suggest for querying the portal, assuming that there is some content that have those words inside the documents. I assume there is no point to ask, for instance, for 'Garcia' and 'ticks', if there are no documents with those words in the data base.
Please, correct me if I am wrong.

---

Search with:

mouse and Hedley 

gives 5 results. I searched the pdf of the first result and nowhere appear 'Hedley'.

Besides that, once I click on the first record, the next screen shows all the language options cross out. Screen shot included.

Best

 Antonio

Quoting JiriFrank:

**Comment by AntonioGVH** [comment]
Continuation of the previous 1.1.2

Searching by mouse AND Hedley (AND in upper case letters) produce no result. 
Using OR with capital letters works the same as with lower case letters.

Antonio

Quoting JiriFrank:

**Comment by fwelter** [comment]
1.1.2  boolean operators  and or +

"musee"
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 25 + 20 + 7. 
- same result as for musee without quotes

"Musée"
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 25 + 20 + 7. 
- same result as for musee without quotes

voyage + iles
- the number of hits was not indicated, I had to count "Data Provider"
  or "Rights": 13 + 4 + 3. 
- of these, search term found in title (and displayed yellow): 4
- "Languages:" gave 4 results for "fre". this was incorrect, 12 titles
  were in french. english, dutch and german titles were not detected. 4
  results were those from Royal Museum for Central Africa. NCB Naturalis
  and Oberösterreichisches Landesmuseum returned no results for
  language.
- I in Iles sometimes not marked in yellow (this error was independent
  from seach for i, î, I or Î)
- result list did not display titles where the word "voyage" was
  contained, but did display titles where the word "iles" was contained
  alone in the title
- in those hits where only the word "iles" was contained in the title,
  the words "voyage" was not contained in the displayed metadata fields
  of the item page. it was unclear to me why those results were listed.

voyage and iles
- the number of hits was not indicated, I had to count "Data Provider"
  or "Rights": 22 + 7 + 5. 
- same results as for voyage iles, no difference

voyage or iles
- the number of hits was not indicated, I had to count "Data Provider"
  or "Rights": 22 + 7 + 5. 
- same results as for voyage iles, no difference

"voyage iles"
- no results. this was correct.

mantides and musee
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 25 + 20 + 9. 
- same results as mantides musee

mantides or musee
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 25 + 20 + 9. 
- same results as mantides musee

mantides + musee
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 25 + 20 + 9. 
- same results as mantides musee

"mantides du musee"
- 1 result (mantides du Musée). this was correct.

"mantides musee"
- no results. this was correct.

"mantide du muse"
- returns 1 result (mantides du Musée). this was incorrect.

über and placenta
- the number of hits was not indicated, you have to count "Data
  Provider" (or "Rights"):
  1. Oberösterreichisches Landesmuseum (1224)
  2. Universitätsbibliothek Bielefeld (188)
  3. NCB Naturalis (106)
  4. Royal Museum for Central Africa (6)
  5. UB der Humboldt-Universität, Zweigbibliothek Museum für
     Naturkunde (3)
- of these, search term found in title (and displayed yellow): about
  100
- same results as for über placenta
- clicking on the Data Provider links gave 2 results for the following
  data providers:

über and placenta AND europeana_dataProvider__facet:"Royal Museum for
Central Africa"
- clicking on the Data Provider links gave zero results for the
  following data providers:

über and placenta AND
europeana_dataProvider__facet:"Universitätsbibliothek Bielefeld" über
and placenta AND europeana_dataProvider__facet:"NCB Naturalis" über
and placenta AND europeana_dataProvider__facet:"UB der
Humboldt-Universität, Zweigbibliothek Museum für Naturkunde" über and
placenta AND europeana_dataProvider__facet:"Oberösterreichisches
Landesmuseum"

exact search does not work, the boolean operators AND + OR do not work
on the main page. it seems that the search within the data providers
accept boolean operators, but not the general search.

search in quotes "xxx" is expected to return exactly what is in the
quotes and nothing else. this does not work properly: the program
seems to accept some tolerance, for example -e and -es at the ending
of words is ignored. It is acceptable that diacritic marks are ignored
in this kind of search (and also capitalised letters).

---
- when there were many results the page took long time to load in and
  blocked the mouse of my computer. this was because all the thumbnails
  needed to load in. it seems that also those thumbnails needed to load
  in that were not displayed on the screen. if I had installed to
  display 25 results in the hitlist and there were 1500 results the
  thumnails for all 1500 results loaded in. after that the computer was
  largely blocked and very slow, I tried to close the window as soon as
  possible and I also tried not to select search terms that produced so
  many results.
- nowhere was displayed how many titles were found in total, usually I
  listed the numbers given for data providers. only maximum 5 data
  providers were shown, I discovered this bug only very late in the
  testing process.
- it is also possible that Date, Language and the other facet lists
  had also restrictions for 5 lines to be shown only. I realised this
  only after 2 weeks testing.
- the big problem was that too many results were shown, mainly for two
  reasons:

1 - the result lists generally displayed titles where none of the
words were contained in the title, author or year, but in the text of
the abstract and notes of the item page. 

2 - single journal volumes were displayed for serial runs, they
blocked all intelligent search attempts and spammed the results list
with over and over the same journal title. 
- it was generally very difficult (better say, practically impossible)
  to test for completeness of results. restricting search for (1) only
  in title, author and date and (2) exclude journal metadata of single
  journal volume item pages (and instead create one single journal title
  hit) would probably solve the problems.

Francisco

---

F. Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536, Fax +49 551 395579
http://www.gwdg.de/~fwelter
http://www.animalbase.org

**Comment by JiriFrank** [comment]
Search with Boolean operators seems to works properly. Serching for exact phrase in the case in one word have some level of tolerance which was reported in bug #177.

**Comment by JiriFrank** [comment]
1.1.2 - Search with Boolean operators (now: 1.2.14 Advanced Search)

COR number: 1.2.14
Testing platform: http://bhl-test.nhm.ac.uk/portal/

Description:

search with AND, OR, NOT, +, “search term” in Advanced search

e.g. mouse AND Hedley
mouse OR Hedley
mouse + Hedley
"mature mouse"

Use the search terms from books I sent in the list yesterday. 

Closer explanations of Boolean operators see here http://www.knowledgecenter.unr.edu/help/using/booltips.aspx. 

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by RalfH** [comment]
Everything works perfect.

Ralf

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:07
An: Hand, Ralf
Betreff: Re: [bhle] 1.1.2 - Search with Boolean operators (now: 1.2.14 Advanced Search) (#34)

1.1.2 - Search with Boolean operators (now: 1.2.14 Advanced Search)

COR number: 1.2.14
Testing platform: http://bhl-test.nhm.ac.uk/portal/

Description:

search with AND, OR, NOT, +, "search term" in Advanced search

e.g. mouse AND Hedley
mouse OR Hedley
mouse + Hedley
"mature mouse"

Use the search terms from books I sent in the list yesterday. 

Closer explanations of Boolean operators see here http://www.knowledgecenter.unr.edu/help/using/booltips.aspx. 

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by HenningScholz** [comment]
This works. In terms of useability (I know we are not testing for useability, but...) it is not intuitive how to work with the "AND" operator. There are buttons for NOT and OR but not for AND. It also looks like using AND or a space between the serach terms give the same result. Also just adding a search field and typing in the next search term gives the same results. But this is a useability problem.

Henning

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 13:07
An: Scholz, Henning
Betreff: Re: [bhle] 1.1.2 - Search with Boolean operators (now: 1.2.14 Advanced Search) (#34)

1.1.2 - Search with Boolean operators (now: 1.2.14 Advanced Search)

COR number: 1.2.14
Testing platform: http://bhl-test.nhm.ac.uk/portal/

Description:

search with AND, OR, NOT, +, "search term" in Advanced search

e.g. mouse AND Hedley
mouse OR Hedley
mouse + Hedley
"mature mouse"

Use the search terms from books I sent in the list yesterday.

Closer explanations of Boolean operators see here http://www.knowledgecenter.unr.edu/help/using/booltips.aspx.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AnneSch** [comment]
Works fine. 

Anne

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:07
An: Scholz, Annemarie
Betreff: Re: [bhle] 1.1.2 - Search with Boolean operators (now: 1.2.14 Advanced Search) (#34)

1.1.2 - Search with Boolean operators (now: 1.2.14 Advanced Search)

COR number: 1.2.14
Testing platform: http://bhl-test.nhm.ac.uk/portal/

Description:

search with AND, OR, NOT, +, "search term" in Advanced search

e.g. mouse AND Hedley
mouse OR Hedley
mouse + Hedley
"mature mouse"

Use the search terms from books I sent in the list yesterday. 

Closer explanations of Boolean operators see here http://www.knowledgecenter.unr.edu/help/using/booltips.aspx. 

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
1.1.2 - Search with Boolean operators (now: 1.2.14 Advanced Search)

COR number: 1.2.14
Testing platform: http://bhl-test.nhm.ac.uk/portal/

Description:

search with AND, OR, NOT, +, “search term” in Advanced search

e.g. mouse AND Hedley
mouse OR Hedley
mouse + Hedley
"mature mouse"

Use the search terms from books I sent in the list yesterday.

Closer explanations of Boolean operators see here http://www.knowledgecenter.unr.edu/help/using/booltips.aspx.

@AntonioGVH
@fwelter
@LarissaS

**Comment by grahamhrbge1670** [comment]
I'm switching between Firefox 9.0 and IE 8.  
The Boolean search is working for Author + Title ; Title NOT Author ; Title + Year ; 

However, I have a few basic functionality problems.  The reset button does not work in Advanced Search, I'm having to manually clear the search box, which is time consuming.

Another problem, which might probably be related to the inability to clear the search box using the reset button, is that searches set by other testers are appearing when I hit the step back button in Advanced Search and also  when I switched to IE8 from Firefox 9.0.  When I switched over the Advanced Search: Author: Krogerus + Year: 1932 was appearing.

Graham

**Comment by JiriFrank** [comment]
The functionality is working fine. From the testers comment rise up two small requirements. 
1. Functional integration of Boolean operator AND needs to be explained in tutorial and hint bar. 
2. Menu Add field will be renamed to "Add field / AND"

@HenningScholz 
Yes the AND is set up as default in search between search fields and unordered keywords. It must be as default for facet list, because all categories in facet list need to be related by AND (filter function). It is also the reason why is possible use the OR or NOT just inside the search field and not between fields. It is based on mathematics logic. e.g. 5_3+5_3=60 but (5_3)+(5_3)=30. the first case is without AND as default.

@grahamhrbge1670 
The reset button is fixed and working now. The fields in advanced search are still filed till you do not close your session by using reset button or adding new search from simple search or browse. If you go from result list to book bibliographic page and even to book-viewer you are still in your session and have the possibility go back and modify you search. 

The step back button in result list was changed to Edit search button and the result list was integrated under the advanced search block or browse block. It solved several problems and will be tested in next phase.

**Comment by JiriFrank** [comment]
Requirement for discussion. 

"Enter"automatically add the OR. 

"Tab" is working properly and changing between menus.

Is a requirement for "Enter" to be sets up as default request for starting search?

@HenningScholz 
@chris-sleep 
@GrahamHigley

**Comment by JiriFrank** [comment]
Requirements above are independent and do not affect directly this feature functionality. 
Feature could be close.

@chris-sleep
@lobajuluwa

**Comment by chris-sleep** [comment]
Boolean default function is now working as required to enable the search and faceting (to increase precision) functionality
