### ISSUE TITLE
Add logged in content provider to metadata

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#365]
As mods:recordContentSource indicates the digitizing institution, the logged in content provider should be added as uploader.

**Comment by mindcatch-com** [comment]
please provide examples, the field is not empty now in my test cases

e.g.
mods:recordContentSourceVXG/mods:recordContentSource

what notation do you want instead of VXG ?

VXG, NBGB ?

or do you only  want PI to add the node if missing?

no matter what variante you want i need the definition of the data which should be written in this element.
select it from users table or ...

@wkollernhm 
@heimor

**Comment by wkollernhm** [comment]
If the mods:recordContentSource field already contains the logged in content provider, no change is required. If the mods:recordContent does not exist or contains an entry which is not equal to the content provider login, add a new field with the login data.

Logged in content provider refers to the provider-token preference in upper case.

**Comment by mindcatch-com** [comment]
an additional new field or a replacement for the field with the wrong or missing data ?

@wkollernhm
@heimor

**Comment by wkollernhm** [comment]
See my second comment:

mods:recordContentSource contains logged in CP => no change
mods:recordContentSource does not exist or contains entry different from logged in cp: => add field

**Comment by mindcatch-com** [comment]
done.

**Comment by wkollernhm** [comment]
The mods:recordContentSource is outside the mods:recordInfo tag, which is invalid. Please refer to http://www.loc.gov/standards/mods/v3/mods-userguide-elements.html#recordinfo for details on this element.

**Comment by mindcatch-com** [comment]
element found right place.

**Comment by wkollernhm** [comment]
Logged in content provider is correctly added on all levels.
