### ISSUE TITLE
1.1.6 - Search with special characters (Simple Search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#38]
Updated description:
Special characters, not diacritics, shall be treated as regular characters. Some examples: !"§$%&/()=?+*#'-.,_:;^°~<>|
Special characters shall not interfere with the system.

Previous description:
Search with diacritic marks, e.g. ´, `, ^

Related bug #197

**Comment by akohlbecker** [comment]
A diacritical mark is an ancillary glyph added to a letter, theses are only a limited subset of the special characters. The title of this ticket requests for the ability to search using special characters. What are special characters, unfortunately the only really comprehensive wikipedia article this topic is written in German: http://de.wikipedia.org/wiki/Sonderzeichen

Some examples: !"§$%&/()=?+*#'-.,_:;^°~<>|

**Comment by janahoffmann** [comment]
ready for testing

**Comment by JiriFrank** [comment]
This is a simple search option.

Bug: Search with special words is working but in the results are also these words without diacritic or just part of that word with complete different meaning. In that case the result is not what the user expected.

Is there an option search the exact word, for example “Král“(King)? In this case I have 10 books in result, but none of them includes “Král“, but just Kral with different meaning.

**Comment by JiriFrank** [comment]
Testing of feature 1.1.6 - Search with special characters

Feature description from the Catalogue of user requirements:

Search with diacritic marks, e.g. ´, `, ^

Testers:
@AntonioGVH
@fwelter
@heimor
@janahoffmann
@JFTester
@JiriFrank
@LarissaS

**Comment by JiriFrank** [comment]
Testing of feature 1.1.6 - Search with special characters

Feature description from the Catalogue of user requirements:

Search with diacritic marks, e.g. ´, `, ^

Testers:
@fwelter

**Comment by akohlbecker** [comment]
Hi Jiri, the original description from the catalogue of user requirements is misleading - see my comment ( https://github.com/bhle/bhle/issues/38#issuecomment-1431016 ). Jana, could you please fix the description in the catalogue of user requirements?

**Comment by JiriFrank** [comment]
Hi Adreas, 

thank you. I will test also the special characters which you mentioned in your comment. Anyway new bug with diacritic due to this issue appeared, see my first comment. 

Cheers,
Jiri

Test results

Special character as !?()/+- reporting error and need to be used in combination with quotes. The error screen need to be replaced for example by information that it is necessary to use the quotes or give automatically no results. Others special characters are working properly.

**Comment by LarissaS** [comment]
Testing of feature 1.1.6 - Search with special characters

Searching for “N’Zau” and “Nzau” gives same result (2 records from RMCA)

Searching for “crâne” gives 5 records and includes as well French “crâne” (scull) as the name Crane

Searching for "tête" and "tete" give same result - 13 records all in French

So,  this function looks ok !

-----Original Message-----

**Comment by fwelter** [comment]
1.1.6     special characters

,
- results:
  1. Oberösterreichisches Landesmuseum (1187)
  2. NCB Naturalis (18)
  3. Consejo Superior de Investigaciones Científicas (1)
  4. Helsingin yliopisto (1)
  5. Royal Botanic Garden Edinburgh (1)
- searching for a comma alone is a nonsense result, but not all data
  providers seem to return hits. I guess in almost all titles a comma is
  contained somewhere.

.
- results:
  1. Oberösterreichisches Landesmuseum (141)
  2. NCB Naturalis (44)
- searching for a full stop returns results, but only for some titles.

(
- error 400

"("
- results:
  1. NCB Naturalis (38)
  2. Oberösterreichisches Landesmuseum (7)
- hard to understand, should be many more titles

")"
- results:
  1. Oberösterreichisches Landesmuseum (8)
  2. NCB Naturalis (6)

# 
- results:
  1. NCB Naturalis (98)
  2. Oberösterreichisches Landesmuseum (55)

&
- results:
  1. NCB Naturalis (546)
  2. Oberösterreichisches Landesmuseum (127)
  3. Royal Museum for Central Africa (8)
  4. Helsingin yliopisto (4)

/
- error 400

"/"
- error 400

"
- error 400

""
- no results

"a*
- error 400

"d'un nouveau genre
- returns error 400

"d'un nouveau genre"
- returns 1 result (d'un nouveau genre)

"l'afrique"
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 7 + 5 + 3. 
- of these, search term found in title (and displayed yellow): 5

l'afrique
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 7 + 5 + 3. 
- of these, search term found in title (and displayed yellow): 5

lafrique
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 7 + 5 + 3.
- same results as for l'afrique

l'''''afrique
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 7 + 5 + 3.
- same results as for l'afrique

"de l'afrique"
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 5 + 5 + 3.

"de lafrique"
- no results

"l'afrique maroc"
- 2 results finding l'Afrique (Maroc

"lafrique maroc"
- 2 results finding l'Afrique (Maroc  - but not marked in yellow!

" lafrique maroc"
- 2 results finding l'Afrique (Maroc  - but not marked in yellow!

"de lafrique maroc"
- no results

"de l'afrique maroc"
- 2 results finding l'Afrique (Maroc  

"(heteroptera,"
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 130 + 58. 
- returns also results for 
  (Heteroptera:
  : Heteroptera)
  (Heteroptera)
- searching for heteroptera alone without ( and , yielded exactly the
  same 130 + 58 results.

basalt?
- 3 results (among these was 1 result that had Basalt? in the title, 2
  others has Basalt. in the title)

"basalt?"
- the number of hits was not indicated, you have to count "Data
  Provider" (or "Rights"): 9 + 6 + 6. 

the program largely ignored special characters, but did not skip them
totally. Exact finding of special characters was not possible. in some
cases not putting the ' yielded curiously different results.

22eme
- 1 result (22ème)

22em
- no result

---
- when there were many results the page took long time to load in and
  blocked the mouse of my computer. this was because all the thumbnails
  needed to load in. it seems that also those thumbnails needed to load
  in that were not displayed on the screen. if I had installed to
  display 25 results in the hitlist and there were 1500 results the
  thumnails for all 1500 results loaded in. after that the computer was
  largely blocked and very slow, I tried to close the window as soon as
  possible and I also tried not to select search terms that produced so
  many results.
- nowhere was displayed how many titles were found in total, usually I
  listed the numbers given for data providers. only maximum 5 data
  providers were shown, I discovered this bug only very late in the
  testing process.
- it is also possible that Date, Language and the other facet lists
  had also restrictions for 5 lines to be shown only. I realised this
  only after 2 weeks testing.
- the big problem was that too many results were shown, mainly for two
  reasons:

1 - the result lists generally displayed titles where none of the
words were contained in the title, author or year, but in the text of
the abstract and notes of the item page. 

2 - single journal volumes were displayed for serial runs, they
blocked all intelligent search attempts and spammed the results list
with over and over the same journal title. 
- it was generally very difficult (better say, practically impossible)
  to test for completeness of results. restricting search for (1) only
  in title, author and date and (2) exclude journal metadata of single
  journal volume item pages (and instead create one single journal title
  hit) would probably solve the problems.

Francisco

---

F. Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536, Fax +49 551 395579
http://www.gwdg.de/~fwelter
http://www.animalbase.org

**Comment by akohlbecker** [comment]
searching with diacritic marks works by now, but searching for special characters is not really an option since we are using. Solr usually only indexes letters and numbers. special characters are always ignored except those which are part of the query syntax, these have to be stripped out:  #247

So I am closing this issue as fixed.

**Comment by chris-sleep** [comment]
special characters are now stripped from the index and searching

**Comment by JiriFrank** [comment]
1.1.6 - Search with special characters (Simple Search)

COR number: 1.1.6
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search, Advanced search

Description:

Special characters, not diacritics, shall be treated as regular characters. Some examples: !"§$%&/()=?+*#'-.,_:;^°~<>|

Special characters shall not interfere with the system.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by RalfH** [comment]
There are certain problems. 

Hyphens work well; results are even given if you omit them. That's fine.

When searching "(Anthropomorphae):" no results are given but it may refer to a general problem because even "Anthropomorphae" is not found by simple search.

By the way: If you start typing with an ( in simple search you receive the attached note. It may be of interest for you.

-----Ursprngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:39
An: Hand, Ralf
Betreff: Re: [bhle] 1.1.6 - Search with special characters (Simple Search) (#38)

1.1.6 - Search with special characters (Simple Search)

COR number: 1.1.6
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search, Advanced search

Description:

Special characters, not diacritics, shall be treated as regular characters. Some examples: !"$%&/()=?+*#'-.,_:;^~<>|

Special characters shall not interfere with the system.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AnneSch** [comment]
Works fine with accents. 
Only a little remark: I looked for "L'etat independant", but it was not found, because it was not written like that, but "Letat". Same with "dequateurville", which is originally "d'Equateurville". 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:39
An: Scholz, Annemarie
Betreff: Re: [bhle] 1.1.6 - Search with special characters (Simple Search) (#38)

1.1.6 - Search with special characters (Simple Search)

COR number: 1.1.6
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search, Advanced search

Description:

Special characters, not diacritics, shall be treated as regular characters. Some examples: !"§$%&/()=?+*#'-.,_:;^°~<>|

Special characters shall not interfere with the system.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment]
Have all the apostrophes, for example, been removed from the system at the data ingest stage.  I tried a similar search to the one Anne did, using l'Atlantique as an example.  A simple search set to Title field for "l'Atlantique" retrieves no results, whilst a simple search set to Title field for "lAtlantique" retrieves one result... This is confusing for me.  

Graham

Just noted Andreas' comment above, about the way Solr indexes.  Important to instruct users that they should remove special characters from search terms that contain them. Not something someone would do intuitively.

**Comment by HenningScholz** [comment]
Not working in all cases: searching for "(Anthropomorphae): " gives not result and I can not even find  "Anthropomorphae". Entering in the simple search gives sometimes an error message in a pop up window (Ajax http error code 500). "botaniker," is working.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 13:38
An: Scholz, Henning
Betreff: Re: [bhle] 1.1.6 - Search with special characters (Simple Search) (#38)

1.1.6 - Search with special characters (Simple Search)

COR number: 1.1.6
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search, Advanced search

Description:

Special characters, not diacritics, shall be treated as regular characters. Some examples: !"$%&/()=?+*#'-.,_:;^~<>|

Special characters shall not interfere with the system.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---
