### ISSUE TITLE
1.1.7 - Search with truncated terms (now Advanced Search 1.2.15)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#39]
Search with truncated terms at the beginning and at the end using wildcards, e.g. `*volution`, `evol*` 

Related bug #178, #289

Connected issue: #56

**Comment by janahoffmann** [comment]
ready for testing

**Comment by janahoffmann** [comment]
Search for "phyto_" give results for all terms beginning with phyto- - o.k.
use of "_" is required and needs to be explained (to user) - see advanced search 3 explanations

There is no function that allows search with truncated terms without wildcard options!

Does not work for truncation at the beginning - as discussed in Tervuren - bug!

**Comment by JiriFrank** [comment]
This is a simple search function. For truncated terms is necessary use the symbol star "*".

Tested Cephalopoda
Cephalopoda – 9 results
Cepha\* - 0 results - bug
Cephalo\* - about 100
Cephalop\* - 0 results - bug
Cephalopo\* - 0 results - bug
*phalopoda – error – bug

This function doesn’t work properly. 
Bug: Searching with truncated terms at the end works just in specific length of searched word.
Bug: Searching with truncated terms at the beginning doesn’t work.

**Comment by JiriFrank** [comment]
Testing of feature 1.1.7 - Search with truncated terms

Feature description from the Catalogue of user requirements:

Search with truncated terms at the beginning and at the end, e.g. ‘volution’, ‘evol’ 

Testers:
@AntonioGVH
@fwelter
@heimor
@janahoffmann
@JFTester
@JiriFrank
@LarissaS

**Comment by JiriFrank** [comment]
Testing of feature 1.1.7 - Search with truncated terms

Feature description from the Catalogue of user requirements:

Search with truncated terms at the beginning and at the end, e.g. ‘volution’, ‘evol’

Testers:
@fwelter

**Comment by LarissaS** [comment]
Testing of feature 1.1.7 - Search with truncated terms
This function does not work properly.
Searching for "ichthyologique" gives 3 records
"ichthyo_" - 38
"icht_" - 43
"ichthyolog*" - 24
So, this looks ok

Searching for "zoogdieren" gives 8 results from Naturalis 
"*dieren" - error!
"dieren" - 37

Searching with Advanced search 2 and 3: "crustacea" - 291
"crustac_" - 323
" crus_" - 339
Looks OK

Searching with truncation in front of the word gives always error

-----Original Message-----

**Comment by AntonioGVH** [comment]
Using the example in the manual, I get:
- queriing by 'evolution' many results
- queriing bay 'evo' 0 results
- queriing by 'evolu' I get 4 results that include key words like 'evolué', 'evolution' and 'l'evolution'
- queriing by 'volution' I get 1 results with the key word 'volutes' (that has nothing to do with evolution)

As an additional comment, I think that this test should be have done on in two steps:
a) first, on a selected set of works with a very diversified set of words and characters
b) then, on a wider, but somewhat controlled set.

Unless one knows what is expected by a query,  (eg, 3 books if one ask for 'ticks'), it is impossible to know if the query system works.

Antonio

Quoting JiriFrank:

**Comment by fwelter** [comment]
1.1.7   truncated terms

cephalop*
- results:
  1. NCB Naturalis (20)
  2. Oberösterreichisches Landesmuseum (12)
  3. Consejo Superior de Investigaciones Científicas (1)

finnla*
- results:
  1. Helsingin yliopisto (20)
  2. Oberösterreichisches Landesmuseum (3)

"mantides du muse"
- returns 1 result (mantides du Musée)

"mantides du mus"
- no result

"antides du muse"
- no result 
- this would have given a result in the current BHL default search
  (this is the "elle des mo" mode of search, to find histoire naturelle
  des mollusques)

"mantide du muse"
- returns 1 result (mantides du Musée)

"mantide du muse*"
- returns 1 result (mantides du Musée)

"mantide du mus*"
- no result

"*antides du muse"
- no result

"mantid\* du muse"
- returns 1 result (mantides du Musée)

"manti\* du muse"
- no result

antide
- no result

*antide
- no result

manti*
- the number of hits was not indicated, you have to count "Data
  Provider" (or "Rights"): 24 + 4 + 1. 

mantid*
- the number of hits was not indicated, you have to count "Data
  Provider" (or "Rights"): 11 + 1. 

mantida*
- 5 results

mantidae
- 5 results

mantidaes
- 5 results

mantidas
- 5 results

*antidae
- error 400

*antida
- error 400

_antid_
- error 400

*usee
- error 400

manti\* mus*
- the number of hits was not indicated, you have to count "Data
  Provider" (or "Rights"): 902 + 809 + 102 + 61 + 35
  1. NCB Naturalis (902)
  2. Oberösterreichisches Landesmuseum (809)
  3. Royal Museum for Central Africa (102)
  4. UB der Humboldt-Universität, Zweigbibliothek Museum für
     Naturkunde (61) 5. Universitätsbibliothek Bielefeld (35)
- clicking on these gave the following results:

899 hits:     manti\* mus\* AND europeana_dataProvider__facet:"NCB
Naturalis" 795 hits:     manti\* mus\* AND
europeana_dataProvider__facet:"Oberösterreichisches Landesmuseum" 102
hits:     manti\* mus\* AND europeana_dataProvider__facet:"Royal Museum
for Central Africa"
 61 hits:     manti\* mus\* AND europeana_dataProvider__facet:"UB der
 Humboldt-Universität, Zweigbibliothek Museum für Naturkunde" 35 hits:
     manti\* mus\* AND
 europeana_dataProvider__facet:"Universitätsbibliothek Bielefeld"

"22eme note"
- 1 result (22ème note)

hepialidae
- the number of hits was not indicated, you have to count "Data
  Provider" (or "Rights"): 5 + 4. 

hepialida
- the number of hits was not indicated, you have to count "Data
  Provider" (or "Rights"): 5 + 4. 

hepialid
- 2 results (at least one for the word hepialid)

hepiali
- no results

hepiali*
- the number of hits was not indicated, you have to count "Data
  Provider" (or "Rights"): 5 + 5. 
- clicking on the data provider brought the following results:
  5 hits:      hepiali\* 22eme AND
  europeana_dataProvider__facet:"Oberösterreichisches Landesmuseum" 5
  hits:      hepiali\* 22eme AND europeana_dataProvider__facet:"NCB
  Naturalis"

22eme
- 1 result

hepiali\* 22eme
- the number of hits was not indicated, you have to count "Data
  Provider" (or "Rights"): 5 + 5. 
- clicking on the data provider brought the following results:
  0 hits:      hepiali\* 22eme AND
  europeana_dataProvider__facet:"Oberösterreichisches Landesmuseum" 1
  hit:       hepiali\* 22eme AND europeana_dataProvider__facet:"NCB
  Naturalis"

*epialidae
- error 400

*2eme
- error 400

verteb*
- results:
  1. NCB Naturalis (59)
  2. Oberösterreichisches Landesmuseum (17)
  3. Royal Museum for Central Africa (2)
  4. UB der Humboldt-Universität, Zweigbibliothek Museum für
     Naturkunde (2)

verte*
- results:
  1. NCB Naturalis (102)
  2. Oberösterreichisches Landesmuseum (55)
  3. Royal Museum for Central Africa (2)
  4. UB der Humboldt-Universität, Zweigbibliothek Museum für
     Naturkunde (2) 5. Helsingin yliopisto (1)

vert*
- results:
  1. NCB Naturalis (208)
  2. Oberösterreichisches Landesmuseum (103)
  3. Universitätsbibliothek Bielefeld (5)
  4. Helsingin yliopisto (2)
  5. Royal Museum for Central Africa (2)

ver*
- results:
  1. Oberösterreichisches Landesmuseum (1831)
  2. NCB Naturalis (1681)
  3. Universitätsbibliothek Bielefeld (240)
  4. University of Copenhagen (28)
  5. Helsingin yliopisto (16)
- only 5 data providers were shown! the others were not shown.

---
- when there were many results the page took long time to load in and
  blocked the mouse of my computer. this was because all the thumbnails
  needed to load in. it seems that also those thumbnails needed to load
  in that were not displayed on the screen. if I had installed to
  display 25 results in the hitlist and there were 1500 results the
  thumnails for all 1500 results loaded in. after that the computer was
  largely blocked and very slow, I tried to close the window as soon as
  possible and I also tried not to select search terms that produced so
  many results.
- nowhere was displayed how many titles were found in total, usually I
  listed the numbers given for data providers. only maximum 5 data
  providers were shown, I discovered this bug only very late in the
  testing process.
- it is also possible that Date, Language and the other facet lists
  had also restrictions for 5 lines to be shown only. I realised this
  only after 2 weeks testing.
- the big problem was that too many results were shown, mainly for two
  reasons:

1 - the result lists generally displayed titles where none of the
words were contained in the title, author or year, but in the text of
the abstract and notes of the item page. 

2 - single journal volumes were displayed for serial runs, they
blocked all intelligent search attempts and spammed the results list
with over and over the same journal title. 
- it was generally very difficult (better say, practically impossible)
  to test for completeness of results. restricting search for (1) only
  in title, author and date and (2) exclude journal metadata of single
  journal volume item pages (and instead create one single journal title
  hit) would probably solve the problems.

Francisco

---

F. Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536, Fax +49 551 395579
http://www.gwdg.de/~fwelter
http://www.animalbase.org

**Comment by akohlbecker** [comment]
#191 is unresolved special case which is related to this issue!

**Comment by JiriFrank** [comment]
1.1.7 - Search with truncated terms (now Advanced Search 1.2.15)

COR number: 1.2.15
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search, Advanced search

Description:

Search with truncated terms at the beginning and at the end using wildcards, e.g. `*volution`, `evol*`

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by RalfH** [comment]
It works but I found the following problem:

If you search Lyhykaeinen (part of a title) instead of Lyhykäinen it works but the combination with \* (i.e. Lyhykaeine_) results in no results. Lyhykäine_ works. Obviously, the combination of diacritic letter alternatives and wildcard seems to be problematic (in simple and advanced).

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:46
An: Hand, Ralf
Betreff: Re: [bhle] 1.1.7 - Search with truncated terms (now Advanced Search 1.2.15) (#39)

1.1.7 - Search with truncated terms (now Advanced Search 1.2.15)

COR number: 1.2.15
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search, Advanced search

Description:

Search with truncated terms at the beginning and at the end using wildcards, e.g. `*volution`, `evol*`

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
1.1.7 - Search with truncated terms (now Advanced Search 1.2.15)

COR number: 1.2.15
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search, Advanced search

Description:

Search with truncated terms at the beginning and at the end using wildcards, e.g. `*volution`, `evol*`

@AntonioGVH
@fwelter
@LarissaS

**Comment by LarissaS** [comment]
Works good

-----Original Message-----

**Comment by HenningScholz** [comment]
This seems to work. Interesting: while Anthropomorphae is not working, Anthro\* is working to give the result.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 13:45
An: Scholz, Henning
Betreff: Re: [bhle] 1.1.7 - Search with truncated terms (now Advanced Search 1.2.15) (#39)

1.1.7 - Search with truncated terms (now Advanced Search 1.2.15)

COR number: 1.2.15
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search, Advanced search

Description:

Search with truncated terms at the beginning and at the end using wildcards, e.g. `*volution`, `evol*`

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AnneSch** [comment]
Works fine. 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:46
An: Scholz, Annemarie
Betreff: Re: [bhle] 1.1.7 - Search with truncated terms (now Advanced Search 1.2.15) (#39)

1.1.7 - Search with truncated terms (now Advanced Search 1.2.15)

COR number: 1.2.15
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search, Advanced search

Description:

Search with truncated terms at the beginning and at the end using wildcards, e.g. `*volution`, `evol*`

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
The basic functionality is done. One bug for special cases needs to be fixed.

Related bug Issue #289
@chris-sleep

**Comment by JiriFrank** [comment]
Ready for testing.

**Comment by JiriFrank** [comment]
1.1.7 - Search with truncated terms (now Advanced Search 1.2.15)

COR number: 1.2.15
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search, Advanced search

Description:

Search with truncated terms at the beginning and at the end using wildcards, e.g. `*volution`, `evol*` 

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
1.1.7 - Search with truncated terms (now Advanced Search 1.2.15)

COR number: 1.2.15
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search, Advanced search

Description:

Search with truncated terms at the beginning and at the end using wildcards, e.g. `*volution`, `evol*` 

---

@GregKenicer
@GeoffHarper
@KasiaGoral
@MartinaMetzger
@DanielFisher
@NeilWoodcock
@SaraPerzley
@SaraCarlton
@HannaKoivula
@PaiviLipsanen

**Comment by JiriFrank** [comment]
1.1.7 - Search with truncated terms (now Advanced Search 1.2.15)

COR number: 1.2.15
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search, Advanced search

Description:

Search with truncated terms at the beginning and at the end using wildcards, e.g. `*volution`, `evol*` 

---

@PaiviJaakkola
@SiniKarki
@TiinaOnttonen

**Comment by GeoffHarper** [comment]
(1) I started by typing 'Plantas medicinales de Filipinas' in Advanced Search, and got a negative result; but I see that Advanced Search doesn't offer a title-only option, so I then tried the same title in Simple Search, and also got a negative result.
(2) Simple Search offers as an alternative 'plantes originales deel Filipinas', but when that is chosen the search result is still negative.
(3) All that is by way of trying to find a title which does give a search result, before using '_' on a missing part of a word. So now I'll try 'Les Arachnides de France' in Simple Search; but it too gives a negative result, while also offering 'keys arachneides deel France' (with acute accent on 'e' in 'arachneides'); again, search result negative.
(4) If I can't get the Search facility to work at all, I can't test the wildcards.
(5) Last attempt: I searched '_schenaffen' in Advanced Search (for 'Menschenaffen') with only 'title' ticked, and the result was negative.
(6) I am getting the impression that nothing is working with Internet Explorer 9. I'll take a break now, then must make some observations in the Garden, but I should be able to spend another hour on it later this morning.
(7) By the way I am using apostrophes (') in these messages to name words, symbols, &c, and I'm not typing them into the search box.
Geoff

-----Original Message-----

**Comment by tiinaonttonen** [comment]
System: Windows 7 Enterprise 6.1 (Build 7601: SP 1)
Browser: Firefox 10.0.3

Simple search, default ticks: land*

5 results, including "Guide de la section de l'Etat" and "Bibliografía de la fauna de Guinea Ecuatorial" which both include la ....n... de

char\* 7 results, including "´Bibliografía de la fauna de Guinea Ecuatorial" by "Museo Nacional de Ciencias Naturales, CSIC"

The fuzzy search may bring too many results to be practical when there will be lots of stuff (unless it works differently when there are more results?)

Ûbe\* - no results (but when typing "übe" the search suggests  "did you mean ûber", so the word would be found)

Ube\* two results, both include ûber or Ûber

*cional 4 results
*nde's 3 results

Generally, seems to work well.

**Comment by GeoffHarper** [comment]
Hi Jiri
  In Advanced Search I've tried 'uber die unter' (negative result), 'uber die unter_' (positive result) and '_ber die unter*' (positive result). So the wildcard seems to work OK.

(Now that I'm getting the hang of it, I wish I could continue, but I have no more time. My apologies. I hope other testers here will be more efficient than I've been!. Best of luck with the project.)

  Geoff

-----Original Message-----

**Comment by HenningScholz** [comment]
This is interesting, using one search string without \* does not work, putting the \* in front of the search term, does not work, but the _at the end of the search string, does work, e.g. *be - no; be_ - yes, be - no.

sometimes it also needs two _, e.g. *werp_, to find anything.

this feature seems to work a bit inconsistently. when I search for be\* and find uber, I should find antwerpsche as well when I search werp\* -  not the case....

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Do 12.04.2012 17:27
An: Scholz, Henning
Betreff: Re: [bhle] 1.1.7 - Search with truncated terms (now Advanced Search 1.2.15) (#39)

1.1.7 - Search with truncated terms (now Advanced Search 1.2.15)

COR number: 1.2.15
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search, Advanced search

Description:

Search with truncated terms at the beginning and at the end using wildcards, e.g. `*volution`, `evol*`

---

Testers:
@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamtestrbge** [comment]
Worked searching for "_rande" and "geogn_" also "_minees" and "gramin_" So on balance it works

**Comment by LarissaS** [comment]
Sorry for starting late!
I am working with Mozilla Firefox.
1. Searching for "belg'" I get proposal from auto complete function "Belgium" - 4 results, "belgique" - 3 results. Choosing first one give me indeed 4 results: two where Belgique is in the title and two where I could not find any word with "belg". Choosing second one give me 0 results! Ignoring auto completion give me 0 results. 
2. Searching for " 'unio" gives 1 result where no word "unio" to find!, while searching for "reuni' " autocomplete it until Réunion and gives one good result from Vinson.
3. searching for "cham' " or "ois' " worked correct

-----Original Message-----

**Comment by KasiaGoral** [comment]
Searched for:
1. 'Uni\* of Edin*'

(University of Edinburgh)
- Error 400
1. 'hort*'
- No result

(Horticulture)
1. 'libr*'
- No result

(Library)

**Comment by KasiaGoral** [comment]
Sorry, misunderstood this task as well and searched for words not in the
current book list.

This time searched for:

'Les oise\* utiles'
No result.

'Les oisea\* utiles'
No result.

Even 'Les oisea\* utiles' gives no result.

**Comment by JiriFrank** [comment]
Ready for close.
