### ISSUE TITLE
1.1.8 - Search in all or one specific main search category (Simple Search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#40]
Updated description:
Search in main categories: author, title/ journal title, year, taxon. Select specific categories (check box).

Precondition: Predefine metadata fields as main search category, integration of uBio.

Previous description:
Categories: author, titles, year, (journal title)

Precondition; defined metadata fields as main search category
reported bug #168

**Comment by JiriFrank** [comment]
It is not implemented in simple search yet, but it is the the options (look&feel) of Advance search 2 but needs to be restricted to the main three (or four) categories.

**Comment by janahoffmann** [comment]
This functionality needs also to be implemented as Simple Search functionality, not only Advanced Search. In simple search it needs to be restricted to the identified main search categories (metadata fields): title, author, year and maybe journal title.

**Comment by JiriFrank** [comment]
Testing of feature 1.1.8 - Search in all or one specific main search category

Feature description from the Catalogue of user requirements:

Categories: author, titles, year, (journal title)

Precondition; defined metadata fields as main search category

Testers:
@AntonioGVH
@fwelter
@heimor
@janahoffmann
@JFTester
@JiriFrank
@LarissaS

**Comment by JiriFrank** [comment]
Testing of feature 1.1.8 - Search in all or one specific main search category

Feature description from the Catalogue of user requirements:

Categories: author, titles, year, (journal title)

Precondition; defined metadata fields as main search category

Testers:
@fwelter

**Comment by LarissaS** [comment]
Testing of feature 1.1.8 - Search in all or one specific main search category

I do not understand well, is it simple search function? Where can I define metadata field? I only see possibility to look for example for Boulenger and then sort by creator. 

-----Original Message-----

**Comment by AntonioGVH** [comment]
There are no specific fields for authors or year in the portal. 
What is closer to 'author' is 'contributor' in advance search.
Queriing by 'Valdecasas' and selecting 'contributor', one gets the two work in the data base (apparently there are only two). And Valdecasas is author for both (I apologize for using myself as a querying example).
Queriing by 'Darwin' and 'contributor' one gets works that have Darwin in the title of the work but for which Darwin was not the author.

I do not find interesting to have several kinds of 'advance search'. It would be better to have one option to 'advance searh and then several options in the same page (as is usual).

Antonio

Quoting JiriFrank:

**Comment by fwelter** [comment]
1.1.8   categories (author, year, title)

the feature is not installed in the simple search version. I can only
sort by title, creator and date, but not specify in the search
function that I like to look for author-only, year-only etc.

there is a clickable feature "Browse" and there I can select between
Browse by Title A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
Browse by Author A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
Browse by Year 1850 1870 1890 1910 1930 1950 1970 1990 2010 

but there is no search function installed to search for a certain
author name or year.

browsing for year

clicking on 1930 
- gave 163 results, all from Oberösterreichisches Landesmuseum
- after that you have to ckick again on "Browse" and select again
  something.

clicking on 1870
- gave the following results:
  1. Oberösterreichisches Landesmuseum (168)
  2. UB der Humboldt-Universität, Zweigbibliothek Museum für
     Naturkunde (10)
- Type:
  1. Text (178)
  2. Books, Monographs (10)
  3. book (10)
- clicking on 2. Books, Monographs and 3. book gave exactly the same
  results.
- clicking in Data Provider 2. UB der Humboldt-Universität,
  Zweigbibliothek Museum für Naturkunde gave 10 results. on that page
  the following information was displayed under the title "Type":
  1. Books, Monographs (10)
  2. Text (10)
  3. book (10)
- clicking on these gave again repeatedly the same 10 results

clicking on all other years 
- gave always only results for these two data providers:
  Oberösterreichisches Landesmuseum 
  UB der Humboldt-Universität, Zweigbibliothek Museum für Naturkunde

browse by title

S
- gave the following results:
  1. NCB Naturalis (639)
  2. Oberösterreichisches Landesmuseum (171)
  3. Universitätsbibliothek Bielefeld (46)
  4. University of Copenhagen (28)
  5. Helsingin yliopisto (16)
- clicking on the Data Provider gave no hits in all 5 cases
- Language
  1. Primarily danish, some abstracts in english (28)
  2. dk (28)
  3. en (28)
  4. ger (16)
  5. fin (14)
- clicking on the Language gave no hits in all 5 cases
- clicking on the displayed results for "Type" and "Date" gave also no
  results in all tested cases.

browse by author

M
- gave the following results:
  1. NCB Naturalis (294)
  2. Universitätsbibliothek Bielefeld (139)
  3. Oberösterreichisches Landesmuseum (41)
  4. UB der Humboldt-Universität, Zweigbibliothek Museum für
     Naturkunde (1)
- clicking on Data Provider, Type, Date and Language gave no results
  in all tested cases

Advanced Search 2

dc_creator:miller
- results: 
  1. Oberösterreichisches Landesmuseum (22)
  2. NCB Naturalis (3)

simple search vinson
- results:
  Royal Museum for Central Africa (2)
- vinson was the name of the author of these 2 publications

dc_creator:vinson
- no results 

simple search modeer
- 3 results:
  Universitätsbibliothek Bielefeld (3)

dc_creator:modeer
- 3 results:
  Universitätsbibliothek Bielefeld (3)

dc_creator:schmidt
- results:
  1. Oberösterreichisches Landesmuseum (66)
  2. NCB Naturalis (1)
  3. Universitätsbibliothek Bielefeld (1)

dc_creator:linne
- results: 
  UB der Humboldt-Universität, Zweigbibliothek Museum für Naturkunde
  (12)

simple search palmgren
- results:
  Helsingin yliopisto (18)

dc_creator:palmgren
- no results   (should have been 18 results in Helsingin yliopisto)

dc_creator:becerra
- no results  (should have been 1 result in Consejo Superior de
  Investigaciones Científicas)

dc_creator:albal*
- no results  (should have been 1 result in Consejo Superior de
  Investigaciones Científicas)

dc_creator

works yes in:
UB der Humboldt-Universität, Zweigbibliothek Museum für Naturkunde NCB
Naturalis Oberösterreichisches Landesmuseum Universitätsbibliothek
Bielefeld

works not in: 
Royal Museum for Central Africa
Helsingin yliopisto
Consejo Superior de Investigaciones Científicas
Royal Botanic Garden Edinburgh

because it is dc_contributor there!

dc_contributor:albal*
- 1 result (correct)

dc_contributor:a*
- results:
  1. Royal Museum for Central Africa (94)
  2. Helsingin yliopisto (17)
  3. Royal Botanic Garden Edinburgh (12)
  4. Consejo Superior de Investigaciones Científicas (6)
  5. NCB Naturalis (3)
- the 3 NCB Naturalis authors were also found when I searched in
  dc_creator

dc_title:uber
- results:
  1. Universitätsbibliothek Bielefeld (188)
  2. NCB Naturalis (24)
  3. Royal Museum for Central Africa (6)

dc_title:systema
- results:
  UB der Humboldt-Universität, Zweigbibliothek Museum für Naturkunde
  (12)

dc_title:svampe
- results:  
  University of Copenhagen (28)

dc_title seems to work everywhere

for the date see the results under 1.2.2

---
- when there were many results the page took long time to load in and
  blocked the mouse of my computer. this was because all the thumbnails
  needed to load in. it seems that also those thumbnails needed to load
  in that were not displayed on the screen. if I had installed to
  display 25 results in the hitlist and there were 1500 results the
  thumnails for all 1500 results loaded in. after that the computer was
  largely blocked and very slow, I tried to close the window as soon as
  possible and I also tried not to select search terms that produced so
  many results.
- nowhere was displayed how many titles were found in total, usually I
  listed the numbers given for data providers. only maximum 5 data
  providers were shown, I discovered this bug only very late in the
  testing process.
- it is also possible that Date, Language and the other facet lists
  had also restrictions for 5 lines to be shown only. I realised this
  only after 2 weeks testing.
- the big problem was that too many results were shown, mainly for two
  reasons:

1 - the result lists generally displayed titles where none of the
words were contained in the title, author or year, but in the text of
the abstract and notes of the item page. 

2 - single journal volumes were displayed for serial runs, they
blocked all intelligent search attempts and spammed the results list
with over and over the same journal title. 
- it was generally very difficult (better say, practically impossible)
  to test for completeness of results. restricting search for (1) only
  in title, author and date and (2) exclude journal metadata of single
  journal volume item pages (and instead create one single journal title
  hit) would probably solve the problems.

Francisco

---

F. Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536, Fax +49 551 395579
http://www.gwdg.de/~fwelter
http://www.animalbase.org

**Comment by JiriFrank** [comment]
1.1.8 - Search in all or one specific main search category (Simple Search)

COR number: 1.1.8
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search

Description:

Search in main categories: author, title/ journal title, year, taxon. Select specific categories (check box).

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by RalfH** [comment]
It works.

But there are problems with the place at least in one (some?) example/s:

Plantas medicinales de Filipinas
Pardo de Tavera, T. H. (Trinidad Hermenegildo), 1857-1925
1892

Combination of 3 fields does not produce results if you search for the place of publication Madrid. It may be a special problem of this title because Madrid is not found if you search for place of publicaton alone. In other cases combinations work.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:47
An: Hand, Ralf
Betreff: Re: [bhle] 1.1.8 - Search in all or one specific main search category (Simple Search) (#40)

1.1.8 - Search in all or one specific main search category (Simple Search)

COR number: 1.1.8
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search

Description:

Search in main categories: author, title/ journal title, year, taxon. Select specific categories (check box).

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment]
This is working for Author only simple search, without any problem. 
For Title only search, the following search combinations are working: first two words from title; key word in title (eg Filipinas); common word in title (eg Flora). 
Single Year search working as expected, eg, 1909 and 1798. The system also retrieves results for a particular year if that appears in the date of publication field as part of a range of years eg 1862- ; -1936; I like this feature.

**Comment by JiriFrank** [comment]
1.1.8 - Search in all or one specific main search category (Simple Search)

COR number: 1.1.8
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search

Description:

Search in main categories: author, title/ journal title, year, taxon. Select specific categories (check box).

@AntonioGVH
@fwelter
@LarissaS

**Comment by LarissaS** [comment]
Works good

-----Original Message-----

**Comment by HenningScholz** [comment]
Works fine.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 13:47
An: Scholz, Henning
Betreff: Re: [bhle] 1.1.8 - Search in all or one specific main search category (Simple Search) (#40)

1.1.8 - Search in all or one specific main search category (Simple Search)

COR number: 1.1.8
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search

Description:

Search in main categories: author, title/ journal title, year, taxon. Select specific categories (check box).

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AnneSch** [comment]
Works fine. 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:47
An: Scholz, Annemarie
Betreff: Re: [bhle] 1.1.8 - Search in all or one specific main search category (Simple Search) (#40)

1.1.8 - Search in all or one specific main search category (Simple Search)

COR number: 1.1.8
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Simple search

Description:

Search in main categories: author, title/ journal title, year, taxon. Select specific categories (check box).

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
Working and ready for close.

@RalfH 
Search for place of publication is possible in Advanced search. In simple search are 4 main most frequently used fields: Title, Author, Year and Scientific name.
