### ISSUE TITLE
gSearch brigde doesn't trigger re-indexing

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#437]
I've just test ingested several uploads from landooe, they went through PI fine, Access picked them up and successfully ingested them. However the index for the portal is not automatically updated. I had to trigger this through the jenkins job.

All the test have been made in the integration environment.

**Comment by zhengl** [comment]
The update of index does take place, but is not committed in Solr after every update according to the current configuration.

If you want to trigger a commit in Solr, you can go the GSearch (http://bhl-int.nhm.ac.uk/fedoragsearch/rest) with username fgsAdmin and click 'browseIndex' (that is treated as a commit), that will flush the updates.

@akohlbecker I think you would have more input for us, about the 'autoCommit' in Solr.

**Comment by akohlbecker** [comment]
The 'autoCommit' feature in solr is disabled, since the recommended way is to use the 'commit' or 'commitWithin' parameters in the query which pushes the new document to solr (http://wiki.apache.org/solr/UpdateXmlMessages#Passing_commit_and_commitWithin_parameters_as_part_of_the_URL). So the best way to solve this issue would be to add `&commit=true` to the gsearch solr update query. If it is not possible to configure gsearch that way we should enable 'autoCommit', and we would have to find sensible settings for the according parameters:

```
<maxDocs>10000</maxDocs>
<maxTime>1000</maxTime> 
```

**Comment by akohlbecker** [comment]
just found this: "Alternatively, you may include a commitWithin attribute in your add element in the index document." - An interesting alternative solution.

**Comment by akohlbecker** [comment]
my suggestion is to add some parameters in  line 55 to the add element the foxmlToSolrDemo.xslt in the
like: 

```
<add overwrite="true" commitWithin="1000" allowDups="false">
```

**Comment by akohlbecker** [comment]
the above fix solves the problem for me locally. @ZhengLIAtos @wkollernhm  can someone of you confirm this on int?

**Comment by zhengl** [comment]
@akohlbecker  Thanks a lot for your input! For _adding_ index, now it works perfectly. Do you think it is also applicable for _deleting_ index in the delete tag?

**Comment by akohlbecker** [comment]
@ZhengLIAtos  it is supported at least in solr 3.6, please see https://issues.apache.org/jira/browse/SOLR-2280 currently we are running 3.5

**Comment by wkollernhm** [comment]
Can confirm that this works, just tried it with another example from landooe!
