### ISSUE TITLE
1.2.2 - Search by year of publication (Advanced search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#45]
Search by exact year of publication, e.g. 1932

Related bug #198

**Comment by JiriFrank** [comment]
Advance search 2 (it will be the main advance search). This function will be also implemented in simple serch option. 
#168 and #22.

**Comment by JiriFrank** [comment]
open for testing

**Comment by JiriFrank** [comment]
Testing of feature 1.2.2 - Search by year of publication

Feature description from the Catalogue of user requirements:

Search by exact year, e.g. 1932

Testers:
@AntonioGVH
@fwelter
@heimor
@janahoffmann
@JFTester
@JiriFrank
@LarissaS

**Comment by JiriFrank** [comment]
Testing of feature 1.2.2 - Search by year of publication

Feature description from the Catalogue of user requirements:

Search by exact year, e.g. 1932

Testers:
@fwelter

**Comment by LarissaS** [comment]
Testing of feature 1.2.2 - Search by year of publication
If I understood well I had to try advanced search and choose somewhere field "year of publication". 

Using Advanced search 1: if I select "searching in only selected fields" I get a small square down where I can not type something or choose something, so I suppose it does not work

Using Advanced search 2: can only see "all fields", no possibility to choose what I am looking for!

Using Advanced search 3: I have used proposed template " specify field to search in:

fieldname:word"

so I tried: 
year of publication: 1900
yearofpublication: 1900
year of publication:1900
yearofpublication:1900
And have got ERROR:

Error
The website encountered an unexpected error. Please try again later. 
Error messageYour search could not be executed. Please enter something else
Exception: "400" Status: undefined_field_publication: undefined_field_publication<html> <head> <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/> <title>Error 400 </title> </head> <body><h2>HTTP ERROR: 400</h2><pre>undefined field publication</pre> <p>RequestURI=/solr/core2/select</p><p><i><small><a href="http://jetty.mortbay.org/">Powered by Jetty://</a></small></i></p><br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/> <br/> </body> </html> in DrupalApacheSolrService->checkResponse() (line 319 of /var/www/drupal/sites/all/modules/additional/apachesolr/Drupal_Apache_Solr_Service.php).

I also tried to search with "date: 1900" and get the same error

Searching in simple search for "1900" I have got 123 records, clicking on DATE (1900) gives 9 results with year of publication 1900.

After Login:

Advanced search 1:
Searching in field DATE "1848" gives one record, the book of Waterhouse (1848) from RMCA collection is not in. I have searched in field ISSUED "1848" and have got this record, but again double!

Control searching in field DATE "1900" gives 10 records, in the detail description 1900 is under the field Date, searching in field ISSUED "1900" gives 5 records, where the date 1900 is in Publication field.
Advanced search 2: the same results
Advanced search 3: does not work

-----Original Message-----

**Comment by LarissaS** [comment]
Testing of feature 1.2.2 - Search by year of publication

Searching with Advanced search 1: 
With all words: 1908 gives 99 matches as well for literature published in 1908 as for texts where 1908 is just mentioned in the bibliographic record.

Searching in exact field with "1908": I was doubting between CREATED and ISSUED, by trying I've got 0 results for first and 6 results for second.

Searching with Advanced search 2: I choose field ISSUAD "1908" and have got same result - 6 records

Conclusion: it is not clear if year of publication corresponds to CREATED or ISSUED field. 

-----Original Message-----

**Comment by LarissaS** [comment]
I am sorry, I just have seen that there is also field DATE and searching with DATE: 1908 gave me 21 result (all from Oberösterreichisches Landesmuseum) but 6 result which I have got with searching be CREATED: 1908 (RMVA, RBGE) are not in. Is it due to difference in metadata fields between different content providers?

-----Original Message-----

**Comment by AntonioGVH** [comment]
Apparently, searching by year gives proper results (but who knows? It would be necessary to know how many works there are in the database for 1994, for instance, to check if the result is correct).

A.

Quoting JiriFrank:

**Comment by fwelter** [comment]
1.2.2   year, Advanced Search 2

Advances Search 2 restored the simple search mode automatically after
each single search

dc_date 1952
- clicking on the lower (main) search button gave error 400
- clicking on the directly associated search button or simply clicking
  return gave results:
   Oberösterreichisches Landesmuseum (9)

dc_date 1921
- Oberösterreichisches Landesmuseum (9)

dc_date 2002
- Oberösterreichisches Landesmuseum (49)

dc_date 2009
- Oberösterreichisches Landesmuseum (103)

When I clicked on the "Date:" results in other searches I only
obtained (very few usually) results from Oberösterreichisches
Landesmuseum, no other data providers

dcterms_issued 1799
- results:
  Universitätsbibliothek Bielefeld (44)

dcterms_issued 2009
- results:
  NCB Naturalis (65)

dcterms_issued 2002
- results:
  NCB Naturalis (77)

dcterms_issued 1952
- results:
  1. NCB Naturalis (14)
  2. Royal Botanic Garden Edinburgh (1)

dcterms_issued 1894
- results:
  Royal Museum for Central Africa (6)

dcterms_issued:1928
- results:
  1. NCB Naturalis (11)
  2. Helsingin yliopisto (4)
  3. Royal Botanic Garden Edinburgh (2)

dcterms_issued:1994
- results:
  1. NCB Naturalis (51)
  2. Consejo Superior de Investigaciones Científicas (2)
  3. Royal Botanic Garden Edinburgh (2)

dcterms_created 2002
- no results, also for years 1952, 1894, 1921

dcterms_created:2009
- results:
  University of Copenhagen (23)

simple search 1799
- results:
  1. Universitätsbibliothek Bielefeld (44)
  2. NCB Naturalis (7)
  3. Oberösterreichisches Landesmuseum (5)

dcterms_issued   1*
- results:
  1. NCB Naturalis (2362)
  2. Universitätsbibliothek Bielefeld (1634)
  3. Royal Botanic Garden Edinburgh (190)
  4. Royal Museum for Central Africa (100)
  5. Helsingin yliopisto (30)
- not displayed in this function:
  Consejo Superior de Investigaciones Científicas

dcterms_created   1\* 
- results:
  University of Copenhagen (23)

dc_date   1*
- results:
  1. Oberösterreichisches Landesmuseum (2578)
  2. UB der Humboldt-Universität, Zweigbibliothek Museum für
     Naturkunde (57)

the date has 3 different fields in Advanced Search 2, this depends on
the Data Provider.

Advanced Search 3

1799
- results:
  1. Universitätsbibliothek Bielefeld (44)
  2. NCB Naturalis (7)
  3. Oberösterreichisches Landesmuseum (5)

1894
- results:
  1. NCB Naturalis (41)
  2. Oberösterreichisches Landesmuseum (32)
  3. Royal Museum for Central Africa (6)
  4. UB der Humboldt-Universität, Zweigbibliothek Museum für
     Naturkunde (1)

1921
- results:
  1. NCB Naturalis (70)
  2. Oberösterreichisches Landesmuseum (26)
  3. Royal Botanic Garden Edinburgh (4)

1952
- results:
  1. NCB Naturalis (64)
  2. Oberösterreichisches Landesmuseum (34)
  3. Royal Botanic Garden Edinburgh (1)

1960
- results:
  1. NCB Naturalis (334)
  2. Oberösterreichisches Landesmuseum (44)
  3. Royal Botanic Garden Edinburgh (1)

2002
- results:
  1. NCB Naturalis (119)
  2. Oberösterreichisches Landesmuseum (69)

2009
- results:
  1. Oberösterreichisches Landesmuseum (105)
  2. NCB Naturalis (70)
  3. University of Copenhagen (23)
  4. Royal Botanic Garden Edinburgh (1)

---
- when there were many results the page took long time to load in and
  blocked the mouse of my computer. this was because all the thumbnails
  needed to load in. it seems that also those thumbnails needed to load
  in that were not displayed on the screen. if I had installed to
  display 25 results in the hitlist and there were 1500 results the
  thumnails for all 1500 results loaded in. after that the computer was
  largely blocked and very slow, I tried to close the window as soon as
  possible and I also tried not to select search terms that produced so
  many results.
- nowhere was displayed how many titles were found in total, usually I
  listed the numbers given for data providers. only maximum 5 data
  providers were shown, I discovered this bug only very late in the
  testing process.
- it is also possible that Date, Language and the other facet lists
  had also restrictions for 5 lines to be shown only. I realised this
  only after 2 weeks testing.
- the big problem was that too many results were shown, mainly for two
  reasons:

1 - the result lists generally displayed titles where none of the
words were contained in the title, author or year, but in the text of
the abstract and notes of the item page. 

2 - single journal volumes were displayed for serial runs, they
blocked all intelligent search attempts and spammed the results list
with over and over the same journal title. 
- it was generally very difficult (better say, practically impossible)
  to test for completeness of results. restricting search for (1) only
  in title, author and date and (2) exclude journal metadata of single
  journal volume item pages (and instead create one single journal title
  hit) would probably solve the problems.

Francisco

---

F. Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536, Fax +49 551 395579
http://www.gwdg.de/~fwelter
http://www.animalbase.org

**Comment by JiriFrank** [comment]
Search by year of publication works just for the LANDOE, UBER and UCPH collections, because they have a field Date. Other collections are not possible search or browse by date. 

The function itself is ready and the problem is probably just in metadata. But without fixing this problem the function is useless.

Related bug is #183.

**Comment by JiriFrank** [comment]
1.2.2 - Search by year of publication (Advanced search)

COR number: 1.2.2
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Simple search

Description:

Search by exact year of publication, e.g. 1900

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by RalfH** [comment]
It works. No critical point found. Even publication periods such as 1879-1882 are indicated, which is very useful.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:56
An: Hand, Ralf
Betreff: Re: [bhle] 1.2.2 - Search by year of publication (Advanced search) (#45)

1.2.2 - Search by year of publication (Advanced search)

COR number: 1.2.2
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Simple search

Description:

Search by exact year of publication, e.g. 1900

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
1.2.2 - Search by year of publication (Advanced search)

COR number: 1.2.2
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Simple search

Description:

Search by exact year of publication, e.g. 1900

@AntonioGVH
@fwelter
@LarissaS

**Comment by LarissaS** [comment]
Works good, but again switching after to advanced search I found old parameters already filled in. Should be empty!

Did not understand very good why in Facet menu in results page in front of YEAR is written REMOVE, what is practical use of it?

-----Original Message-----

**Comment by HenningScholz** [comment]
Works fine.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 13:55
An: Scholz, Henning
Betreff: Re: [bhle] 1.2.2 - Search by year of publication (Advanced search) (#45)

1.2.2 - Search by year of publication (Advanced search)

COR number: 1.2.2
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Simple search

Description:

Search by exact year of publication, e.g. 1900

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AnneSch** [comment]
Works! 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:56
An: Scholz, Annemarie
Betreff: Re: [bhle] 1.2.2 - Search by year of publication (Advanced search) (#45)

1.2.2 - Search by year of publication (Advanced search)

COR number: 1.2.2
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search, Simple search

Description:

Search by exact year of publication, e.g. 1900

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
Works fine, ready to close.

@LarissaS 
The reset button is fixed and working now. The fields in advanced search are still filed till you do not close your session by using reset button or adding new search from simple search or browse. If you go from result list to book bibliographic page and even to book-viewer you are still in your session and have the possibility go back and modify you search.

The step back button in result list was changed to Edit search button and the result list was integrated under the advanced search block or browse block. It solved several problems and will be tested in next phase.

Remove in Facet list means remove back this filter option. It is the same as delete the last search field in advanced search blok. This function is already implemented on developing platform and will be tested in next testing phase.
