### ISSUE TITLE
1.2.3 - Search by range of years of publication (Advanced Search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#46]
Update:

Search needs to be always in form e.g. [1850 TO 1950]. For simple and advanced search.

Search by range of years of publication, e.g. 1850-1950
reported bug #170

**Comment by JiriFrank** [comment]
Advance search 2 and 3

**Comment by janahoffmann** [comment]
This feature is not working correctly. 
If you select the metadatafield 'date' and indicate a range e.g. 1901-1905 it also displays results with 1905 in the title metadata field. 
It should only display result with the year 1901-1905 in the publication metadata field.
The search is only performed for the start and end point e.g. if you search for 1857 to 1859 the search is only performed for "1857" and "1859", but it should also search for 1858.

**Comment by JiriFrank** [comment]
Brackets are needed for search for ranges mentioned in Advance search3: [start TO end], but it reports a error. mentioned bug #179

**Comment by JiriFrank** [comment]
Testing of feature 1.2.3 - Search by range of years of publication

Feature description from the Catalogue of user requirements:

Search by range, e.g. 1850-1950

Testers:
@AntonioGVH
@fwelter
@heimor
@janahoffmann
@JFTester
@JiriFrank
@LarissaS

**Comment by JiriFrank** [comment]
Testing of feature 1.2.3 - Search by range of years of publication

Feature description from the Catalogue of user requirements:

Search by range, e.g. 1850-1950

Testers:
@fwelter

**Comment by LarissaS** [comment]
Testing of feature 1.2.2 - Search by year of publication

Searching with Advanced search 1: 
With all words: 1908 gives 99 matches as well for literature published in 1908 as for texts where 1908 is just mentioned in the bibliographic record.

Searching in exact field with "1908": I was doubting between CREATED and ISSUED, by trying I've got 0 results for first and 6 results for second.

Searching with Advanced search 2: I choose field ISSUAD "1908" and have got same result - 6 records

Conclusion: it is not clear if year of publication corresponds to CREATED or ISSUED field. 

I am sorry, I just have seen that there is also field DATE and searching with DATE: 1908 gave me 21 result (all from Oberösterreichisches Landesmuseum) but 6 result which I have got with searching be CREATED: 1908 (RMVA, RBGE) are not in. Is it due to difference in metadata fields between different content providers?

Subject: Re: [bhle] 1.2.3 - Search by range of years of publication (#46)

Watch out: mistake in Advanced search 3 - it is written "serach for ranges via:"

I have used this option and searching with Advanced search 3: 1900 TO 1908 gave me 214 records, which is obviously to much, these are not only books published in this range, but also books where these dates are just mentioned in the bibliographic record. There is also mismatch between numbers in left column DATA PROVIDER and real number of records then you click on one of providers.

So, I did not really understood how I could find literature published between 1900 and 1908!

---

-----Original Message-----

**Comment by AntonioGVH** [comment]
This option doesn't work properly.

I tested for '1984 - 1994' and I got work published out of that range.

A.

Quoting JiriFrank:

**Comment by fwelter** [comment]
1.2.3   range of years, Advanced Search 3

Advanced Search 3 restored the simple search mode automatically after
each single search

1950-1960
- 1 result:
  Oberösterreichisches Landesmuseum (1)
- only year 1960 was found

1894-1921
- no results

1930-1950
- no results

Advanced Search 2

dc_date   1980-1990
- no results

dc_date   1894-1921
- no results

dcterms_issued   1980-1990
- no results

dcterms_issued   1894-1921
- no results

dcterms_issued   196*
- results: 
  1. NCB Naturalis (292)
  2. Royal Botanic Garden Edinburgh (22)

dcterms_issued   192*
- results:
  1. NCB Naturalis (104)
  2. Royal Botanic Garden Edinburgh (20)
  3. Helsingin yliopisto (10)
  4. Royal Museum for Central Africa (4)

---
- when there were many results the page took long time to load in and
  blocked the mouse of my computer. this was because all the thumbnails
  needed to load in. it seems that also those thumbnails needed to load
  in that were not displayed on the screen. if I had installed to
  display 25 results in the hitlist and there were 1500 results the
  thumnails for all 1500 results loaded in. after that the computer was
  largely blocked and very slow, I tried to close the window as soon as
  possible and I also tried not to select search terms that produced so
  many results.
- nowhere was displayed how many titles were found in total, usually I
  listed the numbers given for data providers. only maximum 5 data
  providers were shown, I discovered this bug only very late in the
  testing process.
- it is also possible that Date, Language and the other facet lists
  had also restrictions for 5 lines to be shown only. I realised this
  only after 2 weeks testing.
- the big problem was that too many results were shown, mainly for two
  reasons:

1 - the result lists generally displayed titles where none of the
words were contained in the title, author or year, but in the text of
the abstract and notes of the item page. 

2 - single journal volumes were displayed for serial runs, they
blocked all intelligent search attempts and spammed the results list
with over and over the same journal title. 
- it was generally very difficult (better say, practically impossible)
  to test for completeness of results. restricting search for (1) only
  in title, author and date and (2) exclude journal metadata of single
  journal volume item pages (and instead create one single journal title
  hit) would probably solve the problems.

Francisco

---

F. Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536, Fax +49 551 395579
http://www.gwdg.de/~fwelter
http://www.animalbase.org

**Comment by lobajuluwa** [comment]
Jiri following on from the Portal Review Workshop held in the Hague: This feature is still "Open" in the Test Core Release Milestone for August - Pls confirm if feature is fully functional or not? Thanks.
@JiriFrank

**Comment by JiriFrank** [comment]
@lobajuluwa
It doesn’t works because of the problem with metadata. Now it is not possible to test it without functional testing platform with the content. It must be open and available for testing hopefully very soon.

**Comment by JiriFrank** [comment]
Andreas will addapted that.

**Comment by JiriFrank** [comment]
It is still not working. Range of years working just for simple search and still not properly. In simple search you need to search in form e.g. 1900-1919. You will get 3 results with years 1919, 1900 and 1900-07. The book with year e.g. 1910 is not included in the result. Typing 1900 TO 1919 has no results. 

In advanced search search for range of years in metadata field "year" does not work in any form. 

@akohlbecker 
@chris-sleep 

Bug reported Issue #290
Related feature Issue #48

**Comment by JiriFrank** [comment]
Works fine and is tested. Could be closed.

@chris-sleep
