### ISSUE TITLE
1.2.5 - Combined search in different metadata fields (Advanced Search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#48]
Updated description:
Select/ combine different metadata fields for search; e.g. search for author and year, or search for taxon name in a certain time interval.

Precondition: 
Define metadata fields for search. Display alternative title for the user, e.g. not 'dc_title' but 'Title'. 

Old description:
Select different categories for search; e.g. search for author and year, or search for taxon name in a certain time interval. 

Precondtion: Define main search categories or list of metadata fields. 

Reported bug #171

**Comment by JiriFrank** [comment]
The date search only gives you results from LANDOE because the books have the year in the title.
If the date search is in the first field you will always get the results from dates (from LANDOE).
Other categories combinations are working independent on order.

**Comment by janahoffmann** [comment]
Search for dates doesn't work correctly in advanced search.
Search for dates is only performed on LANDOE collection because the year is included automatically in the title (which is not supposed to be the case!). In advanced search no other collection can be found by searching for dates.

In simple search, search for dates works (because search is performed on all metadata fields).

**Comment by JiriFrank** [comment]
Testing of feature 1.2.5 - Combined search in different categories 

Feature description from the Catalogue of user requirements:

Select different categories for search; e.g. search for author and year, or search for taxon name in a certain time interval.

Precondtion: Define main search categories or list of metadata fields. 

Testers:
@AntonioGVH
@fwelter
@heimor
@janahoffmann
@JFTester
@JiriFrank
@LarissaS

**Comment by JiriFrank** [comment]
Testing of feature 1.2.5 - Combined search in different categories

Feature description from the Catalogue of user requirements:

Select different categories for search; e.g. search for author and year, or search for taxon name in a certain time interval.

Precondtion: Define main search categories or list of metadata fields.

Testers:
@fwelter

**Comment by LarissaS** [comment]
Testing of feature 1.2.5 - Combined search in different categories
I searched for "creator: guign_" AND "title: coleoptera (also coleo_)" and have got one result, searching just for "guignot" gives 2 results, so it looks OK.
But searching for "creator:Boulenger AND title:batracien" - 0 results, it means that in collection of RMCA (where we have several records of Boulenger) there is no field CREATOR, may be it will be updated during metadata mapping?

Still don't understand why there is no field AUTHOR?

I already mentioned it before, here I just repeat:
Searching with Advanced search 2: 
I notice that if I add new field and after entering search term I automatically push on "enter" instead of pushing on search I get again one field and have to restart all process.  

-----Original Message-----

**Comment by AntonioGVH** [comment]
This option seems not to work properly.
(As I know that there are two works by Valdecasas in the data base) I searched by 'Valdecasas and 1984' or 'Valdecasas 1984'.
One gets a lot of results that has nothing to do with Valdecasas.

Antonio

Quoting JiriFrank:

**Comment by fwelter** [comment]
1.2.5   combined search in different fields (year, title, author...)

I could only use Advances Search 2 for that, the others didn't give
the option to select 2 or more search categories

dcterms_issued:1952 AND dc_title:ceratina
- 1 result, from NCB Naturalis

dcterms_issued:2002 AND dc_title:revision
- results:
  NCB Naturalis (7)

dc_date:2002 AND dc_title:revision
- no results

dc_date:2002 AND dc_title:monografien
- 1 result 
  Oberösterreichisches Landesmuseum (1)

dc_date:2002 AND dc_title:landesmuseen
- results:
  Oberösterreichisches Landesmuseum (14)
- always the same journal title, 14 different volumes of that year

dcterms_created:2009 AND dc_title:svampe
- results:
  University of Copenhagen (23)

dc_creator:linne AND dc_title:systema
- results:
  UB der Humboldt-Universität, Zweigbibliothek Museum für Naturkunde
  (12)

dc_creator:linne AND dc_title:systema AND dc_date:1788
- results:
  UB der Humboldt-Universität, Zweigbibliothek Museum für Naturkunde
  (9)

dc_title:v AND dc_title:finnland
- results:
  Helsingin yliopisto (5)
- the results were incorrect in 2 concerns:
- any "v" in the middle of words was detected, or at the beginning of
  words (I observed this bug only for Helsingin yliopisto) - in result
  No. 1 (not in the others) results for "v" were found in the authors
  and editors metadata field (marked in yellow)

combined research does work, but you have to know exactly the tricks
(dcterms_issued for NCB Naturalis titles, dc_date for
Oberösterreichisches Landesmuseum titles etc.). Oberösterreichisches
Landesmuseum has only journal volumes, you can only search for these,
and it displays every single journal volume as a single hit. Same
problem with University of Copenhagen.

---
- when there were many results the page took long time to load in and
  blocked the mouse of my computer. this was because all the thumbnails
  needed to load in. it seems that also those thumbnails needed to load
  in that were not displayed on the screen. if I had installed to
  display 25 results in the hitlist and there were 1500 results the
  thumnails for all 1500 results loaded in. after that the computer was
  largely blocked and very slow, I tried to close the window as soon as
  possible and I also tried not to select search terms that produced so
  many results.
- nowhere was displayed how many titles were found in total, usually I
  listed the numbers given for data providers. only maximum 5 data
  providers were shown, I discovered this bug only very late in the
  testing process.
- it is also possible that Date, Language and the other facet lists
  had also restrictions for 5 lines to be shown only. I realised this
  only after 2 weeks testing.
- the big problem was that too many results were shown, mainly for two
  reasons:

1 - the result lists generally displayed titles where none of the
words were contained in the title, author or year, but in the text of
the abstract and notes of the item page. 

2 - single journal volumes were displayed for serial runs, they
blocked all intelligent search attempts and spammed the results list
with over and over the same journal title. 
- it was generally very difficult (better say, practically impossible)
  to test for completeness of results. restricting search for (1) only
  in title, author and date and (2) exclude journal metadata of single
  journal volume item pages (and instead create one single journal title
  hit) would probably solve the problems.

Francisco

---

F. Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536, Fax +49 551 395579
http://www.gwdg.de/~fwelter
http://www.animalbase.org

**Comment by JiriFrank** [comment]
This function is working properly. The problem is only with the date field which is connected with metadata and was already reported. After fixing that the feature could be close.

**Comment by lobajuluwa** [comment]
CS: will know if feature is complete once Archival Storage/OLEF are in place.

**Comment by JiriFrank** [comment]
1.2.5 - Combined search in different metadata fields (Advanced Search)

COR number: 1.2.5
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Select/ combine different metadata fields for search; e.g. search for author and year, or search for taxon name in a certain time interval.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by RalfH** [comment]
It works but there is a general problem for multi-volume books.

If I search Sturm's flora for the complete publication period 1798-1862 it works but search for a single volume, e.g. vol. 9 of 1812-1814 is not successful. That may change later when the input is complete and volumes und their metadata are added one by one.

Search in a certain time interval (as recommended in the search combinations) proved to be tricky. "type the start TO end or start - end; recommended is searching in metadata field "year" does not work.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:58
An: Hand, Ralf
Betreff: Re: [bhle] 1.2.5 - Combined search in different metadata fields (Advanced Search) (#48)

1.2.5 - Combined search in different metadata fields (Advanced Search)

COR number: 1.2.5
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Select/ combine different metadata fields for search; e.g. search for author and year, or search for taxon name in a certain time interval.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
1.2.5 - Combined search in different metadata fields (Advanced Search)

COR number: 1.2.5
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Select/ combine different metadata fields for search; e.g. search for author and year, or search for taxon name in a certain time interval.

@AntonioGVH
@fwelter
@LarissaS

**Comment by LarissaS** [comment]
It works, but some bugs:
- I was looking for "flora" AND "1900-1930", has got no results, "flora" AND "1900" - 2 results, so the question is if can I use interval written this way, nowhere could find help! 
  - if I look first for "flora" and then look in facet menu for years and do open for example 1913(1) I see two results, also saw some other mistakes.
    If I want to browse then it does not work at all.  

-----Original Message-----

**Comment by AnneSch** [comment]
Works good, if you know the exact release year. 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:58
An: Scholz, Annemarie
Betreff: Re: [bhle] 1.2.5 - Combined search in different metadata fields (Advanced Search) (#48)

1.2.5 - Combined search in different metadata fields (Advanced Search)

COR number: 1.2.5
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Select/ combine different metadata fields for search; e.g. search for author and year, or search for taxon name in a certain time interval.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by HenningScholz** [comment]
Works fine.

---

Dr. Henning Scholz 
Museum für Naturkunde | Leibniz Institute for Research on Evolution and Biodiversity at the Humboldt University Berlin
Invalidenstraße 43 | D-10115 Berlin | Germany 
Tel.: +49-30-2093-8864 | Fax: +49-30-2093-8868 
Email: henning.scholz@mfn-berlin.de
http://www.naturkundemuseum-berlin.de/ / http://www.bivalve.de 
http://www.bhl-europe.eu / http://www.biodiversitylibrary.org/
BHL-Europe in Europeana:  bit.ly/BHLE-Europeana

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 13:58
An: Scholz, Henning
Betreff: Re: [bhle] 1.2.5 - Combined search in different metadata fields (Advanced Search) (#48)

1.2.5 - Combined search in different metadata fields (Advanced Search)

COR number: 1.2.5
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Select/ combine different metadata fields for search; e.g. search for author and year, or search for taxon name in a certain time interval.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
The field combinations works, but in some cases are reported bugs

Bug - Range of years Issue #290 is solved. For range of years needs to be used form [ TO ]
Implemented on developing platform and tested.

@RalfH
@LarissaS
@AnneSch
