### ISSUE TITLE
1.2.10a - Search for origin of publication (renamed, Advanced Search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#53]
Updated description:
Search in metadata field 'origin of publication', this means city or country, e.g. search for books published in Berlin or Germany.

Extension: 
Invoke webservices in order to get the location/ country of a city.
Provide a map.

Preconditions:
Provision of origin of publication by CP with metadata.
For extension: Integration of geographic reference webservices.

Old description:
Search in metadata field language or origin of publication, e.g. Search for books published in Germany in 1950-1956

Related bug #180 

Connected issue #237 (previously summarised under 1.2.10 Search for publishing country/ language)

**Comment by fwelter** [comment]
4th column: It would possibly be necessary to have a database/controlled vocabulary to understand terms like "Lipsiae".

**Comment by janahoffmann** [comment]
@fwelter Can you explain what you mean here..I don't see this being related to the issue...4th column of what?

**Comment by fwelter** [comment]
I meant the 4th column in your PDF document.
https://bhl.wikispaces.com/file/view/BHL-E_catalogue+of+requirements_v0.pdf

I do not know if library metadata contain a field "country of publication", I thought not. I know they do have a field "locality of publication" which usually contains one or more cities, often copied from the original source. "Lipsiae" (= Leipzig, Germany) is an example to illustrate that if the locality was copied from the original source, then a database is necessary to decode this term and associate "country: Germany" to the term "Lipsiae".

**Comment by janahoffmann** [comment]
@sprogerb There is a metadata field language 'language of metadata' or 'language of publication/ volume'. Could you please clarify whether this would be helpful for this issue or not? 
@fwelter So, a controlled vocabulary would not be needed if only the language matters. Of course this would be more a proxy.
@jirifrank What metadata field do you use for BLE as you have the function sort by country?

**Comment by janahoffmann** [comment]
ready for testing

search for language works fine in general but only if you use:
e.g. "deutsch", it doesn't work for "German" - predefined search terms required (generally understood), pull down menus would be very helpful for the user here (existed in German prototype)

in facet list inconsistent use of language description...sometimes 'eng' and sometimes 'english'  or 'ger' and 'German'

search for language can be combined with search in other fields e.g. deutsch and Afrika - o.k. 

search for publishing country not established - what would be the correct metadata field for search?

**Comment by JiriFrank** [comment]
Some of the Books details in BLE are edited automatically from the metadata and book ID, e. g. Place and Publisher. Based on this information I just check the right country in country category in editing book details form. This will connect the book with the category and the book is sorted by country. It is different system than on the portal.

**Comment by JiriFrank** [comment]
Bug:
Portal includes on Russian book written in Russian

Дополнения и уточнения к фауне чешуекрылых (Lepidoptera) Тульской области. 1 = Additions and corrections to the fauna of Lepidoptera of the Tula Province. 1 

but Matches for: dc_language:Russian have 0 results.

The same for Matches for: dc_language:Español or Matches for: dc_language:Spanish

The same for Matches for: dc_language:French or Matches for: dc_language:Français
Books written by these languages are on portal.

Deutsch and English seems to be fine.

**Comment by JiriFrank** [comment]
Testing of feature 1.2.10 - Search for publishing country/ language

Feature description from the Catalogue of user requirements:

Search in metadata field language or origin of publication, e.g. Search for books published in Germany in 1950-1956

Testers:
@AntonioGVH
@fwelter
@heimor
@janahoffmann
@JFTester
@JiriFrank
@LarissaS

**Comment by JiriFrank** [comment]
Testing of feature 1.2.10 - Search for publishing country/ language

Feature description from the Catalogue of user requirements:

Search in metadata field language or origin of publication, e.g. Search for books published in Germany in 1950-1956

Testers:
@fwelter

**Comment by LarissaS** [comment]
Subject: Re: [bhle] 1.2.10 - Search for publishing country/ language (#53)

Searching with Advanced search 1: 
Search does not work for "French" or "dutch", but finds "fre" and "dut" but only in RMCA collection. 
Searching for "English" gave 28 records from Copenhagen where "English" is mentioned in the metadata filed. Searching for "eng" gives 214 records, looks Ok.

Obviously Naturalis and Oberösterreichisches Landesmuseum have no field "language" in their metadata?

It's also annoying then I go back for new search, I have to choose the field again! May be the button "change the search" could be usefull 

Searching with Advanced search 2: 
I notice that if I add new field and after entering search term I automatically push on "enter" instead of starting the search I get one field and have to restart again all process.  

-----Original Message-----

**Comment by AntonioGVH** [comment]
This option seems to get works  by both criteria, eg.
-queriing by 'Spain' and '1984', gets works with 'Spain', '1984' and 'Spain 1984'.

I think that it is interesting to offer in the result of the query, a summary of works found under each criteria.
I discovered that queriing by 'Sapin 1984' I got a lot of records. 
Queriing by 'Sapin' there are no records at all, so, the previos query are for works of 1984. That is why I tink that a summary could be useful.

A

Quoting JiriFrank:

**Comment by fwelter** [comment]
1.2.10  language/country

sorry for the ?????? in this mail, they referred to Russian 
characters that were not displayed in my mailer

Advanced Search 2

I did not get to know how to search for country. I only found a way to
search for language in Advanced Search 2.

dc_language:*
- error 400
- pity!

dc_language:e*
- results:
  1. Royal Botanic Garden Edinburgh (177)
  2. University of Copenhagen (28)
  3. Royal Museum for Central Africa (20)
  4. Helsingin yliopisto (8)
  5. Consejo Superior de Investigaciones Científicas (1)
- "Language:"
  1. eng (206)
  2. Primarily danish, some abstracts in english (28)
  3. dk (28)
  4. en (28)
  5. ger (8)

dc_language:eng
- results:
  1. Royal Botanic Garden Edinburgh (177)
  2. Royal Museum for Central Africa (20)
  3. Helsingin yliopisto (8)
  4. Consejo Superior de Investigaciones Científicas (1)
- "Language:"
  1. eng (206)
  2. ger (8)
  3. fin (7)
  4. swe (7)
  5. spa (1)

dc_language:g*
- results:
  1. Helsingin yliopisto (30)
  2. Royal Museum for Central Africa (18)
- "Language:"
  1. ger (48)
  2. swe (15)
  3. fin (14)
  4. eng (8)
  5. mul (2)
- clicking in the facet column gave the following results:
- dc_language:g\* AND dc_language__facet:"ger"
  1. Helsingin yliopisto (30)
  2. Royal Museum for Central Africa (18)
- dc_language:g\* AND dc_language__facet:"swe"
  Helsingin yliopisto (15)
- dc_language:g\* AND dc_language__facet:"fin"
  Helsingin yliopisto (14)
- dc_language:g\* AND dc_language__facet:"eng"
  Helsingin yliopisto (8)
- dc_language:g\* AND dc_language__facet:"mul"
  Helsingin yliopisto (2)
- this result was somehow logical because they included many different
  articles in one journal volume and each single journal volume was
  given as one hit in the search query. absolute nonsense, because
  nobody is interested in such a data rubbish, but probably correctly
  displayed.

dc_language:d*
- results:
  1. UB der Humboldt-Universität, Zweigbibliothek Museum für
     Naturkunde (42) 2. University of Copenhagen (28) 3. Royal Museum
     for Central Africa (6)
- "Language:"
  1. deutsch (42)
  2. Primarily danish, some abstracts in english (28)
  3. dk (28)
  4. en (28)
  5. dut (6)
- the 28 hits for dk and en were identical titles of University of
  Copenhagen, they just associated these with all of their titles (which
  was always the same journal, 28 times displayed becaused it had 28
  journal volumes). 

dc_language:f*
- results:
  1. Royal Museum for Central Africa (54)
  2. Helsingin yliopisto (14)
- "Language:"
  1. fre (54)
  2. fin (14)
  3. ger (14)
  4. swe (14)
  5. eng (7)

dc_language:r*
- no results

simple search: ??????????
- 1 result
- no Language is displayed in facet list

dc_language:s*
- results:
  1. University of Copenhagen (28)
  2. Helsingin yliopisto (15)
  3. Consejo Superior de Investigaciones Científicas (9)
- "Language:"
  1. Primarily danish, some abstracts in english (28)
  2. dk (28)
  3. en (28)
  4. ger (15)
  5. swe (15)

there were hits in spanish, but spanish was not displayed in the
language facet list

dc_language:spa
- results:
  Consejo Superior de Investigaciones Científicas (9)
- "Language:"
  1. spa (9)
  2. eng (1)

dc_language:i*
- no results

dc_language:p*
- results:
  University of Copenhagen (28)
- "Language:"
  1. Primarily danish, some abstracts in english (28)
  2. dk (28)
  3. en (28)

simple search: genero
- results:
  1. NCB Naturalis (9)
  2. Oberösterreichisches Landesmuseum (3)
- "Language" was not displayed here
- among the titles were Spanish titles

dcterms_issued:199*
- results:
  1. NCB Naturalis (583)
  2. Royal Botanic Garden Edinburgh (9)
  3. Consejo Superior de Investigaciones Científicas (7)
- "Language:"
  1. spa (7)
  2. eng (4)
- clicking on the languages gave 4 english results for Royal Botanic
  Garden Edinburgh and 7 spanish for Consejo Superior de Investigaciones
  Científicas
- the language was not displayed in the facet list for titles of the
  data provider NCB Naturalis

simple search:  monographie
- results:
  1. Oberösterreichisches Landesmuseum (86)
  2. NCB Naturalis (11)
  3. UB der Humboldt-Universität, Zweigbibliothek Museum für
     Naturkunde (4) 4. Royal Museum for Central Africa (2) 5. Helsingin
     yliopisto (1)
- "Language:"
  1. deutsch (4)
  2. fre (2)
  3. ger (1)
- the language was not displayed in the facet list for titles of the
  data providers NCB Naturalis and Oberösterreichisches Landesmuseum

dc_contributor:n*
- results:
  1. University of Copenhagen (28)
  2. Helsingin yliopisto (13)
  3. Consejo Superior de Investigaciones Científicas (5)
  4. Royal Botanic Garden Edinburgh (3)
  5. NCB Naturalis (2)
- "Language:"
  1. Primarily danish, some abstracts in english (28)
  2. dk (28)
  3. en (28)
  4. ger (13)
  5. fin (12)
- clicking on Consejo Superior de Investigaciones Científicas gave the
  following result:
  Language
  1. spa (5)

Data Provider
1. Consejo Superior de Investigaciones Científicas (5)

---
- when there were many results the page took long time to load in and
  blocked the mouse of my computer. this was because all the thumbnails
  needed to load in. it seems that also those thumbnails needed to load
  in that were not displayed on the screen. if I had installed to
  display 25 results in the hitlist and there were 1500 results the
  thumnails for all 1500 results loaded in. after that the computer was
  largely blocked and very slow, I tried to close the window as soon as
  possible and I also tried not to select search terms that produced so
  many results.
- nowhere was displayed how many titles were found in total, usually I
  listed the numbers given for data providers. only maximum 5 data
  providers were shown, I discovered this bug only very late in the
  testing process.
- it is also possible that Date, Language and the other facet lists
  had also restrictions for 5 lines to be shown only. I realised this
  only after 2 weeks testing.
- the big problem was that too many results were shown, mainly for two
  reasons:

1 - the result lists generally displayed titles where none of the
words were contained in the title, author or year, but in the text of
the abstract and notes of the item page. 

2 - single journal volumes were displayed for serial runs, they
blocked all intelligent search attempts and spammed the results list
with over and over the same journal title. 
- it was generally very difficult (better say, practically impossible)
  to test for completeness of results. restricting search for (1) only
  in title, author and date and (2) exclude journal metadata of single
  journal volume item pages (and instead create one single journal title
  hit) would probably solve the problems.

Francisco

---

F. Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536, Fax +49 551 395579
http://www.gwdg.de/~fwelter
http://www.animalbase.org

**Comment by lobajuluwa** [comment]
Update from The Hague_Portal Review Workshop: - 1.2.10 search for publishing country/language – needs to be in the metadata then it can be done.   An extra issue to be created for country – assign it to Chris.

November release: language stays 1.2.10

**Comment by janahoffmann** [comment]
Done! see #237 or this issue
@lobajuluwa

**Comment by lobajuluwa** [comment]
Thanks Jana! 
@janahoffmann

**Comment by lobajuluwa** [comment]
removing search by publication location
