### ISSUE TITLE
1.2.12 - Search with exact phrase only (Advanced search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#55]
Search for exact phrase, e.g. ' evolution of'; no deviation allowed

Related bug: #177

**Comment by akohlbecker** [comment]
The given example query string 'evolution' is only a single term and not a phrase in the proper sense. Therefore I suggest changing it into:  'evolution of'

**Comment by janahoffmann** [comment]
this corresponds to advanced search 1: exact phrase and is ready for testing (should be merged with advanced search 2)

tested and works fine for entire and not truncated words in all main metadata fields

doesn't work with truncated terms at the end or the beginning, e.g. "elm, riedl harald" or "Linzer biolog"

**Comment by JiriFrank** [comment]
Tested on “new species”
It works fine, whit all searchers. I will give the preference to Advance search 2.

**Comment by JiriFrank** [comment]
Testing of feature 1.2.12 - Search with exact phrase only

Feature description from the Catalogue of user requirements:

search for 'evolution', no deviation allowed

Testers:
@AntonioGVH
@fwelter
@heimor
@janahoffmann
@JFTester
@JiriFrank
@LarissaS

**Comment by JiriFrank** [comment]
Testing of feature 1.2.12 - Search with exact phrase only

Feature description from the Catalogue of user requirements:

search for 'evolution', no deviation allowed

Testers:
@fwelter

**Comment by LarissaS** [comment]
Other presentation of results in advanced search! Text does not past inside the grey rectangles and therefore is offset. I see that I can change it in list form, but on default it was in table form!

Searching in Advanced search 1:

if I look just for African fish I have no results!

Searching for "African fish" gives 230 results, I have checked first 5 and did not find matching for exact phrase! Quick view through showed not only publications about fishes (from RMCA collection well) but also about wasps, lions etc.!

Searching for Central Africa gives 108 results, all with complete match. Searching for "Central Africa" gives 494 results, highlight shows also matching for "Africa" and for "Central"!

I also controlled Advanced search 3:

Searching with exact phrase "African fish" gives no result, searching for "Central Africa" gives  108 results. So it is the same as with search 1.

Also tried fresh water mollusk - no result, freshwater mollusk - 2 results.

May be interesting:

fresh-water gives matches for fresh water too. 

Fresh water gives matches for fresh-water, water, fresh, but no freshwater

Freshwater gives matches for fresh-water but not for fresh water

I am sorry I forgot yesterday change the My account/Advanced Search/Default result view type from table to the list. We are working on the template and I was demonstrated to Jiri something with the portal. The Default result view type is back on the list, but you can change it also yourself. I think this is also one of the testing features and as you already observed, the table view doesn't work properly.

-----Original Message-----

**Comment by AntonioGVH** [comment]
It seems that this option works properly in the advanced search

Quoting JiriFrank:

**Comment by fwelter** [comment]
1.2.12   search with exact phrase

"voyage iles"
- no results. this was correct.

"mantides du musee"
- 1 result (mantides du Musée) - correct

"mantide du muse", "mantid du muse", "mantid du muses", "mantid du
musees", "mantids du musees", "mantides du musees"
- 1 result (mantides du Musée) - incorrect

"mantidese du muse", "mantid dus muses", "mantid due muses", "mantidse
du musees", "mantides du museees", "mantidees du musee", "mantides de
musee"
- no results - correct

"de l'afrique"
- the number of hits was not indicated, you have to count "Data
  Provider" or "Rights": 5 + 5 + 3.

"de lafrique"
- no results

"l'afrique maroc"
- 2 results finding l'Afrique (Maroc

"lafrique maroc"
- 2 results finding l'Afrique (Maroc  - but not marked in yellow!

" lafrique maroc"
- 2 results finding l'Afrique (Maroc  - but not marked in yellow!

"de lafrique maroc"
- no results

"de l'afrique maroc"
- 2 results finding l'Afrique (Maroc  

"weissen ameise", "weißen ameise"
- 2 results (in both searches 1 hit weißen ameise and 1 hit weissen
  ameise - correct)

"weissens ameise", "weissene ameise", "weissen ameises", "weissenes
ameise", "weissenes ameises"
- same 2 results - incorrect

"weisse ameisen", "weisse ameise", "weisses ameises", "weisses
ameise", "weissen ameisee", "weissense ameisee", "weissen ameisese"
- no results - correct

"entomologica de autores"
- 1 result (entomológica de autores) - correct

"entomologicas de autores", "entomologicaes de autores", "entomologica
de autore", "entomologica de autor"
- 1 result - incorrect

"entomologica de autorese", "entomologica des autores",
"entomologicaese de autores", "entomologica d autores", "entomologica
de auto", "entomologic de autores"
- no results - correct
- exact search works except that -e and -s and -es can be added to the
  end, with some exceptions.

---
- when there were many results the page took long time to load in and
  blocked the mouse of my computer. this was because all the thumbnails
  needed to load in. it seems that also those thumbnails needed to load
  in that were not displayed on the screen. if I had installed to
  display 25 results in the hitlist and there were 1500 results the
  thumnails for all 1500 results loaded in. after that the computer was
  largely blocked and very slow, I tried to close the window as soon as
  possible and I also tried not to select search terms that produced so
  many results.
- nowhere was displayed how many titles were found in total, usually I
  listed the numbers given for data providers. only maximum 5 data
  providers were shown, I discovered this bug only very late in the
  testing process.
- it is also possible that Date, Language and the other facet lists
  had also restrictions for 5 lines to be shown only. I realised this
  only after 2 weeks testing.
- the big problem was that too many results were shown, mainly for two
  reasons:

1 - the result lists generally displayed titles where none of the
words were contained in the title, author or year, but in the text of
the abstract and notes of the item page. 

2 - single journal volumes were displayed for serial runs, they
blocked all intelligent search attempts and spammed the results list
with over and over the same journal title. 
- it was generally very difficult (better say, practically impossible)
  to test for completeness of results. restricting search for (1) only
  in title, author and date and (2) exclude journal metadata of single
  journal volume item pages (and instead create one single journal title
  hit) would probably solve the problems.

Francisco

---

F. Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536, Fax +49 551 395579
http://www.gwdg.de/~fwelter
http://www.animalbase.org

**Comment by JiriFrank** [comment]
The function seems to work properly, but there is still problem whit the diacritic tolerance, in that case it is not the exact phrase, but the similar phrase. This problem was already reported in bug #177.

**Comment by JiriFrank** [comment]
Reopened for testing in new Advanced search module

**Comment by JiriFrank** [comment]
1.2.12 - Search with exact phrase only (Advanced search)

COR number: 1.2.12
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search for exact phrase, e.g. ' evolution of'; no deviation allowed

---

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by RalfH** [comment]
It works.

But it should be taken into consideration that users don't know the exact spelling in foreign languages. You find "Plantas medicinales de Filipinas", but if somebody is searching - erroneously - for "Plantas medicinales de Filipina" (i.e. omitting the S), no results are given. Phrase is not truly wrong, but incomplete. Could be frustating. 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 14:11
An: Hand, Ralf
Betreff: Re: [bhle] 1.2.12 - Search with exact phrase only (Advanced search) (#55)

1.2.12 - Search with exact phrase only (Advanced search)

COR number: 1.2.12
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search for exact phrase, e.g. ' evolution of'; no deviation allowed

---

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment]
Checked it using a phrase with diacritics, and it works, you need to search with the diacritics for the record to be retrieved, used "Beschrijving van de familiën" as example.

**Comment by JiriFrank** [comment]
1.2.12 - Search with exact phrase only (Advanced search)

COR number: 1.2.12
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search for exact phrase, e.g. ' evolution of'; no deviation allowed

@AntonioGVH
@fwelter
@LarissaS

**Comment by LarissaS** [comment]
It worked when I was searching for "Deutsche flora" and also with switched "exact word/phrase", but when I was looking for Deutsche flora without "", I have got also one result, while I have 8 results with word "flora".

-----Original Message-----

**Comment by HenningScholz** [comment]
Seams to work, but not enough books to really test it and see the difference compared to boolean search.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 14:11
An: Scholz, Henning
Betreff: Re: [bhle] 1.2.12 - Search with exact phrase only (Advanced search) (#55)

1.2.12 - Search with exact phrase only (Advanced search)

COR number: 1.2.12
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search for exact phrase, e.g. ' evolution of'; no deviation allowed

---

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AnneSch** [comment]
Works fine! 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 14:11
An: Scholz, Annemarie
Betreff: Re: [bhle] 1.2.12 - Search with exact phrase only (Advanced search) (#55)

1.2.12 - Search with exact phrase only (Advanced search)

COR number: 1.2.12
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search for exact phrase, e.g. ' evolution of'; no deviation allowed

---

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
Works!
