### ISSUE TITLE
1.4.2 - Sort result list by facet list (renamed, Result list)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#62]
Updated description:
Sort result by main categories: 
material type (by category): serial (journal), journal volume, monograph; 
author (alphabetically); 
date (numerically); 
language (by category); 
content provider (sort by category); 
scientific name
...

Display number of hits per category

Precondition: 
Expandable facet list  

Previous description:
sort result list by: (1) category; (2) alphabetically (A B C ….); (3) type of publication (journal, monograph); ((4) popularity)

Preconditions:
Web analytic, define main categories, provide type of publication with metadata (for tag)

Related bug #199, #194?

Replaces issue: #64

**Comment by JiriFrank** [comment]
Ready for testing

**Comment by janahoffmann** [comment]
ready for testing

main search categories are: author, title, year and journal title - please change

journal/monograph: information not yet available

**Comment by JiriFrank** [comment]
Testing of feature 1.4.2 - Sort result list

Feature description from the Catalogue of user requirements:

Sort result list by: (1) category; (2) alphabetically (A B C ….); (3) type of publication (journal, monograph); ((4) popularity)

Preconditions:
Web analytic, define main categories, provide type of publication with metadata (for tag)

Testers:
@AntonioGVH
@fwelter
@heimor
@janahoffmann
@JFTester
@JiriFrank
@LarissaS

**Comment by JiriFrank** [comment]
Testing of feature 1.4.2 - Sort result list

Feature description from the Catalogue of user requirements:

Sort result list by: (1) category; (2) alphabetically (A B C ….); (3) type of publication (journal, monograph); ((4) popularity)

Preconditions:
Web analytic, define main categories, provide type of publication with metadata (for tag)

Testers:
@fwelter

**Comment by AntonioGVH** [comment]
There are some options to sort results in the portal, but do not seems to work very well.

A

Quoting JiriFrank:

**Comment by fwelter** [comment]
1.4.2      sort result list

(1) category; (2) alphabetically (A B C ..); (3) type of publication
(journal, monograph); ((4) popularity)

(1) category

I tried to list results by clicking on the button sorted by "Subject"

simple search: 

uber
- results:
  1. Oberösterreichisches Landesmuseum (1224)
  2. Universitätsbibliothek Bielefeld (188)
  3. NCB Naturalis (106)
  4. Royal Museum for Central Africa (6)
  5. UB der Humboldt-Universität, Zweigbibliothek Museum für
     Naturkunde (3)
- clicking on sorted by Subject button changed the sorting, but I was
  not able to understand in which sense. hundreds of single journal
  volumes were in the results list.

musee
- results:
  1. NCB Naturalis (25)
  2. Royal Museum for Central Africa (20)
  3. Oberösterreichisches Landesmuseum (7)
- clicking on sorted by Subject button changed (arrow up) the sorting,
  but I was not able to understand in which sense. 
- clicking on the sorted by Subject button once again (arrow down),
  changed the sorting again, but the last title in the previous list did
  not become the first title in the new sorting (but No. 18)

I was not able to understand what was sorted there and what was meant
by "category" or "subject". 

(2) alphabetically (A B C ..)

I tried to list results by clicking on the button sorted by "Title"

musee
- results:
  1. NCB Naturalis (25)
  2. Royal Museum for Central Africa (20)
  3. Oberösterreichisches Landesmuseum (7)
- clicking on the sorted by Title button (arrow up) yielded an
  alphabetical arrangement beginning with A
- all were sorted correctly
- clicking on the sorted by Title button again (arrow down) yielded an
  alphabetical arrangement beginning with Z, the last title became the
  first title in the new sorting

lepidoptera
- results:
  1. Oberösterreichisches Landesmuseum (303)
  2. NCB Naturalis (162)
- clicking on the sorted by Title button (arrow up) yielded an
  alphabetical arrangement beginning with A
- all were sorted more or less correctly
- one article beginning with P was sorted behind Z -     incorrect,
  should have been sorted under P
- one Russian article beginning with ? was sorted behind Z -  
  acceptable

autores
- results:
  1. NCB Naturalis (17)
  2. Oberösterreichisches Landesmuseum (7)
  3. Consejo Superior de Investigaciones Científicas (1)
- all were sorted more or less correctly, including the title from
  Consejo Superior de Investigaciones Científicas

coleoptera
- results:
  1. Oberösterreichisches Landesmuseum (298)
  2. NCB Naturalis (139)
  3. Royal Museum for Central Africa (6)
  4. Consejo Superior de Investigaciones Científicas (3)
  5. Helsingin yliopisto (1)
- all were sorted more or less correctly
- Coléoptères sorted behind Coleoptera  -    correct
- Catálogo sorted before Catalogue  -    correct
- this means that á and é were treated like a and e  -   correct

ver*
- results:
  1. Oberösterreichisches Landesmuseum (1831)
  2. NCB Naturalis (1681)
  3. Universitätsbibliothek Bielefeld (240)
  4. University of Copenhagen (28)
  5. Helsingin yliopisto (16)
- these were not complete because data provider number was restricted
  to 5 in this list
- sorting alphabetically to begin with A
- [ was sorted before A (p. 1)  - incorrect, such a character should
  be ignored in the sorting
- " was sorted before A (p. 32)  - incorrect, such a character should
  be ignored in the sorting
- " was sorted behind Z (p. 11)  - incorrect, such a character should
  be ignored in the sorting
- ' was sorted before A (p. 32)  - incorrect, such a character should
  be ignored in the sorting
- 3 journal articles from NCB Naturalis of the journal Zoologische
  Verhandelingen were incorrectly sorted behind ZW (p. 39)  - incorrect
- there were more articles in that journal that were sorted correctly,
  so this bug was difficult to understand
- U and Ü were sorted as if Ü was U (p. 34)   - correct
- numbers were sorted alphabetically (1, 10, 11, 19, 2, 20, 21, 29, 3,
  30, 31...) - incorrect, numbers should be sorted as if they were
  numbers examples: SVAMPE journal volume numbers, Systematic notes on
  Asian birds. 13 - monographic multivolume works volume numbers
- _ was sorted behind 9 (p. 27) - incorrect, such a character should
  be ignored in the sorting
- . was sorted behind space (p. 27, "Celebes. VIII")
- - was sorted before A (p. 23) - incorrect, such a character should
    be ignored in the sorting, "Neue Indo-Malayische Hydrophiliden" should
    sort behind "Neue indomalayaische Borkenkäfer"
- clicking on the sorted by Title button again (arrow down) yielded an
  alphabetical arrangement beginning with Z, the last title became the
  first title in the new sorting

alphabetical sorting seemed to work largely. in some cases errors were
observed that I was not able to understand. special characters like '
, . - _ " ( ) ; etc. should be ignored in the sorting.

(3) type of publication (journal, monograph)

I tried to list results by clicking on the button sorted by "Type"

musee
- results:
  1. NCB Naturalis (25)
  2. Royal Museum for Central Africa (20)
  3. Oberösterreichisches Landesmuseum (7)
- clicking on the sorted by Type button (arrow up) showed first the
  journal volumes of Oberösterreichisches Landesmuseum (without that I
  understood how these titles were sorted within themselves), then the
  journal articles of NCB Naturalis, and then the monographs of Royal
  Museum for Central Africa
- clicking on the sorted by Type button again (arrow down) did not
  change the sorting. exactly the same result in the same order were
  shown.

ver*
- results:
  1. Oberösterreichisches Landesmuseum (1831)
  2. NCB Naturalis (1681)
  3. Universitätsbibliothek Bielefeld (240)
  4. University of Copenhagen (28)
  5. Helsingin yliopisto (16)
- these were not complete because data provider number was restricted
  to 5 in this list
- "Type:"
  1. Text (3814)
  2. Zeitschriftenartikel (240)
  3. Journal (28)
  4. Books, Monographs (6)
  5. book (6)
- clicking on the sorted by Type button again (arrow down) did not
  visibly change the sorting. 

(4) popularity

I did not know where to list results by popularity. this was obviously
not yet installed.

(5) author

I tried to list results by clicking on the button sorted by "Creator"

ver*
- results:
  1. Oberösterreichisches Landesmuseum (1831)
  2. NCB Naturalis (1681)
  3. Universitätsbibliothek Bielefeld (240)
  4. University of Copenhagen (28)
  5. Helsingin yliopisto (16)
- authors were sorted alphabetically, but only of the results of the
  following providers:
  NCB Naturalis
  Universitätsbibliothek Bielefeld
  Oberösterreichisches Landesmuseum (only some)
- the results of the other providers were just sorted in before A

musee
- results:
  1. NCB Naturalis (25)
  2. Royal Museum for Central Africa (20)
  3. Oberösterreichisches Landesmuseum (7)
- sorted by "Creator arrow up" had the effect that all tiles from
  Royal Museum for Central Africa were displayed before A, and they were
  sorted by their IDs. 
- after that came the results from NCB Naturalis and
  Oberösterreichisches Landesmuseum, correctly sorted by Author

If none of the "sorted by" buttons were clicked the results were
sorted by ID number from small to large

Once I have clicked on one of the "sorted by" buttons it was only
possible to select another button, but it was not possible to undo the
sorting and to produce the initial stage without a selected sorting.

If the program did not know how to sort (due to bugs or because "Type:
text" contained many hits) then the results were sorted by ID from
small to large. 
- it was not possible to select 2 sortings in the same query (for
  example, first by Type and then by Alphabet)

---
- when there were many results the page took long time to load in and
  blocked the mouse of my computer. this was because all the thumbnails
  needed to load in. it seems that also those thumbnails needed to load
  in that were not displayed on the screen. if I had installed to
  display 25 results in the hitlist and there were 1500 results the
  thumnails for all 1500 results loaded in. after that the computer was
  largely blocked and very slow, I tried to close the window as soon as
  possible and I also tried not to select search terms that produced so
  many results.
- nowhere was displayed how many titles were found in total, usually I
  listed the numbers given for data providers. only maximum 5 data
  providers were shown, I discovered this bug only very late in the
  testing process.
- it is also possible that Date, Language and the other facet lists
  had also restrictions for 5 lines to be shown only. I realised this
  only after 2 weeks testing.
- the big problem was that too many results were shown, mainly for two
  reasons:

1 - the result lists generally displayed titles where none of the
words were contained in the title, author or year, but in the text of
the abstract and notes of the item page. 

2 - single journal volumes were displayed for serial runs, they
blocked all intelligent search attempts and spammed the results list
with over and over the same journal title. 
- it was generally very difficult (better say, practically impossible)
  to test for completeness of results. restricting search for (1) only
  in title, author and date and (2) exclude journal metadata of single
  journal volume item pages (and instead create one single journal title
  hit) would probably solve the problems.

Francisco

---

F. Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536, Fax +49 551 395579
http://www.gwdg.de/~fwelter
http://www.animalbase.org

**Comment by akohlbecker** [comment]
@JiriFrank I guess this ticket should be assigned to jan, since it is on the facet list

**Comment by akohlbecker** [comment]
@lobajuluwa, @JiriFrank I will reassign this ticket to jan, since it is obviously on the facet list.

**Comment by lobajuluwa** [comment]
The function of the facet list has been improved: sort return by relevance - title, date, author, year etc - this is now done and ready for testing. 

Close Issue.
