### ISSUE TITLE
1.4.5 - Display scan quality (Result list)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#65]
Indicate scan quality (start rating system or technical data, e.g. resolution)

Precondition: 
technical information in metadata, e.g. resolution,
user feedback/ crowd sourcing system

**Comment by fwelter** [comment]
User feedback:
Scan and metadata quality for each item would be ranked by the users in a 5-point scale (implies providing two sets of 5-point scale radio buttons for ranking scan quality and metadata quality, so that the users can select a value and submit). 5-point scales: from bad to good: 0, 20, 40, 60, 80, 100. 
"Submit your ranking for scan quality (0 = bad, 100 = good)"
"Submit your ranking for metadata quality (correct page numbers, chapters etc.; 0 = bad, 100 = good)"
The artithmetic mean values would be displayed. In the search results lists, behind the content provider/contributor in the same line.

Display in results list (see #61):

Jong, de C. 1953
A "new" Nitidulid Beetle from Sumatra
Zoologische Mededelingen 32: 43-47
NCB Naturalis. Scan quality: 96. Metadata quality: 87.

Smit J.T. 2009
2nd meeting of the European stag beetle group
NCB Naturalis. Scan quality: 96. Metadata quality: 87.

**Comment by lobajuluwa** [comment]
Update from Portal Review Workshop_The Hague: Resolution should be in the metadata. (March Release 2012)
