### ISSUE TITLE
2.1.9 - Hold local copy of information provided by web services

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#82]
Counteraction if Web Services are down

2 options: 
Setup a proxy to cache external webservice requests
Mirror/local backup of Ubio, species 2000, etc.

**Comment by wkollernhm** [comment]
Right now webservice calls are cached using the internal drupal caching system. Thus if the webservice is down but the request was made before it will just return the cached result.
If the request wasn't done before, the module will return an error code so that calling functions can react (like displaying a note).

I would suggest we keep that behaviour for all of our webservices.

**Comment by janahoffmann** [comment]
@wkollernhm
@lobajuluwa
I agree. Can we close this issue then?

**Comment by wkollernhm** [comment]
This also applies to not yet implemented webservice modules, so I would like to keep this open until all modules are in place - I will close it once it is done.

**Comment by wkollernhm** [comment]
I've changed this issue to the January 2012 milestone, as this is an ongoing issue, but implemented for all modules for the november sub-release.
