### ISSUE TITLE
3.1.1 - View Content (Content view)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#83]
Display content (OCR text or pdf) with various functionalities
 minimum time for loading page (5sec), 
indicate loading process of page
--> compare with BHL portal book viewer

Precondition: OCR for all items

**Comment by fwelter** [comment]
This one or #89 (3.1.7): display page-level metadata scrollbox.

Must be possible to see in a scrollbox immediately how many pages the work has. IA bookviewer does not have this scrollbox, this is the most serious shortcoming of that bookviewer. 

Page-level scrollbox:

Left column: page number in digitised document, preferrably to be displayed in [ ] square brackets
Right column: page number in original source

Examples: BHL, DFG Viewer. Not Gallica.

Highest priority for this feature.

**Comment by JiriFrank** [comment]
Not implemented on the portal yet. Digital object contains URL which needs to be copy/paste in the browser. There are several depositories which show just the pdf. The book viewer is in this case actually Acrobat reader. Only the URL to the Open library BookReader presentation has a design of the online book viewer.

In this phase the book viewer is not testable, because is not implemented on the portal and don’t provide any functions.

---

On another hand the book viewer from Open Library or from the Australian portal have many useful options which are also requirements. I will prefer the Australian portal book viewer (link for example http://bhl.ala.org.au/item/21251#page/8/mode/2up).

**Comment by janahoffmann** [comment]
I agree with the comment above - issue needs to be reopened.

**Comment by JiriFrank** [comment]
3.1.1 - View Content (Content view)

COR number: 3.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Display content (OCR text or pdf) with various functionalities
minimum time for loading page (5sec), 
indicate loading process of page
--> compare with BHL portal book viewer

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by JiriFrank** [comment]
3.1.1 - View Content (Content view)

COR number: 3.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Display content (OCR text or pdf) with various functionalities
minimum time for loading page (5sec), 
indicate loading process of page
--> compare with BHL portal book viewer

You can reach the content viewer by click on Read book in result list.

@AntonioGVH
@fwelter
@LarissaS

**Comment by LarissaS** [comment]
Hurray, I found how to view the book! Via the button "reed book"! And it works! 
I checked RMCA books and quality is ok, with zoom text doubles, but still readable (less good quality than the original files?). 
Did not find in book viewer the lower ruler (to move page left-right), when for example I zoomed the illustration and want to see it in details. 
For downloading: in bibliographic record viewer button download does not work. 
From content viewer it works, but it took me some minutes to understand that if I want to download I have to switch "select the whole literature". Why there is no help for downloading? Because I was also thinking may be I should first log in?! Still could not download one page and no help!

Downloading was rather fast.
"Indicating loading process" - have not seen!

-----Original Message-----

**Comment by HenningScholz** [comment]
Content viewer seems to work faster compared to BHLUS book viewer, in particular when flipping back and forth a lot of pages at once. No indication of loading process.

When clicking on the OCR button and close the popup, the content viewer disappears and I see an empty window.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 15:16
An: Scholz, Henning
Betreff: Re: [bhle] 3.1.1 - View Content (Content view) (#83)

3.1.1 - View Content (Content view)

COR number: 3.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Display content (OCR text or pdf) with various functionalities
minimum time for loading page (5sec),
indicate loading process of page
--> compare with BHL portal book viewer

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by RalfH** [comment]
It works excellent and loading is very fast. Starting with simple or advanced search you have your result (a certain page) within less than 5 sec - as far as you know the basic functionalities.

As stated before: Works only by using Firefox. pdf production is ok, OCR not really satisfying (copy+paste to word?).

Comparison with BHL portal book viewer (which I know quite a while): I need more time for same (or similar results). The BHL icon which combines printing & download functionalities is misleading. BHL-E is more selfexplanatory.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:17
An: Hand, Ralf
Betreff: Re: [bhle] 3.1.1 - View Content (Content view) (#83)

3.1.1 - View Content (Content view)

COR number: 3.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Display content (OCR text or pdf) with various functionalities
minimum time for loading page (5sec), 
indicate loading process of page
--> compare with BHL portal book viewer

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment]
Cannot get the book reader to work using IE 8.0. Not letting me scan from page to page at all. 
Using Firefox 9.0 I can open book and scan from page to page, also open OCR for selected pages. However cannot get the download function to work.  The page selector and download function are similar to BHL-Australia which I've used, and find quite easy to navigate. Being able to see page thumbnails is a great help, this is not possible in BHL-US.

Have successfully downloaded two colour plates from a book, at medium resolution, image not bad, captions quite fuzzy. Now firewall on RBGE system preventing me from opening download file.

**Comment by AntonioGVH** [comment]
Excellent response. 
I have downloaded  the front page of Flora de Catalunya in less than two seconds.

Viewing BHL 'Great and small game of Africa' took about ten seconds for the first page.

Quoting JiriFrank:

**Comment by AnneSch** [comment]
Does not work with IE8, but with actual Firefox.

In general, Content viewer works fine. You can scroll pretty fast. 
But I did not manage to download a page or something. Same problems as Larissa. 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:17
An: Scholz, Annemarie
Betreff: Re: [bhle] 3.1.1 - View Content (Content view) (#83)

3.1.1 - View Content (Content view)

COR number: 3.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Content viewer

Description:

Display content (OCR text or pdf) with various functionalities
minimum time for loading page (5sec), 
indicate loading process of page
--> compare with BHL portal book viewer

You can reach the content viewer by click on Read book in result list.

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment]
@LarissaS 
For moving in on page in zoom you need to use mode one-page view. In two-page view every move to left or right will turn the page. I discussed the possibility with Zheng and he will adapted it also for two-page view mode.
                 "Did not find in book viewer the lower ruler (to move page left-right), when for example I zoomed the illustration and want to see it in details."

Bibliographic page is still not ready, because we need to have the final content form from PI to finish it functionality. So it is just waiting for the real content now.
                 "For downloading: in bibliographic record viewer button download does not work."

@HenningScholz 
The OCR correction is not implemented yet. Issue #131

**Comment by JiriFrank** [comment]
Works fine and with adaptation for moving in zoom in two-page mode, it could be closed.

**Comment by JiriFrank** [comment]
Moving on page in zoom you can use two-page view from now. It is fixed. Zoom out for turn page or use the arrows in footer left menu.

@LarissaS

**Comment by LarissaS** [comment]
Yes, it works but not always, sometimes it springs to another page. 
Other thing: still have to push two times on search button to start searching!

-----Original Message-----

**Comment by JiriFrank** [comment]
You need to refresh your browser using F5 or ctrl+shift+R.

The search on the front page is different issue which is related with auto-complete search.
@LarissaS
