### ISSUE TITLE
3.1.9 - Print item (Content view)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#91]
Click on button: print (not download) volume, page (actual page and page range)
- implement 'safe the environment' button ;-)

Precondition: pagination

**Comment by JiriFrank** [comment]
Not implemented in book viewer yet. Not testable.
See comment on #83

**Comment by janahoffmann** [comment]
not implemented - issue needs to be reopened

**Comment by zhengl** [comment]
Pagination is not available in AIP for the moment, we can only print per page now (From JPEGs in the Book Reader).

**Comment by janahoffmann** [comment]
@zhengLiAtos
Can we print the entire book/ volume?

**Comment by zhengl** [comment]
Not directly,
I suggest to print books or pages from PDF, otherwise it may cause some problems to the users due to the cross-browser difference.
@janahoffmann

**Comment by janahoffmann** [comment]
@zhengliatos
You mean after download?

**Comment by zhengl** [comment]
@janahoffmann
Yes, we can say so.
Because although we can re-organize pages in a new web page and print it out, we cannot make sure the layout fits A4 paper, because every page may have different size or resolution.

I have studied the solution from BHL-US and BHL-Australia, one doesn’t provide on-line printing, and the other fails on Google Chrome and it only can print a page at a time.

**Comment by leenamba** [comment]
Decision during Nov 24th tech call that print will be done by downloading PDF and then printing PDF.
